### ISSUE TITLE
'sdk_package is incorrect' on real device

### ISSUE THREAD

**Issue by DmitrySikorsky** [VKCOM/vk-android-sdk#10]
There is no error with 'Sign In Using Vk' on emulator (Android 4.2.2), but on real device (HTC ONE, Android 4.3) after call

VKSdk.authorize(SignInActivity.vkScopes)

I get

{"error":"invalid_request","error_description":"sdk_package is incorrect"}

**Comment by lectricas** [comment]
Give me this error, every time I try to use VK in my app. Everything was nice couple of weeks ago. Package name and MainActivity are filled correctly , I think.
MainActivity - MainActivity
Package name - com.fooBar 
from  - Manifest - <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.fooBar"

**Comment by v4ekmarev** [comment]
VKSdk.login(this, VKScope.WALL);
Открывается вью в которой отображается {"error":"invalid_request","error_description":"sdk_package is incorrect"} и кнопка "<-Вход", по нажатию на нее у меня заходит в приложение в вк, возвращается на предыдущее активити, но в коллбеке я попадаю в onFailure, что это за магия?

**Comment by v4ekmarev** [comment]
В общем в настройках приложения написано "Название пакета для приложения Android", ну я и скопировал из манифеста package, а как оказалось нужно было build.gradle, applicationId взять.... Спасибо за прозрачность=)

**Comment by IlyaEremin** [comment]
Моя проблема была в том, что я не удалил двоеточия из сгенерированного SHA1.

**Comment by Egrace** [comment]
Полностью согласен с v4ekmarev.
Абсолютно нигде не сказано что package нужно брать в build.gradle. Это вызвало довольно много мучений.

**Comment by IlyaEremin** [comment]
@Egrace Тот package что в `AndroidManifest.xml` переписывается тем, что написано в `build.gradle`. Поэтому это не косяк документации, а незнание того, что в итоге попадает в apk файл.

**Comment by fortrannew** [comment]
Сейчас в 2024 году изменили полностью сервис и теперь снова не работает и опять эту же ошибку отображает на некоторых устройствах, а на некоторых нормально работает. Пишет: sdk_fingerprint is incorrect

**Comment by limengGame** [comment]
It is already 2025. But I still meet this problem. Any can help me answer this question? 
"error":"invalid_request","error_description":"sdk_package is incorrect"
