### ISSUE TITLE
VKError (API errorVKError (code: 113; ; Invalid user id))

### ISSUE THREAD

**Issue by TymofiiKriuchkov** [VKCOM/vk-android-sdk#100]
Вызывая метод:
 VKRequest request = new VKRequest("friends.get", VKParameters.from(VKApiConst.FIELDS, "id,first_name,last_name,sex,photo_200_orig"));
раз получаю правильный ответ, другой раз получаю ошибку: VKError (API errorVKError (code: 113; ; Invalid user id))

Request вызываю в doInBackground AsyncTask
VKSdk.authorize(sMyScope, false, true);

private static final String[] sMyScope = new String[] {
            VKScope.FRIENDS,
            VKScope.WALL,
            VKScope.NOHTTPS,
    };
Авторизация проходит каждый раз, а также каждый раз получаю access_token VKSdk.initialize(sdkListener, Constants.API_ID_VK, VKAccessToken.tokenFromSharedPreferences(getActivity(), accountVK.access_token));

Подскажите, с чем может быть это связано?

**Comment by Dreddik** [comment]
Зачем вы каждый раз проводите авторизацию?
Проводите авторизацию один раз:
1) инициализация
2) ожидание, пока пользователь предоставит разрешение
3) вызов метода
...
?) вызов метода

Возможно, в этом проблема

**Comment by TymofiiKriuchkov** [comment]
Авторизация проводится один раз, сценарий авторизации не меняется. Инициализация, ожидание, пользователь предоставляет разрешение. Но чаще вызывается onError(VKError error), где error - вышеприведенная ошибка. Успех или неудачу авторизации не могу объяснить. Подскажите, в какие случаях выводится данная ошибка?

**Comment by Dreddik** [comment]
А вы всегда вызываете этот метод без user_id?

**Comment by TymofiiKriuchkov** [comment]
Да, у меня всегда такие поля: "id,first_name,last_name,sex,photo_200_orig"

**Comment by sjkrypa** [comment]
Доброго времени суток, такая же проблема, только всегда получаю такую ошибку. Решили проблему?

**Comment by olegsm** [comment]
Please, follow new SDK 2.0
