### ISSUE TITLE
VK_AUTH - error: invalid_token

### ISSUE THREAD

**Issue by boyfox** [VKCOM/vk-android-sdk#101]
Hi, Some time I will be gets following error while authing via VK SDK:

{"error": "invalid_token", "error_description":"token is incorrect"}

I don't understand why appear this error? Do you can explain why appear this Error?
If still needed my implementation VK auth code, I can share it.

**Comment by Dreddik** [comment]
Hello. Is this error appears in VK application?

**Comment by boyfox** [comment]
Hi Dreddik, yes this error appeared when I did try authenticate via VK SDK.

**Comment by Dreddik** [comment]
Can you tell me user_id (or link) of the user you trying to authorize?

**Comment by boyfox** [comment]
Yes I can, my userId: http://vk.com/id171867174
Dreddik I have a extra question please answer to this question, too. Question : Some times users send me following error on authing: 
![auth_error](https://cloud.githubusercontent.com/assets/3168694/6796168/b9d1f58e-d20f-11e4-8284-24942beeb121.jpg) 
I didn't find final solution to this question, too. Please help me.

**Comment by GaidaiNikita** [comment]
У меня такая же беда... Все делал согласно документации... Но при попытке логина вылетает VKError с кодом -102, а в логах вот такая ж ошибка

**Comment by olegsm** [comment]
Please, follow new SDK 2.0

**Comment by boyfox** [comment]
> Please, follow new SDK 2.0

Oh, my God this a bug fixed after 4 years :)))(super fast). That a project which I used Vk SDK already closed :)))
