### ISSUE TITLE
Ошибка при публикации сообщения в группу (StringIndexOutOfBoundsException в VKApiBase)

### ISSUE THREAD

**Issue by lDg5ixb** [VKCOM/vk-android-sdk#102]
Здравствуйте!
Мое Android-приложение должно по нажатию кнопки делать скриншот экрана и публиковать его в группу Вконтакте. В этом месте (не всегда, но часто) возникает ошибка, происходящая в системных классах VK SDK. 

Не могли бы Вы подсказать, в чем может быть проблема?

Сама ошибка:
1) http://pastebin.com/RMgz4b6c
2) http://pastebin.com/Zrk83CD7

Фрагмент кода приложения - публикация в группу
http://pastebin.com/CRVRPg0T

**Comment by Dreddik** [comment]
Мда, об обфускации я как-то не подумал

**Comment by lDg5ixb** [comment]
Ошибки не возникает, если делать apk-debug (вылетает только на apk-release). Или если выключить proguard (minifyEnabled false).

**Comment by Dreddik** [comment]
Нужно изменить настройки proguard, добавив '-keep class com.vk.** { *; }'

**Comment by lDg5ixb** [comment]
Да, спасибо. Я так и сделал.
