### ISSUE TITLE
Ошибка VKError "Invalid hash" в запросе метода API photos.saveMessagesPhoto

### ISSUE THREAD

**Issue by KBiakov** [VKCOM/vk-android-sdk#105]
Здравствуйте!

Возник следующий вопрос по поводу метода photos.saveMessagesPhoto. Я работаю над приложением, которое использует Android VK SDK. Мне нужно прикрепить изображение к сообщению, делаю все по документации:
1. Получаю адрес для загрузки методом photos.getMessagesUploadServer.
2. Создаю post-запрос, передаю изображение, парсю ответ - на выходе получаю server, photo, hash.
3. Передаю полученные данные из п.2 в photos.saveMessagesPhoto, который выдает ошибку "invalid hash".

Хотя в документации сказано, что полученные в п.2 строки из ответного json-объекта никак не должны быть модифицированы, с исходными данными функция из п.3 выдает ошибку, ссылаясь на пустой список photo_list. Хорошо, пытаюсь передать полученную строку photo как параметр photo_list для функции из п.3: "invalid hash".
Еще одним предположением было обрезать первый и последний символ строки hash, т.к. в распарсенном виде она содержит кавычки с обоих концов. Это не помогло: "invalid hash".

Итого, пробовал следующие варианты для устранения ошибки в вызове photos.saveMessagesPhoto:
1) передать параметры server, photo, hash в том виде, в котором их выдает post-запрос (ошибка - пустой список photo);
2) передать полученный от post-запроса photo как параметр photo_list и/или дочерний его объект photo (этого корневого элемента ответа post-запроса, он же псевдо-массив json) как параметр photo (ошибка: invalid hash) (также пробовал просто дочерний photo псевдо-массива photo - ошибка та же);
3) все то же самое, но с отброшенными кавычками для hash (ошибка: invalid hash).

Пожалуйста, подскажите, в чем может быть проблема? Исходный код моего класса, который решает эту задачу, можно посмотреть здесь: 
https://github.com/KBiakov/VKAuthRepository/blob/master/app/src/main/java/org/example/vkauth/ImageUploader.java
Последовательность действий, приведенная в документации, отмечена комментариями.

**Comment by Dreddik** [comment]
Посмотрите, например, на VKUploadWallPhotoRequest, и сделайте по аналогии

**Comment by KBiakov** [comment]
Вероятно, Вы имеете ввиду метод VKApi.uploadWallPhotoRequest, который постит на стену, есть еще аналогичный метод для стены, но такого удобного метода для сообщений нет, поэтому я и осуществляю всю последовательность действий вручную (как в документации для загрузки изображения в сообщение - vk.com/dev/upload_files). Я хочу получить на выходе attachment, чтобы затем использовать его в запросе messages.send как вложение.

**Comment by Dreddik** [comment]
Если вы задаёте вопрос по VK Android SDK, то VKUploadWallPhotoRequest - это класс реализующий загрузку фото на стену вместо вас. Если вы не используете VK SDK, то продолжайте мучаться)

**Comment by KBiakov** [comment]
Мне нужно прикрепить изображение к сообщению, а не запостить его на стену. VK SDK используется для осуществления запроса, который не проходит, выбрасывая ошибку. Или, в таком случае, вопрос выходит за рамки инструментария? Кому тогда можно задать вопрос по поводу того, почему post-запрос проходит и выглядит корректно, а полученные от него данные (причем как неизменные, т.к. и измененные с предположением о том, почему он их не хочет принимать) ни в каком виде не хотят принимать на следующем шаге?

**Comment by Dreddik** [comment]
Давайте ещё разок:
1) Есть класс `VKUploadPhotoBase` реализующий загрузку фотографий на сервера VK, в зависимости от необходимых методов
2) Есть классы `VKUploadAlbumPhotoRequest`, `VKUploadWallPhotoRequest`, унаследованные от `VKUploadPhotoBase`, реализующие загрузку фотографии в альбом или на стену всего лишь возвращением настроенных запросов
3) Вы создаёте свой `VKUploadMessagePhotoRequest`, унаследованный от `VKUploadPhotoBase`, в котором используете методы API `photos.getMessagesUploadServer` и `photos.saveMessagesPhoto`
4) Вы НЕ реализуете загрузку самостоятельно, так как в этом нет необходимости

**Comment by KBiakov** [comment]
Спасибо! Теперь понял, что нужно сделать.
