### ISSUE TITLE
Как получить auth_key?

### ISSUE THREAD

**Issue by 4ibo** [VKCOM/vk-android-sdk#107]
Подскажите пожалуйста, есть ли возможность получить auth_key в Android VK SDK, или как проверить на своем сервере подлинность авторизации в своем Android приложении?

**Comment by Dreddik** [comment]
Можно использовать https://vk.com/dev/secure.checkToken , передав туда токен, полученный через SDK

**Comment by sochka** [comment]
@Dreddik in the docs (https://vk.com/dev/secure.checkToken) it says "Checks the user authentification in IFrame and Flash apps using the access_token parameter". You are saying this works in Android SDK. Is it a mistake in the docs? 

Also, if I understand correctly, this doesn't prevent against this use case:


1. The app has authentication through VK (and possibly other auth providers + local username/password auth). 
2. The app has it's own backend. No other apps should be able to access that API.
3. Let's say VK auth is done through VK SDK. Which means that the token is received on the mobile side and sent to the server.
4. Now, image, there is a different app which uses VK authorization. They would be able to send the VK token to our server (the IP would be still correct, it's the user's phone).
5. On the backend, we cannot know who sent the token - our app or a different app. We authorize the user (in this "bad" app).
6. This second "alien" app has full access to our API just by asking the minimal scope access to VK itself.

In the case of Google, they have a more advanced system with signed JWT tokens and checking Android package name. In the case of VK, the only solution I see is doing server-flow with launching a browser (which would redirect the user back to *only* our app, not others) which somewhat harms UX of the app. Did I get everything right, maybe there is a better solution?
