### ISSUE TITLE
VkApiPost.parse() owner_id vs to_id

### ISSUE THREAD

**Issue by Minkfan** [VKCOM/vk-android-sdk#117]
При запросе wall.get в json c API версии 5.7 приходит параметр owner_id, а не to_id, как в текущей версии SDK. Это будет исправлено? Или можно как-то использовать более старые версии API в wall.get? Мне просто нужно понять, что делать: исправить самому под себя или может где-то есть ветка, в которой поддержка новых API оперативно ведется

**Comment by ray1984** [comment]
https://github.com/VKCOM/vk-android-sdk/blob/master/vksdk_library/src/main/java/com/vk/sdk/api/model/VKApiPost.java:49
to_id, а не owner_id как вы пишете

**Comment by Dreddik** [comment]
Измените на owner_id и сделайте pull request
