### ISSUE TITLE
VKAccessToken "expiresIn" and "created" properties

### ISSUE THREAD

**Issue by int02h** [VKCOM/vk-android-sdk#118]
I get confused about measurement units for  "expiresIn" and "created" properties inside class VKAccessToken. As it described in OAuth documentation "expiresIn" is UNIX time (so it is measured in seconds). But I cannot find any reference for "created" property.

I see the following source code:
```java
if (parameters.containsKey(CREATED)) {
     token.created = Long.parseLong(parameters.get(CREATED));
} else {
    token.created = System.currentTimeMillis();
}
```

So I can guess that "created" is measured in milliseconds (so it has long data type). But I doubt that CREATED field received from server also measured in milliseconds because only Android measures time in millis (similar property in iOS SDK is measured in seconds).

Maybe there is should be multiplication by 1000:
```java
token.created = Long.parseLong(parameters.get(CREATED))*1000;
```

In fact, in common auth flow there is no CREATED field in server response. Maybe first "if" branch is unnecessary and code should looks like:
```java
token.created = System.currentTimeMillis();
```

**Comment by Dreddik** [comment]
`CREATED` field isn't received from server, it is only local parameter to measure token lifetime.
In fact, a token will expire never, because every token is requested as "offline", that means it's `expires_in` field equals 0.
Token may become invalid only if user destroyed all sessions on the site.
