### ISSUE TITLE
vk-android-sdk и обфускация Proguard

### ISSUE THREAD

**Issue by nightmare00** [VKCOM/vk-android-sdk#120]
Как правильно настроить Proguard, чтобы vksdk_library правильно работала и не крашилась?
Падение происходит при отправке запроса к API для получения списка аудио альбомов.
https://gist.github.com/nightmare00/32f600ba537c31131704
proguard-rules.txt содержит:
-dontwarn com.vk.**
-dontshrink
-dontoptimize

**Comment by Dreddik** [comment]
'-keep class com.vk.** { *; }'

**Comment by nightmare00** [comment]
Хм, странно - все равно крашится там же.

**Comment by nightmare00** [comment]
proguard-rules.txt:

-keep class com.vk.** { *; }
-dontwarn org.seamless.**
-dontwarn org.eclipse.jetty.**
-dontwarn org.fourthline.**
-dontshrink
-dontoptimize

**Comment by Dreddik** [comment]
А это точно не у вас в коде крашится?
