### ISSUE TITLE
java.lang.IllegalStateException: Fragment e{41ccdcf0} not attached to Activity

### ISSUE THREAD

**Issue by lDg5ixb** [VKCOM/vk-android-sdk#121]
Здравствуйте! Код (http://pastie.org/10203439) практически аналогичен примеру.

Подскажите, пожалуйста, в чем может быть проблема.

Скриншот из fabric.io http://i.imgur.com/PCqX6Vm.png

**Comment by Dreddik** [comment]
Не могу зайти на pastebin.
Он заблокирован, и вдобавок сам сайт не пускает через анонимайзер

**Comment by lDg5ixb** [comment]
http://pastie.org/10203439

**Comment by Dreddik** [comment]
Я полагаю, что отмирает на getString()?

**Comment by lDg5ixb** [comment]
Роман, я не знаю, как узнать конкретную строку, где вылетает. Fabric такого не показывает, а на моих устройствах все работает.

Могу только попробовать убрать getString() и посмотреть, уйдет ли ошибка.

Я так понимаю, ошибка не связана с самим vk-sdk.

А почему вылетает, не смотря на try..catch?

**Comment by Dreddik** [comment]
Довольно странная аналитика крашей, которая не позволяет определить место краша, вам не кажется?)
Вы ловите только NullPointerException, а произошло другое исключение

**Comment by lDg5ixb** [comment]
Да, странная. Но я еще зеленый и по другому отслеживать не умею =)
Иногда fabric пишет конкретный номер строки с ошибкой, но не всегда.

Действительно, NullPointerException не заметил. Спасибо
