### ISSUE TITLE
Динамическая подгрузка данных по запросам

### ISSUE THREAD

**Issue by neufeld13** [VKCOM/vk-android-sdk#125]
Подскажите, как динамически подгружать результат запроса wall().get? В контексте работы этот метод возвращает некоторое количество последних записей со стены сообщества. 
Сейчас запрос формируется стандартно следующим образом:

currentRequest = VKApi.wall().get(VKParameters.from("domain", "musicsavestheworld", VKApiConst.COUNT, 30, VKApiConst.EXTENDED, 1));

Механизм подгрузки есть, но не знаю, как корректно поместить туда обработку самого запроса, чтобы, например, при скроллинге до конца списка подгружать 10 следующих более ранних записей.

**Comment by Lomovskiy** [comment]
AsyncTask, нет?

**Comment by neufeld13** [comment]
Разумеется, вопрос был немного в другом.
Но ответ уже найден: еще раз заглянул в документацию вспомнил про параметр offset, для которого объявил глобальную переменную.
