### ISSUE TITLE
Как получить фото профиля? 

### ISSUE THREAD

**Issue by fedorsolovey** [VKCOM/vk-android-sdk#126]
Необходимо получить все фотографии профиля пользователя, пытаюсь это сделать таким вот способом и приложение вылетает на строке цикла for each. Не исключаю того, что ошибка в предыдущей строчке, т.е. в парсинге.  Подскажите, как сделать правильно.

        VKRequest requestPhoto = new VKRequest("photos.get", VKParameters.from(VKApiConst.USER_IDS, user_idL.toString(), VKApiConst.ALBUM_ID, "profile"));
        requestPhoto.executeWithListener(new VKRequest.VKRequestListener() {
            @Override
            public void onComplete(VKResponse response) {
                super.onComplete(response);

                VKPhotoArray avataraArray = (VKPhotoArray) response.parsedModel;

                for (VKApiPhoto avatarkaFull : avataraArray) {

                   new DownloadImageTask((ImageView) findViewById(R.id.imageView3))
                            .execute(avatarkaFull.photo_130);
                }

**Comment by Dreddik** [comment]
У вас запрос ничего не парсит, поэтому обращение к parsedModel некорректно.
Нужно передать ещё два параметра при создании запроса: `VKRequest.HttpMethod.GET, VKPhotoArray.class`

**Comment by fedorsolovey** [comment]
Сделал         
VKRequest requestPhoto = new VKRequest("photos.get", VKParameters.from(VKApiConst.OWNER_ID,
                user_idL, VKApiConst.ALBUM_ID, "profile"), VKRequest.HttpMethod.GET, VKPhotoArray.class);
 и заработало. Буду дальше разбираться, спасибо.

**Comment by dan1603** [comment]
а что тут в данном случае user_idL
