### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by kamagrad-dev** [VKCOM/vk-android-sdk#131]
Hi I am trying to integrate the Vk.com android SDK into my cococs2dx game but am not able to post to the wall. The problem is when I ask for "wall" permission, I get stuck in loop where it keeps asking me to login again and again. My code is as follows:

	public void authorizeVK()
	{
		VKSdk.authorize("wall");
	}

 private final VKSdkListener sdkListener = new VKSdkListener() {
	        @Override
	        public void onCaptchaError(VKError captchaError) {
	            new VKCaptchaDialog(captchaError).show();
	        }
	        @Override
	        public void onTokenExpired(VKAccessToken expiredToken) {
	        }

	        @Override
	        public void onAccessDenied(final VKError authorizationError) {
	            new AlertDialog.Builder(VKUIHelper.getTopActivity())
	                    .setMessage(authorizationError.toString())
	                    .show();
	        }

	        boolean parseResponse (String jsonStr) {
	            boolean errorFlag = true ;
	           
	           JSONObject jsonObj = null ;
	            try {
	              jsonObj = new JSONObject (jsonStr);
	              JSONObject errorObj = null ;
	              
	              if (jsonObj.has ( "error" )) {
	                  errorObj = jsonObj.getJSONObject ( "error" );
	                   int  errCode = errorObj.getInt ( "error_code" );
	                   if (errCode == 14 ) {
	               	   errorFlag = false ;
	                  }
	              }
	           }
	           catch (JSONException e) {
	               e.printStackTrace ();
	           }
	           
	           return errorFlag;	
	       }
	        @Override
	        public void onReceiveNewToken(VKAccessToken newToken) {
	        
	        	Log.e("VKPost", "recieve access token");

	        		runOnUiThread(new Runnable() {
	    				public void run() {
	    					VKRequest request = VKApi.users().get();
	    					request.executeWithListener(new VKRequestListener() { 
	    			            @Override 
	    			            public void onComplete(VKResponse response) { 
	    			                //Do complete stuff 
	    			            	Log.e("VKPost","user info obtained" + response.responseString);
	    			            	JSONObject json = response.json;
	    			            	int id = 0;
	    			            	try {
										id = Integer.parseInt(json.getJSONArray("response").getJSONObject(0).getString("id"));
										Log.e("user id" , "id "+id);
									} catch (NumberFormatException e) {
										// TODO Auto-generated catch block
										e.printStackTrace();
									} catch (JSONException e) {
										// TODO Auto-generated catch block
										e.printStackTrace();
									}
	    			            	VKRequest request = VKApi.wall().post(VKParameters.from(VKApiConst.OWNER_ID, 0, VKApiConst.MESSAGE, "android post"));
	    			            	request.setModelClass(VKWallPostResult.class);
	    	    					request.executeWithListener(new VKRequestListener() { 
	    	    			            @Override 
	    	    			            public void onComplete(VKResponse response) { 
	    	    			            	Log.e("VKPost","photo posted " + response.responseString);
	    	    			            } 
	    	    			            @Override 
	    	    			            public void onError(VKError error) { 
	    	    			                //Do error stuff 
	    	    			            	Log.e("VKPost"," post failed " + error);
	    	    			            } 
	    	    			            @Override 
	    	    			            public void attemptFailed(VKRequest request, int attemptNumber, int totalAttempts) { 
	    	    			            	Log.e("VKPost"," post attemptFailed ");
	    	    			            } 
	    	    			        });
	    			            } 
	      			}
	    			});	
	        	}
	        @Override
	        public void onAcceptUserToken(VKAccessToken token) {
	        }
	    };

Please help with this.

**Comment by dkostryukov** [comment]
Try new SDK version
