### ISSUE TITLE
Catch successful authorization \ cancel event

### ISSUE THREAD

**Issue by NickPakhomov** [VKCOM/vk-android-sdk#133]
Is there any way I can catch authorization and cancel events so I can send specific intends when they occur? So far when I hit "cancel" or use "back" button, the webview \ app finishes, but the previous intent isn't shown fully, there's 50% opacity black layer on top of it.

For auth event: I have button that calls VKSdk.authorize() when I click it, is there any way to specify new intent when I successfully authorize? So far I have to click the button 2 times to actually go to Activity that strictly requires VK authorization.

Stackflow question here as well: http://stackoverflow.com/questions/31541104/vk-sdk-any-way-to-catch-authorize-completion-or-cancel

**Comment by Dreddik** [comment]
Check out new version, there are special callbacks for authorization
