### ISSUE TITLE
!!! Миграция на версию 1.5 (Migration to version 1.5)

### ISSUE THREAD

**Issue by Dreddik** [VKCOM/vk-android-sdk#134]
В версии 1.5 изменилось несколько важных вещей:
1) [APP_ID необходимо прописывать в манифесте приложения] (https://github.com/VKCOM/vk-android-sdk#sdk-initialization)
2) [Для логина осталось 2 метода] (https://github.com/VKCOM/vk-android-sdk#user-authorization)
3) Изменился сам процесс авторизации, убран VKUIHelper. Обратите внимание на обновлённый [механизм обработки результата авторизации] (https://github.com/VKCOM/vk-android-sdk/blob/master/VKTestApplication/src/main/java/com/vk/vktestapp/LoginActivity.java#L97)
4) Для отслеживания изменения Access Token появился специальный абстрактный класс, [пример использования] (https://github.com/VKCOM/vk-android-sdk#handling-accesstoken-invalide)
5) Все запросы идут через POST, больше не нужно указывать тип HTTP запроса

Задавайте вопросы по миграции здесь.

In version 1.5 changed several important things changed:
1) [Move APP_ID in application manifest] (https://github.com/VKCOM/vk-android-sdk#sdk-initialization)
2) [Now only 2 methods for login] (https://github.com/VKCOM/vk-android-sdk#user-authorization)
3) Authorization process changed, VKUIHelper removed. Pay attention to updated [processing of login result] (https://github.com/VKCOM/vk-android-sdk/blob/master/VKTestApplication/src/main/java/com/vk/vktestapp/LoginActivity.java#L97)
4) Track access token with new access token tracker, [see example usage] (https://github.com/VKCOM/vk-android-sdk#handling-accesstoken-invalide)
5) All requests now using POST, there is no need to specify HTTP type of VKRequest

Ask your questions about migration here

**Comment by Y-E-P** [comment]
import com.vk.sdk.VKSdkListener
не импортиться,чем заменить его??

**Comment by alexqill** [comment]
Использовал в сервисе явное указание контекста приложения 

VKUIHelper.setApplicationContext(this);

Иначе не отправлялись запросы к API

Чем теперь заменить?

**Comment by BeetLab** [comment]
Вашу мать а! Вы про совместимость версий что-нибудь слыхали?! Не это возмутительно! Мейлгруп совсем испортила все!

**Comment by Dreddik** [comment]
@Y-E-P для логина используется следующая схема
```
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        VKCallback<VKAccessToken> callback = new VKCallback<VKAccessToken>() {
            @Override
            public void onResult(VKAccessToken res) {
                // User passed Authorization
                startTestActivity();
            }

            @Override
            public void onError(VKError error) {
                // User didn't pass Authorization
            }
        };

        if (!VKSdk.onActivityResult(requestCode, resultCode, data, callback) ) {
            super.onActivityResult(requestCode, resultCode, data);
        }
    }
```

Для отслеживания токена используется token-tracker (пример из демо-приложения)
```
VkAccessTokenTracker vkAccessTokenTracker = new VkAccessTokenTracker() {
        @Override
        public void onVKAccessTokenChanged(VKAccessToken oldToken, VKAccessToken newToken) {
            if (newToken == null) {
                Toast.makeText(Application.this, "AccessToken invalidated", Toast.LENGTH_LONG).show();
                Intent intent = new Intent(Application.this, LoginActivity.class);
                intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TOP);
                startActivity(intent);
            }
        }
    };

    @Override
    public void onCreate() {
        super.onCreate();
        vkAccessTokenTracker.startTracking();
        VKSdk.initialize(this);
    }
```

**Comment by alexqill** [comment]
BeetLab, ставлю на то что обнаружили фатальную уязвимость в авторизации, по тому и нет совместимости, на перелопачивание старого кода тупо забили.

**Comment by Dreddik** [comment]
@alexqill ничем. Нужно инициализировать SDK с контекстом приложения один раз при создании приложения или сервиса.

**Comment by Dreddik** [comment]
@BeetLab мне вообще-то пофиг на совместимость, это следующая версия. Не нравится - используйте версию 1.3.9. Если есть какие-то вопросы по миграции – задавайте.
Во некоторых местах постарались оставить обратную совместимость

**Comment by BeetLab** [comment]
@Dreddik - господа, с матюгами переборыч. Звиняйте. Стало быть - просто compile 'com.vk:androidsdk:1.3.9' и всё будет?

**Comment by Dreddik** [comment]
@BeetLab да.

**Comment by BeetLab** [comment]
@Dreddik До земли!

**Comment by BeetLab** [comment]
@Dreddik  - но перепиливать все равно придется - у Вас колбеки самого приложения изменились? Т.е. в активити резалте и проч проч - включая новые изменения в манифест?

**Comment by Dreddik** [comment]
@BeetLab если перелезете на версию 1.5 – придётся. Версии 1.3.9 всё по-старому

**Comment by vkotovv** [comment]
Правильно я понимаю, что Class reference в конце README устарел?

**Comment by Dreddik** [comment]
@vkotovv нет, она в актуальном состоянии.

**Comment by nindzyago** [comment]
"sdk_package is incorrect" при логине на 1.3.9 это из-за этого происходит ?

**Comment by Lomovskiy** [comment]
Здравствуйте, теперь получаю NPE при попытке инициализировать SDK VKSdk.initialize(this.getApplicationContext());
Вот StackTrace:
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference.
Что делаю не так? В манифесте meta-data с AppID присутствует.

**Comment by Dreddik** [comment]
@Lomovskiy снова переделали. Теперь нужно указывать app_id в ресурсах
```<integer name="com_vk_sdk_AppId">your_app_id</integer>```

**Comment by Lomovskiy** [comment]
xD

**Comment by NickPakhomov** [comment]
Недавно перестал успешно получать e-mail пользователя. После авторизации вызываю метод VKAccessToken.currentToken() и забираю там e-mail. Теперь большинство полей там пишет как null.

<img width="438" alt="screen shot 2015-08-09 at 12 03 43 pm" src="https://cloud.githubusercontent.com/assets/7837662/9154260/bc4c476a-3e8e-11e5-9f64-3f33c4f428bf.png">

**Comment by enterpredator** [comment]
@Dreddik, спасибо за обновку!
Будет ли поддержка VKSdk.login(...) метода для android.support.v4.app.Fragment?

**Comment by airstep** [comment]
Можно ли сохранять токен в настройках и как это правильно оформить? Как проверить токен потом на валидность? Раньше было VKSdk.initialize для этого и функция ивента                 public void onTokenExpired(VKAccessToken expiredToken)....

Еще интересует public void onCaptchaError(final VKError captchaError) как правильно ловить капча ошибки?

**Comment by NAO3133** [comment]
Есть ли возможность указать id приложения для Android SDK не в ресурсах проекта? Я работаю с AIR приложением, и пишу ANE для работы с Вашим SDK. Эту ANE будут использовать несколько проектов, у которых, соответственно, разные ID приложений, и держать для всех проектов разные копии VKSDK, которые будут различаться лишь упакованным в ресурсы ID проекта - крайне неудобно. Подскажите пожалуйста, как быть? Реализация IOS SDK в этом плане намного удобнее - передаешь ID в метод инициализации SDK, и всё тут.

**Comment by Dreddik** [comment]
@NAO3133 такая возможность есть. Метод initialize(Context applicationContext, int appId, String appVer)

**Comment by NAO3133** [comment]
@Dreddik да, только этот метод приватный

**Comment by NAO3133** [comment]
@Dreddik нашел, customInitialize(Context ctx, int appId, String apiVer)

**Comment by frakc** [comment]
https://github.com/VKCOM/vk-android-sdk/issues/178 после VKsdk.logIn() всегда возвращается ошибка с кодом VK_CANCELED

**Comment by caxerabc** [comment]
У меня такая ошибка:
{"error":"invalid_request","error_description":"sdk_package is incorrect"}.
Перепробовал все на что мозгов хватило. Уже неделю пытаюсь разобраться... С другой библиотекой все работает. Где ошибка то?

**Comment by Summonerrk** [comment]
{"error":"invalid_request","error_description":"sdk_package is incorrect"}.
То же самое. Перепробывал всё.
