### ISSUE TITLE
Где взять параметры для account.registerDevice ?

### ISSUE THREAD

**Issue by nethergrim** [VKCOM/vk-android-sdk#135]
Добрый день! 
Делаю вк приложение на андроид, остановился на подписке на push уведомления.

Не понимаю где взять параметры token и device_id для этого запроса. Для этого нужно использовать C2DM или GCM ? Пожалуйста, объясните как можно более подробно где я могу взять эти параметры. Спасибо!

ps C2DM сервера выключаются 30 июля 2015, так как эта технология deprecated

**Comment by Dreddik** [comment]
Используйте GCM. Получайте token, как описано здесь https://developers.google.com/cloud-messaging/android/client в секции "Obtain a registration token".
device_id генерируете самостоятельно. Это может быть android id http://stackoverflow.com/a/2785493/1271424 , либо любой другой сгенерированный вами достаточно уникальный идентификатор (guid)

**Comment by nethergrim** [comment]
Спасибо! =)

**Comment by nethergrim** [comment]
Еще маленький вопрос по настройке GCM:
В настройках приложения :
<img width="819" alt="2015-07-23 12 26 36" src="https://cloud.githubusercontent.com/assets/5869863/8847329/6a27325c-3136-11e5-9699-5268539b2bda.png">
в project id и simple api key надо вставлять ключи из 
<img width="928" alt="2015-07-23 12 26 45" src="https://cloud.githubusercontent.com/assets/5869863/8847339/82910390-3136-11e5-8e78-c7cb557620cd.png">

sender Id и Server API key соответственно? Или другие ключи? Спасибо!

**Comment by Dreddik** [comment]
Вроде всё так. Напишите id приложения

**Comment by nethergrim** [comment]
@Dreddik 4579411

**Comment by Dreddik** [comment]
А запрос account.registerDevice проходит успешно?
Какие параметры передаёте?

**Comment by nethergrim** [comment]
@Dreddik 
Да, судя по всему успешно, result code = 1.
Параметры:
"system_version" -> "22"
"device_model" -> "android"
"token" -> "fQdP00xcGA4:APA91bHSH31RlfAPAbeTrcE6Wt63M28g99EN67D1MIkmKZhzpY0EeCzKygqC0w-nPayzYAKvY7ueQgjfLS1sm5iGIT-tpBXsqCL1JnrTdMKYfdRjDMQejo1-9m9xprH-iUEWgUnUm6Q5"
"device_id" -> "b907a35878609a25"

**Comment by Dreddik** [comment]
Возможно, проблема в том, что вы забыли передать settings

**Comment by nethergrim** [comment]
@Dreddik оу.... сейчас добавлю, спасибо за наводку!

**Comment by nethergrim** [comment]
@Dreddik да, дело было в этом, и еще в том что я использовал API 5.21 (давно не обновлял), обновил APi версию, добавил сеттингсы, заработало =)
Будете в Харькове - с меня пиво :+1:

**Comment by Dreddik** [comment]
:+1: 
Только будьте внимательны, некоторые модели в SDK пока не предназначены для новой версии

**Comment by esseckers** [comment]
Всем привеб.

Ребят а как должен выглядеть параметр settings? то есть что туда передавать?

Зарание, спасибо.

**Comment by Dreddik** [comment]
@esseckers https://vk.com/dev/push_settings
Туда передавать json-строку, содержащую нужные параметры

**Comment by esseckers** [comment]
Спасибо, за ответ.

Я прошу прощения, если задаю глупые вопросы.

Передовать что-то вроде этого {"msg":"on", "friend":"on", "reply":"on", "mention":"fr_of_fr"} , правильно?

Когда я так делаю VK выкидывает ошибку: VKError (API errorVKError (code: 100; ; One of the parameters specified was missing or invalid: settings is accepted only from version 5.31))

vk sdk ставлю - compile 'com.vk:androidsdk:1.6.2' или compile 'com.vk:androidsdk:+'

Вот как ее победить?

Спасибо.

**Comment by esseckers** [comment]
Ребят, подскажите, плиз, до НГ нужно сделать(((

**Comment by Dreddik** [comment]
Нужно инициализировать SDK через customInitialize, указав версию выше 5.31

**Comment by esseckers** [comment]
Спасибо, огромное, заработало!!! Извините, за беспокойство.

**Comment by lectricas** [comment]
ай да описание сдк. Что бы найти почему не работает нужно с собаками искать по гитхабам и теребить дредика за вымя.

**Comment by shagspb** [comment]
Привет. ID приложения 5641592.

В документации указана настройка с помощью GCM. Но GCM мигрировал на FCM. 
Не приходят уведомления.

Настройки:
projekt_id 847695575415
Simple API Key: ***********************************************
"token", FirebaseInstanceId.getInstance().getToken()
, "device_model", "android"
, "device_id"
, Settings.Secure.getString(this.getContentResolver(), Settings.Secure.ANDROID_ID)
, "system_version", 1
, "settings", "{"msg":"on", "chat":["no_sound","no_text"], "friend":"on", "reply":"on", "mention":"fr_of_fr"}"

В ответ приходит: {"response":1}. (тоесть все ОК).

account.getPushSettings 
ответ:
{"response":{"settings":{"msg":["on"],"chat":["on","no_sound","no_text"],"friend":["on"],"friend_found":["off"],"friend_accepted":["off"],"reply":["on"],"comment":["off"],"mention":["on","fr_of_fr"],"like":["off"],"repost":["off"],"wall_post":["off"],"wall_publish":["off"],"group_invite":["off"],"group_accepted":["off"],"event_soon":["off"],"tag_photo":["off"],"app_request":["off"],"sdk_open":["off"],"new_post":["off"],"snap":["off"],"birthday":["off"],"money_transfer":["off"]},"conversations":{"count":2,"items":[{"user_id":2000000001,"chat_id":1,"sound":1,"disabled_until":1},{"user_id":2000000002,"chat_id":2,"sound":0,"disabled_until":-1}]}}}

Помогите плиз!

**Comment by nainkazi** [comment]
shagspb did you solve this issue please help me i am not getting push notification from VK.
and also what to pass as token in "account.registerdevice", you passed "FirebaseInstanceId.getInstance (). getToken ()" so i dont understand what to pass i am passing VKSDK token which i am getting from VKSDK when loggedIN.
