### ISSUE TITLE
Не могу добавить scope, ошибка в VKSdk.onActivityResult

### ISSUE THREAD

**Issue by ioerrorle** [VKCOM/vk-android-sdk#139]
Две проблемы:
1) Когда я пытаюсь сделать из своего активити `VKSdk.login(this, VKScopes.EMAIL);` то VKSdk.onActivityResult делает ровным счетом ничего. VKCallback просто не срабатывает, ни onResult, ни onError.
2) Посмотрев в исходники, я увидел следующий код:
`if(resultCode == -1) {
vkCallback.onResult(VKAccessToken.currentToken());
} else if(requestCode == 0) {
vkCallback.onError((VKError)VKObject.getRegisteredObject(data.getLongExtra("vk_extra_error_id", 0L)));
}`
Мне показалось это подозрительным и я поменял else if на 
`} else if(resultCode == 0) {`
и получил в errorCode, что оказывается запрос был отменен (canceled).
В приложении все фингерпринты и активити указаны, что я делаю не так?

**Comment by ioerrorle** [comment]
Добавлю, что нет никакой информации о том, в каком формате указывать основную activity в настройках приложения. Указывать package или нет? полный путь типа com.application.id.activites.package.MainActivity или activites.package.MainActivity или MainActivity?
В смысле, если activity лежит не в корне, то надо ли указывать к ней путь.

**Comment by ioerrorle** [comment]
АПДЕЙТ.
Вопрос решён.
VKOpenAuthActivity:142
`if(extraData.contains("error")) {
                    VKOpenAuthActivity.this.setResult(0, data);
                } else {
                    VKOpenAuthActivity.this.setResult(-1, data);
                }`
Мой e-mail содержит в себе строку "error". Поправьте ошибку.

**Comment by dkostryukov** [comment]
А какую версию библиотеки используете?

**Comment by ioerrorle** [comment]
1.5.1. Возможно, я неверно указал строку - смотрел из декомпилированой библиотеки.
