### ISSUE TITLE
Не найден нужный символ data в onActivityResult

### ISSUE THREAD

**Issue by Kerosinka** [VKCOM/vk-android-sdk#140]
Здравствуйте. В процессе работы я столкнулся с одной проблемой. Проект выдал ошибку на этапе сборки. Gradle сказал мне что в классе VKSdk не найдено нужное поле. И действительно, в методе onActivityResult(...) есть вызов data.getLongExtra(...), но поля data нет во всём классе. Чтобы sdk заработало мне пришлось закомментировать эту строку, но я полагаю с этим надо что-то решать.

**Comment by dkostryukov** [comment]
public static boolean onActivityResult(int requestCode, int resultCode, <b>@NonNull Intent data</b>, VKCallback<VKAccessToken> vkCallback) {
...
VKObject.getRegisteredObject(data.getLongExtra(VKSdk.EXTRA_ERROR_ID, 0)));
...
}

поле дата приходит в метод параметром, это Intent data

**Comment by Kerosinka** [comment]
хорошо, спасибо, я исправлю
