### ISSUE TITLE
Опечатка в VKSdk.onActivityResult()

### ISSUE THREAD

**Issue by abler98** [VKCOM/vk-android-sdk#143]
В методе onActivityResult класса VKSdk, в условии допущена ошибка: в строке
} else if (requestCode == VKSdk.RESULT_ERROR) {
вместо resultCode написано requestCode. Таким образамо метод onError никогда не вызывется.

**Comment by Hippeistudio** [comment]
v1.5.1 та же ошибка
`else if (requestCode == VKSdk.RESULT_ERROR)`
