### ISSUE TITLE
Gradle project sync failed.

### ISSUE THREAD

**Issue by Lomovskiy** [VKCOM/vk-android-sdk#148]
При открытии тестового приложения в Android Studio получаю следующую ошибку:
Error:(1, 0) Plugin with id 'com.android.application' not found.
Подскажите, как исправить?

**Comment by Dreddik** [comment]
Попробуйте обновить компоненты android studio

**Comment by Dreddik** [comment]
Какие-нибудь изменения?

**Comment by Lomovskiy** [comment]
Присоединяясь к проблеме.Тестовый проект не открывается в Android Studio по тпкой же причине. Но мне хватает исходников на GitHub, поэтому на эту тему вопрос не поднимал.

**Comment by lxknvlk** [comment]
при чем тут твой градл и сдк вк???

**Comment by Lomovskiy** [comment]
Во-первых, не "твой", а " Ваш", а во-вторых мой Gradle пока разворачивал все проекты, кроме этого.

**Comment by Lomovskiy** [comment]
Изменений никаких, вопрос больше не актуален, хотя и не решан.

**Comment by Dreddik** [comment]
Скорее всего, у вас gradle устарел или что-то в этом роде.
Пробовали http://stackoverflow.com/a/25232725/1271424 ?
