### ISSUE TITLE
версия 1.5.1 NPE Unable to resume VKServiceActivity

### ISSUE THREAD

**Issue by coralinejones1985** [VKCOM/vk-android-sdk#149]
Fatal Exception: java.lang.RuntimeException
Unable to resume activity {com.wachanga.android/com.vk.sdk.VKServiceActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10485, result=0, data=Intent { (has extras) }} to activity {com.wachanga.android/com.vk.sdk.VKServiceActivity}: java.lang.NullPointerException

android.app.ActivityThread.performResumeActivity (ActivityThread.java:3002)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3031)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2415)
android.app.ActivityThread.access$800 (ActivityThread.java:155)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1331)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:5395)
java.lang.reflect.Method.invokeNative (Method.java)
dalvik.system.NativeStart.main (NativeStart.java)

Caused by java.lang.NullPointerException
android.preference.PreferenceManager.getDefaultSharedPreferencesName (PreferenceManager.java:378)
android.preference.PreferenceManager.getDefaultSharedPreferences (PreferenceManager.java:373)
com.vk.sdk.VKAccessToken.tokenFromSharedPreferences (VKAccessToken.java:236)
com.vk.sdk.VKAccessToken.currentToken (VKAccessToken.java:275)
com.vk.sdk.VKSdk.updateLoginState (VKSdk.java:410)
com.vk.sdk.VKSdk.updateLoginState (VKSdk.java:406)
com.vk.sdk.VKSdk.processActivityResult (VKSdk.java:220)
com.vk.sdk.VKServiceActivity.onActivityResult (VKServiceActivity.java:184)
android.app.Activity.dispatchActivityResult (Activity.java:5469)

**Comment by coralinejones1985** [comment]
Не знаю, связана ли эта задача с #123, но похожа

**Comment by dkostryukov** [comment]
1) Вы вызываете в Application#onCreate() инициализацию - VKSdk.initialize(this) ?
2) стабильно ли у вас повторяется эта ошибка?

**Comment by coralinejones1985** [comment]
1. Да
2. 3 раза (у трех разных пользователей)

**Comment by dkostryukov** [comment]
А какая версия SDK?

**Comment by coralinejones1985** [comment]
1.5.1

**Comment by dkostryukov** [comment]
Вызываете ли вы какие-либо методы SDK перед VKSdk.initialize(this)?

**Comment by coralinejones1985** [comment]
Нет, вот как это выглядит:

@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        VKSdk.initialize(this);
    }

**Comment by dkostryukov** [comment]
У объекта Application метод onCreate не принимает Bundle, может вы делаете это в Activity, а не в Application?

**Comment by dkostryukov** [comment]
Данный баг был из-за использования SDK отличным от документации способом

**Comment by dkostryukov** [comment]
Когда системе не хватает памяти, она выгружает приложение из памяти, после окончания авторизации, система пытается вызвать onActivityResult и воссоздает приложение. Так как вызов происходит в VKServiceActivity в момент ее создания SDK не проинициализировано, так как в данной активности SDK не инициализируется. Если реализовывать инициализацию в Application такого не произойдет, так как сначала система создаст Application и в этот момент произойдет инициализация. 
Таким образом, что бы воспроизвелся этот баг, нужно что бы система убила приложение, вызвавшее авторизацию, чаще всего такое происходит, когда системе не хватает памяти. Так как это происходит довольно редко, баг не постоянен.
