### ISSUE TITLE
NullPointerException при VKSdk.login 

### ISSUE THREAD

**Issue by coralinejones1985** [VKCOM/vk-android-sdk#150]
Fatal Exception: java.lang.NullPointerException

android.content.ComponentName. (ComponentName.java)
android.content.Intent. (Intent.java)
com.vk.sdk.VKServiceActivity.createIntent (VKServiceActivity.java:117)
com.vk.sdk.VKServiceActivity.startLoginActivity (VKServiceActivity.java:94)
com.vk.sdk.VKSdk.login (VKSdk.java:163)
com.wachanga.android.framework.social.networks.VkSocialNetwork.requestAccessToken (VkSocialNetwork.java:67)

**Comment by dkostryukov** [comment]
Необходимо инициализировать SDK именно в Application, как описано в документации, причины данного бага выяснены здесь #149

**Comment by coralinejones1985** [comment]
почему тогда это и #149 не происходят каждый раз?

**Comment by coralinejones1985** [comment]
Вы не могли бы объяснить, как инициализация в активности может вызывать эти баги, к тому же периодически? Так как у большинства пользователей все срабатывает нормально.
