### ISSUE TITLE
Инициализация

### ISSUE THREAD

**Issue by kavolorn** [VKCOM/vk-android-sdk#151]
Нельзя ли поддерживать две возможности указывать ID приложения (в ресурсах и в рантайме)? Очень неудобно использовать ресурсы для этих целей. В моем нативном расширении для Adobe AIR получается так, что я вообще не могу производить инициализацию с 1.5 версией сдк. Может вместо ресурсов следует вытащить мета параметр в манифест?

**Comment by dkostryukov** [comment]
Если вы можете указать ID приложения в манифесте, почему не можете указать в ресурсах и чем этот подход лучше?

**Comment by kavolorn** [comment]
Для ясности разделим пользователя и автора расширения для AIR. Я как автор могу модифицировать что хочу, могу ID зашить в ресурсы перед сборкой и все сработает. Но пользователю доставляется уже собранное стандартное расширение, в котором он ничего не должен внутри изменять.

Пользователю AIR предоставляет возможность редактировать только манифест непосредственно при создании приложения, но не ресурсы. Любые ресурсы должны зашиваться при сборке ANE. Пользователю нужна возможность не модифицируя сборку указывать свой ID.

Вот поэтому перевод ID в ресурсы для меня и других пользователей AIR очень неудобен.

**Comment by dnikolaev** [comment]
Поддержу @kavolorn Наиболее удобный способ указать ID приложения был бы через [meta-data](http://developer.android.com/guide/topics/manifest/meta-data-element.html) Учитывая специфику разработки Adobe AIR ANE, указание ID приложения в ресурсах действительно доставит много проблем.

**Comment by Klug76** [comment]
Указание ID приложения в ресурсах ставит крест на не-Java средствах разработки, т.к. доступ к ресурсам может быть ограничен. Поддерживаю вариант meta-data, например как в GoogleGames:
```
...
<application>
	<!-- You must change 00000000000 to your own game id -->
	<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ 00000000000" />
...
```
либо верните возможность задать ID в рантайме.

**Comment by dkostryukov** [comment]
А инициализация SDK в Application#onCreate проблем не вызывает?

**Comment by kavolorn** [comment]
Если речь идет о 1.3, то там все довольно гладко работает. Изменения в 1.5  я толком не разбирал еще, что-то изменилось?

**Comment by dkostryukov** [comment]
Теперь инициализация в Activity#onCreate не будет работать, только если инициировать в Application#onCreate. Если для приложений не Java нет проблем с доступом к Application и с его наследованием, то можно добавить ID при инииализации

**Comment by kavolorn** [comment]
Да, возможно это тоже проблематичная вещь. Это принципиально, вызывать инициализацию именно в Application#onCreate? 
```
vkAccessTokenTracker.startTracking();
VKSdk.initialize(this);
```
Нельзя ли эти две строки вызывать где-нибудь в другом месте, но передавать ссылку на Application?

**Comment by dkostryukov** [comment]
Принципиально

**Comment by kavolorn** [comment]
Тогда это еще более проблематичная вещь, чем ресурсы. Почему понадобилось такое ужесточение требований на инициализацию?

**Comment by dkostryukov** [comment]
Я так понимаю, у вас есть доступ к файлу манифеста и возможность создавать классы на java? Есть ли возможность Создать наследника Application java и переопределить его в манифесте?

**Comment by kavolorn** [comment]
Официальной возможности доступа к коду Application нет. И к коду основного Activity тоже. Как их создавать решает компилятор AIR. В расширении есть возможность получить доступ к контексту уже созданного приложения.

Теоретическая возможность переопределения класса приложения есть, как описано тут:

http://blogs.adobe.com/digitalmedia/2011/05/extending-air-for-android/

Здесь показано, как подменить Application. Но на практике это ненадежный хак и не документированное поведение, которое с легкостью может сломаться в любой версии AIR. Возможно уже сейчас оно не работает, потому что статья очень старая и в рантайме поменялось  слишком много всего. Даже пробовать нет смысла, потому что невозможно поддерживать в случае проблем.

**Comment by dkostryukov** [comment]
в новой версии, 1.5.10 доступен метод VKSdk.customInitialize(Context ctx, int appId, String apiVer),
вы должны вызвать его перед обращением к SDK

**Comment by kavolorn** [comment]
Супер! Обязательно используем.
