### ISSUE TITLE
VK SDK использует классы отсутсвующие в Android 6 SDK

### ISSUE THREAD

**Issue by nkuznetsow** [VKCOM/vk-android-sdk#154]
Например, класс com.vk.sdk.api.httpClient.VKMultipartEntity наследован от класса AbstractHttpEntity которого нет в Android SDK 6. http package http://developer.android.com/sdk/api_diff/23/changes.html

**Comment by illarionov** [comment]
C `compileSdkVersion 23` proguard мозг выносил, решение:

    -dontwarn org.apache.http.**
    -keep class com.vk.** { *;}

**Comment by nkuznetsow** [comment]
Вам нужно перестать использовать классы из пакета org.apache.http вообще, а не просто отключить сообщения об ошибках, иначе, на Android 6 с targetSdkVersion=23 библиотека не будет работать.

**Comment by illarionov** [comment]
`org.apache.http` не удалили, а спрятали из публичного SDK, работать всё будет. Сейчас, по крайней мере на предварительных образах, работает. Но вообще да, ждем от авторов выпиливания.

**Comment by nkuznetsow** [comment]
По этой ссылке можно посмотреть все изменения в 23 SDK http://developer.android.com/sdk/api_diff/23/changes.html  пакеты org.apache.http удалены почти все. 

В этом можно убедиться, посмотрев android.jar:

22 SDK:
![Image](http://dn.imagy.me/201508/19/d71f63fd54458878b89c42e389a2f4c8.png)

23 SDK:
![Image](http://dn.imagy.me/201508/19/54c7863966bb4f67aaecfd85c7c90d4c.png)

Сейчас, если вы установите у Вашего приложения targetSdkVersion=23, то оно не будет работать на Android 6, по крайней мере так его часть, которая использует классы из VK SDK, которые ссылаются на удалённые из фреймворка классы.

**Comment by dkostryukov** [comment]
Данная проблема поправлена в версии 1.5.6
В данный момент она недоступна через gradle зависимость, ее обновление займет определенное время, пока она не обновлена, можно подключить SDK сабмодулем
