### ISSUE TITLE
BatchRequest

### ISSUE THREAD

**Issue by Rupini** [VKCOM/vk-android-sdk#155]
На сколько я понимаю BatchRequest нужен для того чтобы выполнять в одном запросе множество запросов и тем самым решать проблему с ограничением по кол-во запросов в секунду. Я хочу для всех друзей узнать IsUserApp, получается в районе 13 запросов. Однако мне выводится ошибка "code 6 Too many request per second". Подскажите пожалуйста что не так или посоветуйте другой способ определения для всех пользователей IsUserApp.

**Comment by dkostryukov** [comment]
Вы можете запросить приложение с флагом возврата друзей и на клиенте уже отфильтровать, будет один запрос, вместо 13-ти

**Comment by Rupini** [comment]
Да, я так и делаю, я запрашиваю всех друзей одним запросом, но у VKApiUserFull нет поля isUserApp, поэтому его приходится запрашивать отдельно через VKApiUsers

**Comment by dkostryukov** [comment]
https://vk.com/dev/apps.get return_friends=1 тогда вернется приложение и список друзей в ней, сопоставив uid вы сможете понять, кто установил приложение

**Comment by Rupini** [comment]
а в данном sdk, есть вызов отвечающий за apps.get или его нужно делать как-то на прямую?

**Comment by dkostryukov** [comment]
вы можете указать метод в VKRequest и передать нужные параметры

**Comment by Rupini** [comment]
типо VKRequest("apps.get","return_friends")?

**Comment by dkostryukov** [comment]
типо new VKRequest("apps.get", VKParameters.from("return_friends", 1)).executeWithListener(...);

**Comment by Rupini** [comment]
отлично, спасибо, все работает

**Comment by Rupini** [comment]
только проще использовать метод 
new VKRequest("apps.getFriendsList", VKParameters.from("type","request"));
