### ISSUE TITLE
Does not read client_id from the integer value

### ISSUE THREAD

**Issue by MrXlebNick** [VKCOM/vk-android-sdk#158]
I have put the client ID into the integer value but it SDK sends it as if my client ID were 0.

**Comment by dkostryukov** [comment]
Show us code please

**Comment by MrXlebNick** [comment]
public void login(View v){


		int resId = getResources().getIdentifier("com_vk_sdk_AppId", "integer", getPackageName());
		final String[] scope = {VKScopes.GROUPS, VKScopes.WALL};

		VKSdk.login(LoginActivity.this, scope);
	}

	@Override
	protected void onActivityResult(int requestCode, int resultCode, Intent data) {
		if (!VKSdk.onActivityResult(requestCode, resultCode, data, new VKCallback<VKAccessToken>() {
			@Override
			public void onResult(VKAccessToken res) {
			}
			@Override
			public void onError(VKError error) {
			}
		})) {
			super.onActivityResult(requestCode, resultCode, data);
		}
	}

**Comment by dkostryukov** [comment]
and res file

**Comment by MrXlebNick** [comment]
\<?xml version="1.0" encoding="utf-8"?>
\<resources>
    \<integer name="com_vk_sdk_AppId" type="integer">7-digit access code\</integer>
\</resources>

**Comment by dkostryukov** [comment]
and error log

**Comment by MrXlebNick** [comment]
no error log, but i have this
![device-2015-09-14-144205](https://cloud.githubusercontent.com/assets/10089784/9848965/d8c52a5c-5aee-11e5-91fd-576125abf40d.png)

**Comment by dkostryukov** [comment]
Did you add VKSdk.initialize(this) to Application#onCreate?

**Comment by MrXlebNick** [comment]
Yes, I did. Also, I sniffed the traffic, the key isn't passed as argument to server

**Comment by dkostryukov** [comment]
Are you sure that the VKSdk.initialize(this) was called? Can you set breakpoint and check it?

**Comment by MrXlebNick** [comment]
Yes, I can. It's called for sure

**Comment by MrXlebNick** [comment]
Thank you, I found a mistake. It wasn't because of SDK, so I close this issue. Thank you for being ready to help.
