### ISSUE TITLE
SDK использует старую версию апи

### ISSUE THREAD

**Issue by bughater** [VKCOM/vk-android-sdk#160]
Когда выполняю запросы к методам апи через сдк, получаю ответ в старом формате. При попытке передачи параметра "v" со значением актуальной версии апи ничего не меняется. Можно ли как-нибудь указать сдк какую версию апи использовать? Спасибо!

**Comment by dkostryukov** [comment]
Можно указать версию строкой com_vk_sdk_ApiVersion, аналогично "com_vk_sdk_AppId
