### ISSUE TITLE
registerDevice

### ISSUE THREAD

**Issue by chingiz98** [VKCOM/vk-android-sdk#161]
Здравствуйте! При попытке вызова метода "registerDevice" не получаю никакого ответа, в параметры передаю GCM token, device_I'd и settings. Если передавать только token и device_id – получаю в ответ response:1. Хочу реализовать прием push уведомлений в android приложении. Будьте добры, подскажите, что делать.

**Comment by Dreddik** [comment]
Ещё актуально?
