### ISSUE TITLE
Получение информации текущего пользователя

### ISSUE THREAD

**Issue by IlyaEremin** [VKCOM/vk-android-sdk#162]
Есть ли способ получить инфу по текущему юзеру после авторизации?
Я полагаю, что users().get(useId) не будет отдавать информацию, если профиль закрытый. 
Есть запрос https://vk.com/dev/account.getProfileInfo, но в VkApi он не реализован.
Планируется ли сделать в `VkApi` еще один пункт `account` ?

**Comment by Dreddik** [comment]
>Я полагаю, что users().get(useId) не будет отдавать информацию, если профиль закрытый. 

Будет

**Comment by Dreddik** [comment]
>Планируется ли сделать в VkApi еще один пункт account ?

Вы можете реализовать его самостоятельно, вне зависимости от VKApi

**Comment by IlyaEremin** [comment]
Если будет, то нафиг надо) Спасибо за супер оперативность.
