### ISSUE TITLE
Сортировка списка друзей отсутствует

### ISSUE THREAD

**Issue by soulstyless** [VKCOM/vk-android-sdk#163]
У VkApiConst нет поля ORDER, пробовал так VKRequest request= VKApi.friends().get(VKParameters.from(VKApiConst.FIELDS,"id,first_name, last_name,bdate",VKApiConst.SORT,"hints")); но не работает.

**Comment by Dreddik** [comment]
VKParameters.from(VKApiConst.FIELDS,"id,first_name, last_name,bdate","order","hints")
