### ISSUE TITLE
Креш приложения пр старте

### ISSUE THREAD

**Issue by JaroslavL** [VKCOM/vk-android-sdk#166]
Здравствуйте! 

Ситуация следующая. Разрабатываю плагин для Unity3D под андроид с вашим SDK. При запуске приложение вылетает. Делаю все так же как у вас в документации, но как только использую хоть что-то из вашего SDK приложение не запускается. Сам по себе плагин работает. Пробовал подключать ваш sdk по разному и манифест переписывал и все что угодно результат прежний.

Вот пример кода моего MainActivity

package com.brosuniverse.blackstar.vkandroidplugin;

import android.content.Intent;
import android.os.Bundle;

import com.unity3d.player.UnityPlayerActivity;
import com.vk.sdk.VKSdk;

public class MainActivity extends UnityPlayerActivity {

    private String[] code;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //VKSdk.initialize(getApplicationContext());
        VKSdk.initialize(this);
    }

    @Override
    public void onResume() {
        super.onResume();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
    }

    public String ReturnString() {

        return "lol";
    }
}

Вот settings.gradle

include ':app', ':lib', ':vksdk_library'

Вот build.gradle

apply plugin: 'com.android.library'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        //applicationId "com.brosuniverse.blackstar.vkandroidplugin"
        minSdkVersion 19
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile files('libs/classes.jar')
    compile project(':vksdk_library')
}

//task to delete the old jar
task deleteOldJar(type: Delete) {
    delete 'release/AndroidPlugin.jar'
}

//task to export contents as jar
task exportJar(type: Copy) {
    from('build/intermediates/bundles/debug/')
    into('release/')
    include('classes.jar')
    ///Rename the jar
    rename('classes.jar', 'AndroidPlugin.jar')
}

Подскажите пожалуйста в чем собственно дело? Спасибо!

**Comment by Dreddik** [comment]
Стектрейс можно увидеть?

**Comment by JaroslavL** [comment]
Есть вот такое

10-01 18:36:33.912: I/ActivityManager(492): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.brosuniverse.blackstar.vkandroidplugin/.MainActivity (has extras)} from pid 888
10-01 18:36:33.984: I/BufferQueue(136): [Starting com.brosuniverse.blackstar.vkandroidplugin](this:0x41e63d60,api:0) setConsumerName: Starting com.brosuniverse.blackstar.vkandroidplugin
10-01 18:36:33.991: I/ActivityManager(492): Start proc com.brosuniverse.blackstar.vkandroidplugin for activity com.brosuniverse.blackstar.vkandroidplugin/.MainActivity: pid=5882 uid=10117 gids={50117, 3003, 1028}
10-01 18:36:33.991: D/ACTSpeed(492): AMS: logAppLaunchTime : Start proc com.brosuniverse.blackstar.vkandroidplugin for activity com.brosuniverse.blackstar.vkandroidplugin/.MainActivity: pid=5882 uid=10117 gids={50117, 3003, 1028}
10-01 18:36:33.996: I/BufferQueue(136): [Starting com.brosuniverse.blackstar.vkandroidplugin](this:0x41e63d60,api:0) setDefaultBufferSize: w=720, h=1280
10-01 18:36:34.004: V/ActivityManager(492): com.brosuniverse.blackstar.vkandroidplugin/.MainActivity: task=TaskRecord{424c4668 #13 A com.brosuniverse.blackstar.vkandroidplugin U 0}
10-01 18:36:34.018: V/ActivityManager(492): Binding process pid 5882 to record ProcessRecord{41e86cc8 5882:com.brosuniverse.blackstar.vkandroidplugin/u0a10117}
10-01 18:36:34.019: V/ActivityManager(492): New app record ProcessRecord{41e86cc8 5882:com.brosuniverse.blackstar.vkandroidplugin/u0a10117} thread=android.os.BinderProxy@421a2d18 pid=5882
10-01 18:36:34.021: I/BufferQueue(136): [Starting com.brosuniverse.blackstar.vkandroidplugin](this:0x41e63d60,api:0) connect: api=2
10-01 18:36:34.021: I/BufferQueue(136): [Starting com.brosuniverse.blackstar.vkandroidplugin](this:0x41e63d60,api:2) setSynchronousMode: enabled=1
10-01 18:36:34.022: I/BufferQueue(136): [Starting com.brosuniverse.blackstar.vkandroidplugin](this:0x41e63d60,api:2) new GraphicBuffer needed
10-01 18:36:34.024: V/ActivityManager(492): ACT-Launching: ActivityRecord{42053c00 u0 com.brosuniverse.blackstar.vkandroidplugin/.MainActivity}
10-01 18:36:34.030: I/ActivityManager(492): boardcastResumedActivityInfo: start ...packageName:com.brosuniverse.blackstar.vkandroidplugin
10-01 18:36:34.037: D/LenovoBatteryManagerService(492): isPackageChange, packageName:com.brosuniverse.blackstar.vkandroidplugin
10-01 18:36:34.037: V/LenovoBatteryManagerService(492): package changed: current package:com.brosuniverse.blackstar.vkandroidplugin
10-01 18:36:34.060: I/SurfaceTexture(136): [Starting com.brosuniverse.blackstar.vkandroidplugin](this:0x41e5c620,api:2) [void* android::SurfaceTexture::createImage(EGLDisplay, const android::sp<android::GraphicBuffer>&)]
10-01 18:36:34.060: D/dalvikvm(5882): open_cached_dex_file : /mnt/asec/com.brosuniverse.blackstar.vkandroidplugin-2/pkg.apk /data/dalvik-cache/mnt@asec@com.brosuniverse.blackstar.vkandroidplugin-2@pkg.apk@classes.dex
10-01 18:36:34.064: I/dalvikvm(5882): Could not find method com.vk.sdk.VKSdk.initialize, referenced from method com.brosuniverse.blackstar.vkandroidplugin.MainActivity.onCreate
10-01 18:36:34.069: D/dalvikvm(5882): Trying to load lib /mnt/asec/com.brosuniverse.blackstar.vkandroidplugin-2/lib/libmain.so 0x416e1cc0
10-01 18:36:34.070: D/dalvikvm(5882): Added shared lib /mnt/asec/com.brosuniverse.blackstar.vkandroidplugin-2/lib/libmain.so 0x416e1cc0
10-01 18:36:34.115: E/AndroidRuntime(5882): 	at com.brosuniverse.blackstar.vkandroidplugin.MainActivity.onCreate(MainActivity.java:17)
10-01 18:36:34.120: W/ActivityManager(492):   Force finishing activity com.brosuniverse.blackstar.vkandroidplugin/.MainActivity
10-01 18:36:34.262: D/AES(492):     process : com.brosuniverse.blackstar.vkandroidplugin
10-01 18:36:34.262: D/AES(492):      module : com.brosuniverse.blackstar.vkandroidplugin v1 (1.0)
10-01 18:36:34.262: D/AEE/LIBAEE(492): shell: raise_exp(2, 5882, -1361051648, com.brosuniverse.blackstar.vkandroidplugin, 0x0x6112b008, 0x0x0)

Тут видно что он не может найти com.vk.sdk.VKSdk.initialize.  И это странно ведь сдк подключен

На выходе если что я получаю .jar, который и помещаю в Unity

**Comment by JaroslavL** [comment]
Есть какие-нибудь предположения? Если что ошибка вот такая I/dalvikvm(5882): Could not find method com.vk.sdk.VKSdk.initialize

Я так понимаю это связано с настройками. Подскажите пожалуйста

**Comment by TheFifthMoon** [comment]
Попробуй по соседству с твоей Activity (в той же папке) создать класс Application:

public class Application extends android.app.Application {
    @Override
    public void onCreate() {
        super.onCreate();
        VKSdk.initialize(Application.this);
    }
}

Дело в том, что в описании api сказано инициилизировать sdk в классе Application приложения. Я сам не сразу это заметил. Как поменял - сразу заработало. Отпишитесь, если заработает.

**Comment by dkostryukov** [comment]
появился метод VKSdk#customInitialize
