### ISSUE TITLE
VKSdk.requestUserState callback never called

### ISSUE THREAD

**Issue by asimaruk** [VKCOM/vk-android-sdk#168]
I got the following code

'''
if (!mAppConfig.isCheckedInstallFromVk()) {
            VKSdk.requestUserState(this, new VKPaymentsCallback() {
                @Override
                public void onUserState(final boolean userIsVk) {
                    new Handler(Looper.getMainLooper()).post(new Runnable() {
                        @Override
                        public void run() {
                            mAppConfig.setIsVkInstall(userIsVk);
                            mAppConfig.setCheckedInstallFromVK(true);
                            LocalBroadcastManager.getInstance(App.this).sendBroadcast(new Intent(VkPlatform.ACTION_CHECK_VK_INSTALL));
                        }
                    });
                }
            });
        }
'''

And onUserState() never called.

**Comment by bigblackdot** [comment]
Подтверждаю. В тестовом приложении VKSDK данный запрос проходит нормально. В разрабатываемом приложении ответа на запрос не приходит. Какое конкретно различие между ними влияет на работоспособность запроса - локализовать не удается.

**Comment by bigblackdot** [comment]
В соответствии со следующим куском кода, в случае возврата сервером значения CHECK_USER_INSTALL_ANSWER_UNKNOWN (-1), callback не вызывается:
                case CHECK_USER_INSTALL_ANSWER_VK:
                case CHECK_USER_INSTALL_ANSWER_VK_FORCE:
                    callback.onUserState(true);
                    break;
                case CHECK_USER_INSTALL_ANSWER_NOT_VK:
                    callback.onUserState(false);
                    break;
                default:
                    mVkPaymentsCallbacks.add(callback);

@Dreddik , вы бы прокомментировали как-нибудь ситуацию? Очень много времени уходит на дебаг таких вещей. По какой причине сервер может возвращаять такой ответ? package/main activity/appID/фингерпринты в норме. Может быть такой ответ возвращается любому не прошедшему модерацию приложению?

**Comment by dkostryukov** [comment]
@asimaruk @bigblackdot
this method available for https://vk.com/dev/mobile_games only

**Comment by bigblackdot** [comment]
@dkostryukov Вы можете несколько более развернутое пояснение дать? Из сообщений, как моих, так и @asimaruk должно быть очевидно, что мы работаем с VKSDK-android. Этот факт еще не делает приложение "mobile_games"? Что нужно сделать, чтобы оно считалось таковым? ПРи использовании vksdk-android приложение очевидно становится мобильным. Значит, проблема в дифференциации mobile apps - mobile games? В существующей документации каталога мобильных игр я не вижу конкретных шагов как обозначить платформе, что приложение является именно игрой.

**Comment by bigblackdot** [comment]
Ответ сервера сейчас выглядит следующим образом:

{"error":{"error_code":100,"error_msg":"One of the parameters specified was missing or invalid: Platform android is not allowed for this application.","request_params":[{"key":"oauth","value":"1"},{"key":"method","value":"apps.checkUserInstall"},{"key":"platform","value":"android"},{"key":"app_id","value":"4310044"},{"key":"v","value":"5.21"},{"key":"lang","value":"ru"},{"key":"https","value":"1"}]}}

**Comment by dkostryukov** [comment]
@bigblackdot mobile_games это подмножество мобильных приложений, использующих наше SDK. По ссылке, которую я прикрепил выше (https://vk.com/dev/mobile_games) описан процесс подготовки приложения и процедура прохождения модерации.
P.S.: на странице https://vk.com/dev/mobile_games если кликнуть по заголовку, например "Размещение в каталоге" откроется подробная страница, где описано, что делать.

**Comment by dkostryukov** [comment]
@bigblackdot а для чего конкретно в приложении Вы используете данный запрос, если не для каталога игр?

**Comment by bigblackdot** [comment]
@dkostryukov именно под каталог мобильных игр мы и планируем адаптировать свои ios/android игры. В каталоге наши игры не присутствуют. Модерацию не проходили. Но перед прохождением модерации и последующим попаданием в каталог ведь нужно взаимодействие с данными методами VK SDK настроить и отладить, что, кстати, соответствует порядку действий в приведенной вами ссылке: сначала имплементация SDK(в развернутом описании данного шага есть отсылка к данному методу: "Отслеживание источника установки игры доступно через специальный метод SDK."), следующий шаг - прохождение модерации. Как это можно сделать? Прохождение модерации нужно осуществлять без экрана авторизации и добавлять его впоследствии?

**Comment by Dreddik** [comment]
Больше не актуально
