### ISSUE TITLE
android.support.v4.app.Fragment

### ISSUE THREAD

**Issue by Tieru** [VKCOM/vk-android-sdk#170]
Судари, а не соизволите ли поддержать старые фрагменты из саппорт либ? (: 
Проект написан уже, переписывать на нормальные фрагменты не хотелось бы, боролся с крашами, заодно и вк обновил, а метод _VKSdk.login(android.support.v4.app.Fragment fragment)_ отстутствует. 
Я, конечно, через активити прокину, но это как-то не очень...

**Comment by Dreddik** [comment]
В таком случае лучше через getActivity()  делать

**Comment by Tieru** [comment]
Даа, так и поступил

**Comment by 3mph4515** [comment]
В таком случае лучше через getActivity() делать

>>>
Какие на это причины?

**Comment by nbarishok** [comment]
Минус делать через getActivity() в том, что тогда onActivityResult(...) приходит в Activity, а иногда есть желание, чтобы это происходило во фрагменте. А значит его вручную приходится пробрасывать во фрагмент для дальнейшей обработки.

**Comment by cab404** [comment]
я бы всё же переоткрыл issue. действительно не хватает.

**Comment by Skullper** [comment]
Офигел просто когда увидел что нету android.support.v4.app.Fragment в 2016

**Comment by Tieru** [comment]
Если посмотреть внимательно, то его и в 2015 уже не было)

**Comment by razer89** [comment]
Активити для авторизации можно запустить вручную, из саппорт фрагмента:

Intent intent = new Intent(getActivity(), VKServiceActivity.class);
            intent.putExtra("arg1", "Authorization");
            ArrayList<String> scopes = new ArrayList<>();
            scopes.add(VKScope.OFFLINE);
            intent.putStringArrayListExtra("arg2", scopes);
            intent.putExtra("arg4", VKSdk.isCustomInitialize());
            startActivityForResult(intent, VKServiceActivity.VKServiceType.Authorization.getOuterCode());

Результат отлавливать в onActivityResult точно так же, как описано в документации.
Hope it helps =)

**Comment by Skullper** [comment]
Спасибо, но я уже разобрался и сделал почти также.
А это сохраню себе)
Благодарю!

2016-11-04 17:18 GMT+02:00 Sergey Vrublevskiy <notifications@github.com>:

**Comment by spbisya** [comment]
Почему закрыто issue? Проблема так и не устранена.

**Comment by Skullper** [comment]
Потому что её никто не будет устранять. Походу и так устраивает(

**Comment by akolodyazhnyy** [comment]
+, сделайте, пожалуйста, поддержку фрагментов из support

**Comment by arkty** [comment]
@RomanTruba  Добрый день, почему закрыли issue?

**Comment by RomanTruba** [comment]
@arkty автор закрыл, его и спрашивайте

**Comment by arkty** [comment]
@RomanTruba я столкнулся с такой же проблемой, можете пожалуйста переотрыть issue. Проблема не решена.

**Comment by RomanTruba** [comment]
@arkty вам проще использовать какую-нибудь актуальную библиотеку, на эту забили, по всей видимости.

**Comment by Tieru** [comment]
@arkty

Проблема решается другим способом. Отказались от v4 фрагментов, возможно, неспроста. Теме уже два года, поэтому рассчитывать уже не стоит

**Comment by kaitkulov** [comment]
Теперь точно  актуально;) android.app.Fragment deprecated!

**Comment by feivur** [comment]
Решите наконец эту тупую проблему, имейте совесть. Админ, переоткрой задачу, отговорки не принимаются.
