### ISSUE TITLE
Поддержка Adobe AIR 

### ISSUE THREAD

**Issue by AlexeyMeshkov** [VKCOM/vk-android-sdk#172]
VK SDK 1.6 требует, чтобы метод VKSdk.initialize выполнялся внутри обработчика Application#onCreate.
Но в случае с Adobe AIR это место нам недоступно. Вызвать инициализацию SDK мы можем только позднее. При этом в версии 1.5 такого требования не было и не очевидно откуда вообще оно взялось.

В результате получается, что использовать версию 1.6 VK SDK внутри Adobe AIR невозможно.

**Comment by NAO3133** [comment]
Я зову initialize на создании контекста

**Comment by AlexeyMeshkov** [comment]
В версии 1.5 это работало. В 1.6.1 внутри initialize есть явная проверка на наличие в стэке вызовов

```java
if (!hasInStack(Application.class, "onCreate")) {
  throw new RuntimeException("VKSdk.initialize(Context) must be call from Application#onCreate()");
}
```

**Comment by Dreddik** [comment]
https://github.com/VKCOM/vk-android-sdk/issues/151
