### ISSUE TITLE
Постоянный перезапуск активити

### ISSUE THREAD

**Issue by NAO3133** [VKCOM/vk-android-sdk#173]
Работаю над имплементацией VK SDK в AIR приложении.
Для инициализации использую customInitialize
Столкнулся с проблемой на одном устройстве (на остальных норм):
- позвать  VKSdk.login при установленном приложении ВК
- Откроется активити с выбором "регистрация", "авторизация"
- нажать кнопку BACK - в итоге активити перезапустится (произойдет onResume, onDestroy, onCreate родительского активити)
- выйти из активити получается только после 5-10 раз нажатия кнопки BACK
Аналогичная ситуация при нажатии кнопки "Разрешить" после авторизации юзера - активити совсем не хочет завершаться, и иногда выводится тост "Be sure to call this using startActivityForResult()"
При этом авторизация проходит успешно, но не срабатывает колбэк onActivityResult.

Почти сразу после вызова метод login в логах падает ошибка:

I/dalvikvm( 5578): Could not find method android.webkit.WebView.setWebContentsDebuggingEnabled, referenced from method com.vkontakte.android.VKApplication.onCreate
W/dalvikvm( 5578): VFY: unable to resolve static method 12852: Landroid/webkit/WebView;.setWebContentsDebuggingEnabled (Z)V
D/dalvikvm( 5578): VFY: replacing opcode 0x71 at 0x00e9
D/ACRA    ( 5578): ACRA is enabled for com.vkontakte.android, intializing...
D/ACRA    ( 5578): Looking for error files in /data/data/com.vkontakte.android/files
D/ACRA    ( 5578): Looking for error files in /data/data/com.vkontakte.android/files
I/[myTracker]( 5578): Tracker initialized. Version: 1.1.4. ID: 39905392329609327611
D/dalvikvm( 5578): GC_CONCURRENT freed 307K, 14% free 10230K/11847K, paused 3ms+14ms, total 58ms
W/SerializableHttpCookie( 5578): java.lang.NoSuchFieldException: httpOnly
W/SerializableHttpCookie( 5578): 	at java.lang.Class.getDeclaredField(Class.java:631)
W/SerializableHttpCookie( 5578): 	at com.vkontakte.android.api.SerializableHttpCookie.initFieldHttpOnly(SerializableHttpCookie.java:92)
W/SerializableHttpCookie( 5578): 	at com.vkontakte.android.api.SerializableHttpCookie.setHttpOnly(SerializableHttpCookie.java:82)
W/SerializableHttpCookie( 5578): 	at com.vkontakte.android.api.SerializableHttpCookie.readObject(SerializableHttpCookie.java:125)
W/SerializableHttpCookie( 5578): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/SerializableHttpCookie( 5578): 	at java.lang.reflect.Method.invoke(Method.java:511)
W/SerializableHttpCookie( 5578): 	at java.io.ObjectInputStream.readObjectForClass(ObjectInputStream.java:1354)
W/SerializableHttpCookie( 5578): 	at java.io.ObjectInputStream.readHierarchy(ObjectInputStream.java:1266)
W/SerializableHttpCookie( 5578): 	at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1855)
W/SerializableHttpCookie( 5578): 	at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:787)
W/SerializableHttpCookie( 5578): 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:2003)
W/SerializableHttpCookie( 5578): 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1960)
W/SerializableHttpCookie( 5578): 	at com.vkontakte.android.api.SerializableHttpCookie.decode(SerializableHttpCookie.java:56)
W/SerializableHttpCookie( 5578): 	at com.vkontakte.android.api.PersistentCookieStore.loadAllFromPersistence(PersistentCookieStore.java:53)
W/SerializableHttpCookie( 5578): 	at com.vkontakte.android.api.PersistentCookieStore.<init>(PersistentCookieStore.java:39)
W/SerializableHttpCookie( 5578): 	at com.vkontakte.android.Global.<clinit>(Global.java:82)
W/SerializableHttpCookie( 5578): 	at com.vkontakte.android.VKApplication.onCreate(VKApplication.java:128)
W/SerializableHttpCookie( 5578): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
W/SerializableHttpCookie( 5578): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4251)
W/SerializableHttpCookie( 5578): 	at android.app.ActivityThread.access$1400(ActivityThread.java:140)
W/SerializableHttpCookie( 5578): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297)
W/SerializableHttpCookie( 5578): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/SerializableHttpCookie( 5578): 	at android.os.Looper.loop(Looper.java:137)
W/SerializableHttpCookie( 5578): 	at android.app.ActivityThread.main(ActivityThread.java:4921)
W/SerializableHttpCookie( 5578): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/SerializableHttpCookie( 5578): 	at java.lang.reflect.Method.invoke(Method.java:511)
W/SerializableHttpCookie( 5578): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
W/SerializableHttpCookie( 5578): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
W/SerializableHttpCookie( 5578): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by AlexeyMeshkov** [comment]
А в чём была причина? У нас похожая проблема и мы пока не нашли решения?

**Comment by fincode** [comment]
Такая же проблема
