### ISSUE TITLE
Смена ориентации активити

### ISSUE THREAD

**Issue by NAO3133** [VKCOM/vk-android-sdk#174]
Моё приложение (AIR) имеет горизонтальную ориентацию. На некоторых девайсах VKServiceActivity разворачивается в вертикальной ориентации, и столкнулся с тем, что на таких девайсах VKServiceActivity после завершения - сразу создаётся вновь.

Если в манифесте прописать "android:configChanges":
activity android:name="com.vk.sdk.VKServiceActivity" android:label="ServiceActivity" android:configChanges="keyboardHidden|orientation|screenSize" android:theme="@style/VK.Transparent"
то вышеописанной проблемы не происходит. Можно ли оставить в манифесте это изменение, и не приведет ли оно к чему то плохому?

**Comment by dkostryukov** [comment]
Можно оставить. Не приведет.
