### ISSUE TITLE
Double login fragments opening when option **Do not keep activities** set

### ISSUE THREAD

**Issue by SKART1** [VKCOM/vk-android-sdk#175]
Android: 5.1.1,
Smartphone: LG Google Nexus 4
Library version: 1.6.1 (compile 'com.vk:androidsdk:1.6.1' in gradle)

How to reproduce:
1. Switch on **Do not keep activities** in development settings
2. Start default example app
3. Push `SIGN IN WITH VK` button
4. 2 fragments/activities will be added to back stack - if you press arrow back button in upper left conner you will not come back to  `SIGN IN WITH VK` button, but to the exactly same page (animation of fragment changing will apear)

**Comment by dkostryukov** [comment]
fixed in 1.6.2
