### ISSUE TITLE
NullPointerException при первом запуске

### ISSUE THREAD

**Issue by AndriyTheProgrammer** [VKCOM/vk-android-sdk#177]
При первом запуске приложение падает после строки
VKSdk.wakeUpSession(this, loginStateCallback);
При последующих запусках, все происходит без проблем
Stacktrace показал только классы с sdk
До этого вызывал только VKSdk.initialize(this); в Application
![scr](https://cloud.githubusercontent.com/assets/8404404/10970919/2031c7ce-83da-11e5-9886-f665d7782c46.png)

**Comment by petruchodd** [comment]
+1 В пятницу поставил сдк.  , указал только в application  VKSdk.initialize(this) и в активити VKSdk.login(activity,scope).
При вызове логина и вейкапа ошибка 
![nullpointer](https://cloud.githubusercontent.com/assets/10280929/11028808/6a2dd0a0-86ca-11e5-9b4f-eb274893ceb1.png)

**Comment by petruchodd** [comment]
Пока нашел для себя фикс  это использование старой версии. Там все работает.

**Comment by AndriyTheProgrammer** [comment]
petruchodd можно узнать какой именно?

**Comment by petruchodd** [comment]
AndriyTheProgrammer , хз ))  не нашел какая версия https://yadi.sk/d/MWAbLGxSkMf7f
