### ISSUE TITLE
Не приходят пуш-уведомления

### ISSUE THREAD

**Issue by ERussel** [VKCOM/vk-android-sdk#179]
Добрый день,

Реализовал Android мессенджер на API ВКонтакте. Возникла проблема с пуш-уведомлениями о новых сообщениях. Тестирую приложение установленное на 2 устройства. На одном отправляю сообщения на другом отображаются уведомления, но через некоторое количество сообщений пуш-уведомления перестают приходить.

Существуют ли какие-либо ограничения API ВКонтакте на пуш-уведомления? Может есть какие-либо мысли с чем может быть связана проблема?

**Comment by Dreddik** [comment]
Ограничений нет, проблема может быть связана с обработкой, с устройством, с пушилкой на серверах ВК.
Проблема ещё актуальна?
