### ISSUE TITLE
Как использовать вебвью для регистрации даже если приложение вк установлено?

### ISSUE THREAD

**Issue by frakc** [VKCOM/vk-android-sdk#181]
Если не ошибаюсь до версии 1.5 можно было всегда использовать  вебформу в обход регистрации через установленное приложение вк. Сохранилась ли такая функция?

**Comment by dkostryukov** [comment]
В случае, если не установлено офф приложение, покажется WebView

**Comment by frakc** [comment]
@dkostryukov то что оно покажется, если приложение не установленно, то и так понятно. Я хочу, что бы использовалась вебвью даже если приложение установленно ( из-за бага https://github.com/VKCOM/vk-android-sdk/issues/178)

**Comment by Dreddik** [comment]
@frakc мы не хотим, чтобы это можно было форсировать. Баг скорее всего связан с неправильной настройкой

**Comment by frakc** [comment]
@Dreddik  если бы ли бы неправильно настроены ключи или параметры, то регистрация через вебвью не работала

**Comment by Dreddik** [comment]
@frakc если вы неправильно настроили отпечатки сертификатов, то авторизация через оф. приложение может не работать

**Comment by frakc** [comment]
@Dreddik откатился на версию 1.3.8 Авторизация работает и через вебвью и через приложение. Сертификаты теже
