### ISSUE TITLE
VkShareDialog does not work with native FragmentManager  

### ISSUE THREAD

**Issue by akulyakhtin** [VKCOM/vk-android-sdk#182]
VkShareDialog extends android.app.support.v4.DialogFragment and requires the calling activity to pass getSupportFragmentManager()  

Therefore it is not possible to use it in an activity with native fragments support (such as plain Activity in versions >=14). We can not pass getFragmentManager() to show the VkShare dialog

**Comment by Dreddik** [comment]
See VKShareDialogBuilder
