### ISSUE TITLE
Клавиатура в WebView

### ISSUE THREAD

**Issue by PavlikPetr** [VKCOM/vk-android-sdk#184]
При авторизации в VK через наше приложение, использующее VK Android SDK, не вызывается клавиатура после получения фокуса элементом ввода текста. Авторизация выполняется на устройстве не имеющем мобильный клиент VK (экран авторизации в WebView), устройство Meizu M1 Note android 4.4.4 (на других тестовых устройствах, что находятся в распоряжении отдела тестирования, данный баг не воспроизвелся), версия SDK = 4.5.0.

**Comment by FacelessTheOne** [comment]
Не буду ручаться, но скорее всего дело в том, что для отображения WebView используется AlertDialog - для него это известный баг.  В вконтактовской SDK эту проблему обошли одним хаком для WebView, который, видимо, не работает на Meizu, а ещё крешит приложение на старых HTC. В issue #180 я уже сообщал об этой проблеме. В пулл реквесте #186 есть решение, предложенное в комменте. Можете попробовать использовать его же и посмотреть, будет ли оно работать у вас. Гарантировать 100% работоспособность я не могу, но на тех аппаратах, что есть в распоряжении у нас (несколько популярных самсунгов, нексусы, несколько HTC), всё работает.
