### ISSUE TITLE
sdk_fingerprint is incorrect при установленном приложении вк

### ISSUE THREAD

**Issue by aperfilyev** [VKCOM/vk-android-sdk#187]
При попытке логина с установленным приложением получаю сабж. Через WebView все ок.

**Comment by aperfilyev** [comment]
Добавил другой, сгенерированный с помощью VKUtil.getCertificateFingerprint(this, this.getPackageName()); и все заработало )

**Comment by koderbober** [comment]
такая же проблема, только у меня с помощью VKUtil.getCertificateFingerprint(this, this.getPackageName()); возвращается такой же fingerprint, что и прописан в настройках в вк, поэтому не очень понимаю, как эту проблему решать. и да, эта проблема только если скачивать приложение через гугл плей, если установить просто релизный подписанный апк из студии, то все ок.

**Comment by isudakoff** [comment]
@koderbober Ещё не нашли решения? Такое же получаем. Точное описание нашей проблемы

**Comment by koderbober** [comment]
@isudakoff Нашел. Оказывается, в проде юзается два фингерпринта, один, когда на девайсе используется приложение вк, другой когда юзается вебвью. Как второй фингерпринт отловил, уже не помню, там вроде тоже не все так просто было, но смысл примерно такой. При этом странно, что в дебаге хватает одного фингерпринта и в релизе без гугл плея тоже хватает одного, хотя могу уже не помнить точно, как оно было.

**Comment by solareye** [comment]
@koderbober @isudakoff вот этот чувак помог:
[https://ru.stackoverflow.com/questions/594176/%D0%92%D0%9A-api-sdk-android-sdk-fingerprint-is-incorrect/723595#723595](url)

Брать надо оба SHA1 из консоли
