### ISSUE TITLE
Чат Вк

### ISSUE THREAD

**Issue by Avenger13** [VKCOM/vk-android-sdk#188]
Привет. Кто хочет поделиться своими работами с апи вк? Я хочу написать  клиент чисто для чата если у кого есть наработки а этом направлении то хотел бы задать пару вопросов.

**Comment by aperfilyev** [comment]
привет, я как раз пытаюсь начать )

**Comment by Avenger13** [comment]
Начать не сложно. С запросами можно за пару дней разобраться. Сложнее потом бывает, когда пытаешься написать более менее стоящий апп. Некоторые запросы приходится самому добавлять. У меня назрел вопрос как отделить чат от диалога? Они оба приходят в ответ на запрос диалогов. Кто сталкивался ответьте.
