### ISSUE TITLE
Android Studio 1.4.1 : Gradle dependency

### ISSUE THREAD

**Issue by boyfox** [VKCOM/vk-android-sdk#189]
Hi All VK SDK Top Developers. I using actively VK SDK mostly in my projects. Exists a problem. I Need use multidex application to if I want using VK SDK in my every projects. And when I use multidex gradle compile time will be greater 2 minut 35 seconds. This is very long time to developers. I tried to optimizing this process, but does not help : 

    android {
        compileSdkVersion 23
        buildToolsVersion "23.0.2"

        defaultConfig {
            ...
            multiDexEnabled true
        }

        dexOptions {
            preDexLibraries = false
            javaMaxHeapSize "2g"
        }
 
        packagingOptions {
            exclude 'META-INF/LICENSE.txt'
            exclude 'META-INF/NOTICE.txt'
       }
    }

    afterEvaluate {
        tasks.matching {
            it.name.startsWith('dex')
        }.each { dx ->
            if (dx.additionalParameters == null) {
                dx.additionalParameters = []
            }
            dx.additionalParameters += '--multi-dex'
            dx.additionalParameters += "--main-dex-list=$projectDir/multidex.keep".toString()
       }
    } 

Please, Create jar and put it is to jCenter repository to using VK SDK such as following way:

    dependencies {
        compile 'com.vk:androidsdk:1.6.2'
    }   

My Android Studio Project used jCenter repository.

**Comment by dkostryukov** [comment]
If you open https://github.com/VKCOM/vk-android-sdk you'll find
