### ISSUE TITLE
Push-уведомления

### ISSUE THREAD

**Issue by maxbpro** [VKCOM/vk-android-sdk#193]
Не пойму что не так с настройками пуш-уведомлений.
Тестировал отправку пуш-уведомлений со своего сервера - все в порядке. Залит pem в приложение на сайте правильный, без запроса пароля.

С помощью метода account.registerDevice зарегистрировал device. Вот мой запрос 

{
    "device_id" = "ABCD6085-E50C-46C1-9BA3-9B6BE67A255C";
    "device_year" = 2015;
    sandbox = 1;
    settings = "{\"msg\":\"on\",\"friend\":\"off\"}";
    "system_version" = ios;
    token = ca95c9d53b6007ff49ef8aa6f75ec85c17c081ce1bc15616ea635dddca21880f;
}

Получил в ответ response = 1

Уведомлений нет. 

Если запросить 

account.getPushSettings, передав device_id ABCD6085-E50C-46C1-9BA3-9B6BE67A255C, то ответ

response: {
disabled: 1,
subscribe: 'msg, chat, friend',
conversations: {
count: 0,
items: []
}
}

При этом, если специально отправить неверный device_id, то ответ аналогичный. Не пойму что не так...

**Comment by dkostryukov** [comment]
как минимум странно "system_version" = ios;

**Comment by romawizard** [comment]
аналогичная проблема. поеимаю что уже много времени прошло, но все же, удалось ли тебе ее решить?
