### ISSUE TITLE
sdk_package is incorrect

### ISSUE THREAD

**Issue by Sharombolla** [VKCOM/vk-android-sdk#194]
Help me please! Android application works when I test it on the emulator, but when I try to run it on a real device screen appears with the following error: {"error":"invalid_request","error_description":"sdk_package is incorrect"}

settings on page of the application is correct...

**Comment by ir4y** [comment]
+1

**Comment by caxerabc** [comment]
+1
I am trying to solve it for almost a week. With another library it works.
