### ISSUE TITLE
Как получить данные пользователя на русском языке?

### ISSUE THREAD

**Issue by bently93** [VKCOM/vk-android-sdk#196]
сейчас при запросе они приходят латиницей вроде как.

**Comment by aperfilyev** [comment]
от локали зависит

**Comment by bently93** [comment]
от локали чего? андроида? страницы?

**Comment by aperfilyev** [comment]
устройства

**Comment by bently93** [comment]
не зависит. пробовал.

**Comment by aperfilyev** [comment]
У меня все работает

**Comment by aperfilyev** [comment]
Вообще, сюда смотри http://vk.com/dev/api_requests
