### ISSUE TITLE
Постинг изображения на стену ссылкой

### ISSUE THREAD

**Issue by sava19** [VKCOM/vk-android-sdk#207]
Подключил VK SDK android и не нашел метода для загрузки изображений cсылкой на стену. В Facebook это выглядит примерно так 
ShareDialog shareDialog = new ShareDialog(this);
ShareLinkContent content = new ShareLinkContent.Builder()
.setContentUrl(Uri.parse("ссылка"))
.setContentTitle("I don't know, help me")
.setImageUrl(Uri.parse("ссылкаНаКартину.png"))
.setContentDescription("I don't know, help me")
.build();

shareDialog.show(content);

В VK SDK я нашел только такой способ, но тут берутся изображения из альбома
VKPhotoArray photos = new VKPhotoArray();
photos.add(new VKApiPhoto("photo26557941_393152601"));
new VKShareDialogBuilder()
.setText(getString(R.string.shareVkText))
.setUploadedPhotos(photos)
.setAttachmentLink(getString(R.string.shareVkTitleLink), getString(R.string.shareVkLink))
.setShareDialogListener(new VKShareDialog.VKShareDialogListener() {
@Override
public void onVkShareComplete(int postId) {
AndroidLauncher.checkRepostVK = true;
finish();
}

@Override
public void onVkShareCancel() {
finish();
}

@Override
public void onVkShareError(VKError error) {

}
})
.show(getFragmentManager(), "VK_SHARE_DIALOG");

**Comment by Dreddik** [comment]
А что ожидаете получить?

**Comment by IlyaEremin** [comment]
```
 VKUploadImage img = new VKUploadImage(bitmap, VKImageParameters.jpgImage(.9f));

new VKShareDialogBuilder().setAttachmentLink(link, title)
    .setText(title)
    .setAttachmentImages(new VKUploadImage[]{img})
    .show(fragmentManager, "randomTextHere");
```
Единственное неудобство, что изображение надо иметь в виде bitmap

**Comment by olegVovkZazmic** [comment]
Хочу запостить себе на стену сообщение, для этого использую
new VKShareDialogBuilder()
                .setText(text)
                .setShareDialogListener(new VKShareDialog.VKShareDialogListener() {
                    @Override
                    public void onVkShareComplete(int postId) {
                        Log.e("TAG", "post ID " + postId);
                    }

                    @Override
                    public void onVkShareCancel() {
                        Log.e("TAG", "cancel ");
                    }

                    @Override
                    public void onVkShareError(VKError error) {
                        Log.e("TAG", "error " + error);

                    }
                }).show(activity.getFragmentManager(),"TAG");

В ответе постоянно error -->VKError (API errorVKError (code: 15; ; Access denied: no access to call this method)) что я делаю не так?? Не пойму...

**Comment by Dreddik** [comment]
@olegVovkZazmic не запросили разрешение на wall
