### ISSUE TITLE
Hybrid flow or Google-like auth with JWT tokens

### ISSUE THREAD

**Issue by sochka** [VKCOM/vk-android-sdk#208]
I decided to make a separate issue after writing [this ](https://github.com/VKCOM/vk-android-sdk/issues/107#issuecomment-176414943)comment.

The issue is: how do you do server-side authentication using mobile flow in Android app? Sending the token from mobile to server is not quite secure - the server cannot trust the mobile. How do you accomplish that without using server side flow (and therefore launching a system browser or webview). Our backend should be able to authenticate only those VK users which authenticate using our app, not somebody elses. (that would be a security problem if a different app gained access to our api just by getting minimal scope access to VK.).

More detailed flow:
1. The app has authentication through VK (and possibly other auth providers + local username/password auth). 
2. The app has it's own backend. No other apps should be able to access that API.
3. Let's say VK auth is done through VK SDK. Which means that the token is received on the mobile side and sent to the server.
4. Now, image, there is a different app which uses VK authorization. They would be able to send the VK token to our server (the IP would be still correct, it's the user's phone).
5. On the backend, we cannot know who sent the token - our app or a different app. We authorize the user (in this "bad" app).
6. This second "alien" app has full access to our API just by asking the minimal scope access to VK itself.

In the case of Google, they have a more advanced system with signed JWT tokens and checking Android package name. In the case of VK, the only solution I see is doing server-flow with launching a browser (which would redirect the user back to _only_ our app, not others) which somewhat harms UX of the app. Did I get everything right, maybe there is a better solution?

**Comment by Dreddik** [comment]
Use secure.checkToken on your server side to check clients tokens

**Comment by olegsm** [comment]
Please, follow new SDK 2.0
