### ISSUE TITLE
Пошаговая документация.

### ISSUE THREAD

**Issue by ir4y** [VKCOM/vk-android-sdk#210]
Сделайте уже нормальную документацию по настройке. Опишите все детально по шагам.

Весь трекер завален мусорными тикетами связанными с тем что невозможно настроить работу приложения по предоставленной документации.
https://github.com/VKCOM/vk-android-sdk/issues/194
https://github.com/VKCOM/vk-android-sdk/issues/185
https://github.com/VKCOM/vk-android-sdk/issues/178

На стороне VK нужно настривать не только поле "Отпечаток сертификата для Android:"
но и все остальные поля и "Название пакета для Android:", "Main activity для Android:"

Первый заполняется значеннием поля package из AndroidManifest.xml
Второй - это полный путь до модуля с Main activity (например com.myapp.MainActivity)

Почему этих двух простых и обязательных шага не отображены в документации, для меня загадка.

**Comment by frakc** [comment]
@ir4y 
Первый заполняется значеннием поля package из AndroidManifest.xml
Второй - это полный путь до модуля с Main activity (например com.myapp.MainActivity)
я открывал баг 178 и тогда эти значения были заполнены (иначе не работало с мк сдк версии 1.3.8)
