### ISSUE TITLE
Перекрытие кастомного CookieManager

### ISSUE THREAD

**Issue by MultX** [VKCOM/vk-android-sdk#213]
Долго не мой найти проблему, почему перестают передаваться cookie после аутентификации через vk-android-sdk.

Результатом поиска стала строчка в файле VkHttpClient.java:

```
...
public static VKHttpResponse execute(VKHTTPRequest request) throws IOException {
--->   CookieHandler.setDefault(new CookieManager(null, CookiePolicy.ACCEPT_ALL));
...
```
Были мысли после каждой работы с SDK возвращать обратно кастомный CookieManager, но в изначальном initialize вызывается wakeUpSession, который и делает Request, который не удается отследить.

Какой сценарий работы вы планировали, если используется кастомный CookieManager?

**Comment by agent10** [comment]
Тоже самое, используем свой CookieHandler. После каждой ВК аутентификации все наши запросы отваливаются.
