### ISSUE TITLE
Работа с товарным API

### ISSUE THREAD

**Issue by NapalmRain** [VKCOM/vk-android-sdk#215]
Доброго времени суток!

Есть достаточно простая задача получить список товаров у конкретного продавца, для того, что бы выполнить это в своё приложении пишу следующий код:

VKRequest request = new VKRequest("market.get", VKParameters.from(-50515196, null, 100, null, 0));

Но результатом получаю:
VKError (API errorVKError (code: 100; ; One of the parameters specified was missing or invalid: owner_id is undefined))

Из самого текста ошибки я понимаю, в чём она заключается, но я выполняю этот запрос с теми же параметрами на странице запроса в разделе разработчиков и всё отрабатывает корректно.
Параметры указывал и в таком виде и в виде строк, заключая их в кавычки. Результат идентичен.

В тех поддержке вконтакте меня отправили к вам.

Прошу подсказать в чём моя ошибка.

Заранее благодарю!

**Comment by Dreddik** [comment]
VKParameters.from не знает, что -50515196 это owner_id и т.д.
Он принимает пары "ключ-значение", например VKParameters.from("owner_id", -50515196)

**Comment by NapalmRain** [comment]
Благодарю, понял свою ошибку!
Если позволите, ещё один небольшой вопрос: а как мне, собственно, дальше работать с полученным response? В примерах видел работу с пользователями, комментариями и фотографиями, для каждого из них есть свой тип данных, для товаров аналога не нашёл, подумал, что можно работать с ним как просто с JSON строкой, но при приведении к строке получаю:

`Log.d("ANSWER_VK", response.toString());`
результат: `D/ANSWER_VK: com.vk.sdk.api.VKResponse@...`

**Comment by Lomovskiy** [comment]
Вы вызываете `.toString()` у объекта класса `VKResponse`, поэтому и получаете адрес этого объекта в памяти, в виде строки. Ваше решение: `response.responseString`, вызывайте, чтобы получить Json.

**Comment by NapalmRain** [comment]
Понял, благодарю за помощь!
