### ISSUE TITLE
Ошибка при попытке получить изображение java.io.FileNotFoundException

### ISSUE THREAD

**Issue by NapalmRain** [VKCOM/vk-android-sdk#217]
Доброго времени чуток!

Прошу прощения за беспокойство, но никак не могу понять истоки проблемы.
Есть кастомизированный список для загрузки товаров из группы. В нём так же присутствует иконка товара. В адаптере в строке загрузки картинки
`holder.Icon.setImageURI(Uri.parse(values[position].ImageURL));`
Я получаю ошибку:
```
I/System.out: resolveUri failed on bad bitmap uri: https://pp.vk.me/c633323/v633323174/15a6d/Aedwc-beFW4.jpg
E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: https:/pp.vk.me/c630916/v630916174/f5a5/cZOSM2Z6wDQ.jpg: open failed: ENOENT (No such file or directory)
```
Перехожу по ссылке прямо из логов, в браузере картинка отображается корректно.

Прошу подсказки, что именно я делаю не так?

Заранее благодарю!

**Comment by Dreddik** [comment]
Вы неправильно скачиваете картинки, используйте какой-нибудь фреймворк типа Picasso
