### ISSUE TITLE
React-native обёртка для VK SDK под Android?

### ISSUE THREAD

**Issue by sergiks** [VKCOM/vk-android-sdk#219]
Для iOS SDK энтузиасты уже [делают](https://github.com/doochik/react-native-vksdk) обёртку VK SDK в React-native.

Мне, и, вероятно, другим разработчикам сфокусированным на веб-технологиях и далёким от Java / C++, очень помогло бы наличие такого же компонента под Android. Как минимум, решить задачу авторизации через установленное приложение ВК. Как максимум – все доступные методы перекинуть.

**Comment by dkostryukov** [comment]
@sergiks будет круто, если энтузиасты сделают такую же обёртку и для Android!

**Comment by kLkA** [comment]
YOu may try this one https://www.npmjs.com/package/react-native-vkontakte-login
