### ISSUE TITLE
Не загружается картинка из мета-тегов

### ISSUE THREAD

**Issue by sierbrat** [VKCOM/vk-android-sdk#224]
Шарю ссылку в VK через интент, передавая её так:
shareIntent.putExtra(android.content.Intent.EXTRA_TEXT, url);
Для одной и той же ссылки он то подтягивет фото, то нет.
Однажды бала замечена зависимость:
если приложение VK свернуто, картинка шарится, если запускается сначала - то нет.
Но, данная зависимость проявлялась только однажды.
В целом, причины или сценарии не ясны

**Comment by Dreddik** [comment]
Тут не поддержка приложения ВК, но передам
