### ISSUE TITLE
Отсутствуют классы для работы с лентой новостей (newsfeed.*)

### ISSUE THREAD

**Issue by yeputons** [VKCOM/vk-android-sdk#226]
Например, <a href="https://vk.com/dev/newsfeed.get">newsfeed.get</a>. У меня есть некоторые частичные наработки в эту сторону, которые можно попробовать использовать, если такая функциональность вообще планируется.

Кажется, что как минимум реализация этого конкретного метода сложной быть не должна.

**Comment by Dreddik** [comment]
Зачем вам эти классы, если вы можете вызвать любой метод самостоятельно?

**Comment by yeputons** [comment]
Для удобства десериализации. Скажем, тот же newsfeed.get возвращает что-то сложнее стандартных объектов/списков: одновременно список новостей (которые не являются ни постами, ни фотографиями, а чем-то более общим - такой сущности в библиотеке вроде бы еще нет) и список пользователей, а также какую-то служебную информацию. Удобнее вызывать метод и получать объект с полями, чем некий JSON  и бояться опечататься в названии очередного поля (а так это проверит компилятор).

**Comment by dkostryukov** [comment]
Работая с JSON напрямую вы можете использовать парсер, который идеально подходит именно для вашего приложения, JSON дает вам больше свободы в создании быстрого и ресурсосберегающего приложения

**Comment by yeputons** [comment]
@dkostryukov Разумеется, работая напрямую с API получаем больше свободы и, вероятно, скорости. Однако же библиотека зачем-то предоставляется и в ней есть реализации многих других методов. Если у вас есть возможность, я бы хотел получить более развёрнутый комментарий: а чем именно методы работы с лентой принципиально отличаются от остальных методов, реализованных в библиотеке? Мне кажется, аргумент со скоростью применим и к ним. Сейчас получается, что в SDK нет никакого "родного" способа получить ленту новостей, насколько я понимаю.

Или вы подразумеваете, что методы работы с новостями возвращают слишком много всего за один запрос и если уж начинаем их использовать, то наверняка делаем это в погоне за скоростью, а тогда лучше парсер?

**Comment by ilyamodder** [comment]
@Dreddik, ответ от разработчика отличный, конечно. Так бы и сказали, мол, нам лень делать, пилите сами.
