### ISSUE TITLE
Помогите

### ISSUE THREAD

**Issue by kalter704** [VKCOM/vk-android-sdk#227]
Помогите, не могу понять как сделать так, чтобы каждый раз не выходил экран с подтверждением прав доступа.

**Comment by Dwite** [comment]
Пробовал сохранять токен и проверять есть ли он?

**Comment by kalter704** [comment]
Пробовал, но возникает еще одна проблема. Если пользователь захочет воспользоваться моим приложением с другого аккаунта, то он не сможет это сделать, пока токен не обновиться. 

Я хочу сделать так, чтобы экран с подтверждением прав доступа(обновление токена) появлялся, только в двух случаях, 1) при  окончании срока годности старого токена и 2) при смене пользователя.

**Comment by Dwite** [comment]
Всмысле с другого аккаунта? Аккаунта Вк? Аккаунта телефона?

**Comment by kalter704** [comment]
аккаунта вк

**Comment by dkostryukov** [comment]
@kalter704 можете описать подробнее Вашу проблему? а то пункты
 
"2) при смене пользователя."
"Если пользователь захочет воспользоваться моим приложением с другого аккаунта"

противоречат друг другу

**Comment by mmotorniy** [comment]
var vkAccessTokenTracker : VKAccessTokenTracker = object : VKAccessTokenTracker() {
        override fun onVKAccessTokenChanged(oldToken : VKAccessToken?, newToken : VKAccessToken? ) {
            if (newToken == null) {
                VKSdk.login(this@NavigationActivity, "scope=offline,audio");
            } else {
                 //здесь повторяешь обращение
            }
        }
    };

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        
        vkAccessTokenTracker.startTracking();
        //здесь обращаешся прямо к методам, которые требуют авторизации
        //если токен валидный, то метод отработает отлично, если нет
        //то попросит авторизоваться
    }

Это на kotlin. Как то так.

**Comment by Dreddik** [comment]
Мы предполагаем работу SDK с одним пользователем. SDK сам сохраняет токен, от вас только требуется не вызывать forceLogout перед авторизацией
