### ISSUE TITLE
Library Manifest

### ISSUE THREAD

**Issue by Dimdron** [VKCOM/vk-android-sdk#229]
Привет, я использую vk-sdk в своем android-проекте. Как-то заметил, что очень важный receiver с неким фильтром не отрабатывает:
`<intent-filter>
   <action android:name="com.android.vending.INSTALL_REFERRER" />
</intent-filter>`
Изучив проблему, я заметил, что во время сборки проекта, в мой manifest вмердживается `com.vk.sdk.payments.VKPaymentsReceiver`, который мне совсем не нужен, и, который имеет такой же intent-filter. 
К чему я говорю: библиотека не должна обязывать использование компонент, а значит [этот manifest](https://github.com/VKCOM/vk-android-sdk/blob/master/vksdk_library/src/main/AndroidManifest.xml)  должен быть пустой.
Подскажите, если я заблуждаюсь.

**Comment by Dimdron** [comment]
#230

**Comment by Dimdron** [comment]
@Dreddik или так было задумано? Просто вы пишите в readme, что для использования "необходимо добавить в манифест...", но по-факту можно ничего не добавлять (как сделано это в sample).
Я пока что подключил vk-sdk как library module с изменениями.

**Comment by Dreddik** [comment]
Исправлено 4ec7f1432d589bf9d2c77fcd012b61c1aee8d5fd
