### ISSUE TITLE
sdk_fingerprint is incorrect

### ISSUE THREAD

**Issue by belousovconst** [VKCOM/vk-android-sdk#231]
Добрый день, создал android приложение brush, пытаюсь прикрутить авторизацию через VK, сделал все как описано в руководстве, и на основе предложенного примера на гитхабе, но при попытке залогиниться получаю ошибку sdk_fingerprint is incorrect. Приложение Brush с id 5348429, использую дебажный ключ, SHA1 указал для дебажного ключа, на андроиде установлено приложение VK. Самостоятельно ответ не нашел, очень надеюсь на вашу помощь.

**Comment by mmotorniy** [comment]
Попробуй получи фингерпринт прямо в запущеном приложении с помощью String[] fingerprints = VKUtil.getCertificateFingerprint(this, this.getPackageName()); и сравни с тем, что ты прописал в консоли разработчика и ты будешь удивлен)

**Comment by belousovconst** [comment]
абсолютно не буду удивлен, ибо так я тоже делал и прежде чем задать вопрос, я сначала сделал все как в мануале, несколько раз проверил настройки но тем не менее решение проблемы не нашел, в подтверждении своих слов прилагаю ссылку на скриншот, где наглядно видно что fingerprint полученный при запуске приложения тот же что указан в настройках приложения  https://www.dropbox.com/s/b3p0egxebc1y3zn/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-03-15%2021.08.41.png?dl=0

**Comment by Dreddik** [comment]
Проверьте, что в конце не вставился пробел или перенос строки

**Comment by belousovconst** [comment]
да вы абсолютно правы, проверил, оказался символ пробела, даже не подумал об этом, теперь все работает, спасибо

**Comment by mmotorniy** [comment]
Почему название активити не указано?
15 Мар 2016 г. 20:25 пользователь "belousovconst" <notifications@github.com>
написал:

**Comment by artuska** [comment]
Та же самая проблема — пишу в Настройках приложения «Отпечаток сертификата для Android», никаких лишних пробелов нету, все двоеточия удалил (хотя не понимаю, почему сами разработчики на сервере не могут попросту взять и сами элементарно почистить строку от неугодных символов).

Использую команду 
```
keytool -exportcert -alias balumates -keystore android.keystore -list -v
```

и получаю

```
Certificate fingerprints:
MD5:  83:89:AE:22:0E:D1:34:B8:A9:F5:8E:6E:A6:07:F3:42
SHA1: 1F:75:47:34:99:4C:94:EE:36:7C:90:82:1E:82:94:A3:E3:CB:08:E3
SHA256: B3:BC:60:9D:D6:F6:D0:15:CE:81:57:57:A2:A1:0D:A5:D7:D8:B5:A8:0A:CF:FF:75:EB:D0:18:81:90:BE:0D:8F
Signature algorithm name: SHA256withRSA
Version: 3
```

В Настройках приложения «Отпечаток сертификата для Android» вбиваю SHA256-ключ, удаляю все неугодные символы.

При авторизации мне тупо приходит ошибка `sdk_fingerprint is incorrect`.

Что я делаю не так-то?

**Comment by solareye** [comment]
Так нужен ведь SHA1

**Comment by artuska** [comment]
@solareye не, не понимаю, там же написано `SHA256withRSA`

**Comment by solareye** [comment]
@artuska Вы должны увидеть нечто вроде
Certificate fingerprint: SHA1: DA:39:A3:EE:5E:6B:4B:0D:32:55:BF:EF:95:60:18:90:AF:D8:07:09 
ни слова про `SHA256withRSA`

**Comment by solareye** [comment]
И если приложение опубликовано в google play также надо добавить из консоли отпечаток:

**Comment by artuska** [comment]
@solareye ясно, спасибо!

**Comment by solareye** [comment]
@artuska Маленькая поправка - если вы включали Google Play App Signing

**Comment by listros** [comment]
Добрый день, нужна помощь, получил ключ для вк приложения через команду String[] fingerprints = VKUtil.getCertificateFingerprint(this, this.getPackageName()); приложение если ставить из студии работает отлично, когда залил на гугл плэй и установил оттуда, стало такую же ошибку выводить sdk_fingerprint is incorrect

**Comment by plaxin** [comment]
@listros для публикации приложения в Google Play вы подписываете приложение собственным ключём. При этом отпечаток сертификаиа меняется. Запустите на отлаживаемом устройстве приложение, подписанное личным ключём и отследите отпечаток сертификата, его же и введите в настройках приложения в vk.com/dev

**Comment by localhostEU** [comment]
SHA1 отпечаток не должен содержать двоеточий

**Comment by DemonStars** [comment]
solareye попал в точку с консолью. Если вы участвуете  в программе подписи приложения от Google -  они подписывают вашу релизную сборку своим ключом, который можно посмотреть в консоли.
