### ISSUE TITLE
Зачем ставить аннотацию @NonNull а потом проверят на null ?

### ISSUE THREAD

**Issue by mmotorniy** [VKCOM/vk-android-sdk#233]
public class VKSdk {
...
public static boolean onActivityResult(int requestCode, int resultCode, @NonNull Intent data, @NonNull VKCallback<VKAccessToken> vkCallback) {
        if (requestCode == VKServiceActivity.VKServiceType.Authorization.getOuterCode()) {
            if (resultCode == VKSdk.RESULT_OK) {
                vkCallback.onResult(VKAccessToken.currentToken());
            } else if (resultCode == VKSdk.RESULT_ERROR) {
                vkCallback.onError((VKError) VKObject.getRegisteredObject(data == null ? 0 : data.getLongExtra(VKSdk.EXTRA_ERROR_ID, 0)));
            }
            return true;
        } else {
            return false;
        }
    }
...
}

После вызова логина я в onActivityResult получаю data null и пытаюсь пропихнуть его в этот метод, как Вы рекомендуете в readme. И получаю IllegaleStateException. Я использую язык kotlin для разработки приложения. Не понимаю зачем ставить аннотацию @NonNull а потом проверят на null ?

**Comment by Dreddik** [comment]
data сейчас указана nullable

**Comment by mmotorniy** [comment]
Ну,так, укажите в какой версии сдк есть это исправление, и уберите это с readme com.vk:androidsdk:+
Вместо этого указывайте конкретно актуальную версию. Потому что это не есть хорошо, когда версия автоматом обновляется и прилетают новые глюки.
Скачиваю библу через градл, а там все равно присутствует данное issue.

**Comment by Dreddik** [comment]
Что изменится от того, что в документации будет конкретная версия? Во-первых, она появляется на серверах maven через несколько часов, во-вторых, вы всё равно не полезете в документацию смотреть на версию, и думать "а изменилось ли что-то". Версия с исправлением попала в maven вчера, сегодня должно уже быть исправлено, проверяйте

**Comment by mmotorniy** [comment]
Во-первых, ну вот представьте себе, что я использую определенную версию, где стоит аннотация возле переменной nullable. Завтра вы передумали и сменили её на notnull. И с прошлой версией у меня все работало ок, а после обновления краш. Мне каждый раз, когда я собираю проект думать каких там новых косяков прилетит? Нас тимлид больно ругает за использование подхода с подключением библиотек через + вместо номера версии. Даже сама IDEA подсказывает, что + вместо версии может привести к непредсказуемым ошибкам. Что как бы тонко намекает.
Во-вторых, полезу смотреть, если я жду исправления по конкретному issue, то я смогу увидеть в документации, что в такой то версии исправлено, посмотрю у себя в градле, а там версия ниже, и мне надо будет лезть на гитхаб и разводить срач в коментах по этому поводу.

**Comment by Dreddik** [comment]
Хорошо, теперь можете отслеживать версию здесь 
https://github.com/VKCOM/vk-android-sdk/blob/master/README.md#connecting-with-maven

**Comment by mmotorniy** [comment]
Спасибо! Лучшая поддержка из всего что я видел!

**Comment by vitos18** [comment]
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or  view it on GitHub


С уважением,
Виталий Рочняк
vitaliy.rochnyak@mail.ru
