### ISSUE TITLE
Рассширеные примеры

### ISSUE THREAD

**Issue by studmix** [VKCOM/vk-android-sdk#234]
Может я многого прошу , но было бы хорошо для новичков сделать более рассширеный пример с работой api в sample приложении, тоже с самое с работой push уведомлениями , загрузкой аватаркой , со спискам групп , мелодий и тд. Эти примеры очень помогли бы новичкам

**Comment by Dreddik** [comment]
Мы считаем, что текущего примера достаточно, чтобы ознакомиться с SDK и работой с API:
* есть пример, как делать запросы к API
* есть пример, как загружать фоточки
* есть пример, как обрабатывать ошибки
* есть пример, как показывать окно шаринга

Дальше сами, мы клиенты за вас писать не будем
