### ISSUE TITLE
Не загружается фото на стену

### ISSUE THREAD

**Issue by formakidov** [VKCOM/vk-android-sdk#236]
uploadWallPhotoRequest отрабатывает без ошибок, но фото не загружается и не отображается на стене. Пробовал разные аккаунты. Через ShareDialog загружается нормально. 

scopes: VKScope.WALL, VKScope.PHOTOS

onComplete:

{"response":[{"id":407800462,"album_id":-14,"owner_id":232165140,"photo_75":"https:\/\/pp.vk.me\/c631922\/v631922140\/1ca9a\/Q25sSwFr4aM.jpg","photo_130":"https:\/\/pp.vk.me\/c631922\/v631922140\/1ca9b\/o2pawvd1nJk.jpg","photo_604":"https:\/\/pp.vk.me\/c631922\/v631922140\/1ca9c\/P6Wsv-1p_II.jpg","width":96,"height":96,"text":"","date":1458723637}]}

```
VKRequest request = VKApi.uploadWallPhotoRequest(new File(path),
					Integer.valueOf(VKAccessToken.currentToken().userId), 0);
request.attempts = 3;
request.executeWithListener(new VKRequest.VKRequestListener() { ... });
```

**Comment by Dreddik** [comment]
В результате вы получаете фотку, которую надо вставить в wall.post

**Comment by formakidov** [comment]
А через один запрос никак нельзя запостить фотку с текстом сразу на стену?

**Comment by Dreddik** [comment]
Нет
