### ISSUE TITLE
Вопрос: Есть ли метод для получения "hash" VK-приложения?

### ISSUE THREAD

**Issue by DemonStars** [VKCOM/vk-android-sdk#239]
Привет! Речь идет про следующее:
Hash, который формируется конкатинацией следующих строк
hash = md5(vkAppId + uid + vkAppKey)

Естественно, можно и самому собрать его, но это получается менее безопасный способ
Доп. вопрос: Можно ли получить этот hash при восстановлении сессии, т.е. в теле условия:
if (VKSdk.wakeUpSession(this)) {
            Log.d(TAG, "Vk session have been saved");
//TODO : getHash();
        }

**Comment by Dreddik** [comment]
Зачем?
