### ISSUE TITLE
VKApi.wall().get не работает EXTENDED

### ISSUE THREAD

**Issue by martsinkevych** [VKCOM/vk-android-sdk#240]
Привет. я сейчас делаю приложение для Android (android studio, Java). добавил ваш сдк. 

так подключаю библиотеку:
compile 'com.vk:androidsdk:1.6.6'

так создаю запрос на получение новостей:
VKRequest request = VKApi.wall().get(VKParameters.from(VKApiConst.OWNER_ID, -27895931, VKApiConst.COUNT, 1, VKApiConst.EXTENDED, 1)); 
возвращает нужный масив новостей, но там нет полей (user_likes и user_reposted), которые указывают лайкал ли репостил пользователь запись. если поменять последный параметр на 0, то резутальт остается прежний.

как узнать лайкал(репостил) ли пользователь запись? 

пример ответа: 
{
"response": {
"count": 28616,
"items": [
{
"id": 3353048,
"is_pinned": 1,
"text": "Сегодня солнечно на улице и на душе моей тепло..",
"reposts": {
"count": 170
},
"from_id": -27895931,
"likes": {
"count": 1134
},
"owner_id": -27895931,
"post_type": "post",
"attachments": [
{
"type": "video",
"video": {
"photo_130": "https://pp.vk.me/c627523/u234352279/video/s_53a6cc32...",
"id": 456239017,
"duration": 247,
"title": "Андрей Иванцов - За спиной, как за стеной",
"views": 74481,
"description": "Крепкая семья – главная ценность нашей жизни. \nС этим утверждением согласны 95% успешных людей, которые, согласно статистике, живут в счастливом браке. \nПредлагаем вашему вниманию новый видеоклип Андрея Иванцова \"За спиной как за стеной\" - любите, доверяйте, наслаждайтесь обществом друг друга до глубокой старости, и пусть ваша семья крепнет с каждым годом.",
"owner_id": 234352279,
"photo_320": "https://pp.vk.me/c627523/u234352279/video/l_9c1dbd1c...",
"access_key": "a4d7806bffeff282e5",
"date": 1458047287,
"photo_640": "https://pp.vk.me/c627523/u234352279/video/y_d1d5d63c...",
"comments": 3
}
}
],
"date": 1459185610,
"comments": {
"count": 3
}
}
],
"groups": [
{
"id": 27895931,
"photo_200": "https://pp.vk.me/c629429/v629429999/4f767/bh6Y_yGoZNc..",
"photo_50": "https://pp.vk.me/c629429/v629429999/4f769/-5GiesUK02k..",
"is_closed": 0,
"name": "Новинки Музыки 2016",
"screen_name": "exclusive_muzic",
"type": "page",
"photo_100": "https://pp.vk.me/c629429/v629429999/4f768/7SFzmX1pqwk.."
}
],
"profiles": []
}
}

**Comment by Dreddik** [comment]
Если вы не логинились, эти поля не будут приходить

**Comment by KChernenko** [comment]
@Dreddik а если логинились, но метод не отрабатывает? 
На получение информации о пользователе:
`VKApi.users().get(VKParameters.from(VKApiConst.FIELDS, "bdate, city, country"))`
ок.

На получение постов:
```
VKApi.wall().get(VKParameters.from(VKApiConst.OWNER_ID, VKAccessToken.currentToken().userId,
                VKApiConst.COUNT, 15, VKApiConst.EXTENDED, 1))
```
Не отрабатывает вообще. Везде запросы синхронные.
