### ISSUE TITLE
Инициализация

### ISSUE THREAD

**Issue by deko519** [VKCOM/vk-android-sdk#241]
Добрый день!

Вставляем поддержку VK API для нашей игры.

При вызове  `VKSdk.initialize(activity);` в лог выводятся следующие сообщения:
```
03-31 10:06:34.681 21039 21222 I dalvikvm: Could not find method android.webkit.CookieManager.removeAllCookies, referenced from method com.vk.sdk.VKSdk.logout
03-31 10:06:34.681 21039 21222 W dalvikvm: VFY: unable to resolve virtual method 15642: Landroid/webkit/CookieManager;.removeAllCookies (Landroid/webkit/ValueCallback;)V
```
после чего бьется java VM и все java вызовы из native кода становятся недоступны.

Девайс Nexus 2012, android 4.4.4 (API 20). removeAllCookies - это API 21.

**Comment by Dreddik** [comment]
Он в API 20 и не вызывается, тем более в методе initialize.
Вы уверены, что проблема с java vm происходит именно из-за этого? Просто это выглядит как обычное предупреждение и инфо, не ошибка

**Comment by deko519** [comment]
Проблема решилась переносом вызова `initialize` в `onCreate`.
