### ISSUE TITLE
video.save периодически теряет авторизационный токен

### ISSUE THREAD

**Issue by egv** [VKCOM/vk-android-sdk#242]
Столкнулись со следующей проблемой: при вызове `video.save` на некоторых устройствах возвращается ошибка `auth_error`, при этом
- другие методы (получение статуса пользователя) работают ок
- если явно передать токен в параметрах `video.save`, то вызов проходит ок
- воспроизведение не в 100% случаев

Это проявляется только на сборках из google play и не проявляется на отладочных сборках. 
Стабильно воспроизводится на samsung galaxy s6 c последней официальной прошивкой.

/cc @linreal

**Comment by Dreddik** [comment]
Вряд ли проблема в SDK
