### ISSUE TITLE
Запрос apps.sendRequest невозможно проверить на приложении, не прошедшем модерацию.

### ISSUE THREAD

**Issue by darkstarx** [VKCOM/vk-android-sdk#243]
Чтобы отправить приложение на модерацию, я должен быть уверен, что оно работает. Но метод apps.sendRequest я проверить не могу.

1. Если пользователя нет среди админов приложения, то при попытке отправить ему приглашение, получаем такую ошибку:
API errorVKError (code: 15; ; Access denied: this method is allowed only for approved apps)
2. Если пользователь есть среди админов ("Отправка запросов в приложениях, не опубликованных в Мобильном каталоге, доступна только администраторам приложения.", https://new.vk.com/dev/apps.sendRequest), то у него уже приложение оказывается установленным. Соответственно ошибка такая:
API errorVKError (code: 15; ; Access denied: invited user has already installed this application)

Как мне проверить, что функция моего приложения, связанная с запросом apps.sendRequest, корректно работает?

**Comment by babichev** [comment]
Эта ситуация описана в документации в самом низу страницы https://vk.com/dev/game_invites. 

> Обратите внимание, что пока игра не запущена в мобильном каталоге, метод apps.sendRequest позволяет отправлять запросы только между администраторами приложения. Это значит, что пригласить в игру никого не получится, однако проверить работу приглашений можно. 
> В методе apps.sendRequest приглашение и запрос отличаются только параметром type. Потому для проверки можно передать параметр type=request. Если на него вернется корректный ответ, значит и приглашение через type=invite отобразится корректно в каталоге у получателя.

**Comment by darkstarx** [comment]
VKSdk request: com.vk.sdk.api.VKRequest@40c0d57{apps.sendRequest access_token=xxx user_id=yyy type=request name=zzz_invite_request key=zzz_invite_key separate=1 }

VKSdk onError VKError (API errorVKError (code: 15; ; Access denied: this method is allowed only for approved apps))

что я делаю не так?

**Comment by babichev** [comment]
Пришлите ссылку на приложение и на администраторов. 
Если что, можно в личку —  vk.com/max

**Comment by darkstarx** [comment]
Проблему решили. Указывал в запросе закэшированный accessToken от другого приложения.
Спасибо за помощь в решении проблемы!
