### ISSUE TITLE
Падение при использовании VKShareDialog когда доступ приложению заблокирован

### ISSUE THREAD

**Issue by agent10** [VKCOM/vk-android-sdk#244]
> 04-12 14:30:11.448: E/AndroidRuntime(10875): java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.vk.sdk.VKAccessToken.userId' on a null object reference
> 04-12 14:30:11.448: E/AndroidRuntime(10875):    at com.vk.sdk.dialogs.VKShareDialogDelegate.makePostWithAttachments(VKShareDialogDelegate.java:330)
> 04-12 14:30:11.448: E/AndroidRuntime(10875):    at com.vk.sdk.dialogs.VKShareDialogDelegate.access$700(VKShareDialogDelegate.java:75)
> 04-12 14:30:11.448: E/AndroidRuntime(10875):    at com.vk.sdk.dialogs.VKShareDialogDelegate$4.onClick(VKShareDialogDelegate.java:377)
> 04-12 14:30:11.448: E/AndroidRuntime(10875):    at android.view.View.performClick(View.java:4856)
> 04-12 14:30:11.448: E/AndroidRuntime(10875):    at android.view.View$PerformClick.run(View.java:19956)
> 04-12 14:30:11.448: E/AndroidRuntime(10875):    at android.os.Handler.handleCallback(Handler.java:739)
> 04-12 14:30:11.448: E/AndroidRuntime(10875):    at android.os.Handler.dispatchMessage(Handler.java:95)
> 04-12 14:30:11.448: E/AndroidRuntime(10875):    at android.os.Looper.loop(Looper.java:211)
> 04-12 14:30:11.448: E/AndroidRuntime(10875):    at android.app.ActivityThread.main(ActivityThread.java:5373)
> 04-12 14:30:11.448: E/AndroidRuntime(10875):    at java.lang.reflect.Method.invoke(Native Method)
> 04-12 14:30:11.448: E/AndroidRuntime(10875):    at java.lang.reflect.Method.invoke(Method.java:372)
> 04-12 14:30:11.448: E/AndroidRuntime(10875):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
> 04-12 14:30:11.448: E/AndroidRuntime(10875):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)

**Comment by alexmalikov** [comment]
Такая же проблема возникла:
1. Авторизуюсь в приложении через ВК
2. Добавляю пост на стену через приложение 
3. Захожу в настройки приложений (в десктопной версии) и удаляю свое приложение из списка
4. Снова пытаюсь добавить пост, приложение падает с таким же стектрейсом
