### ISSUE TITLE
wall.get() — parsedModel == null 

### ISSUE THREAD

**Issue by RankoR** [VKCOM/vk-android-sdk#248]
Код:
`VKParameters vkParameters = VKParameters.from(VKApiConst.USER_ID, SettingsManager.getInstance().getVkId());

```
    VKRequest vkRequest = VKApi.wall().get(vkParameters);
    vkRequest.executeWithListener(new VKRequest.VKRequestListener() {
        @Override
        public void onComplete(VKResponse response) {
            super.onComplete(response);

            VKList<VKApiPost> posts = (VKList<VKApiPost>) response.parsedModel;
            for (VKApiPost post : posts) {
                Logger.i(GuestsActivity.class, "Post: " + post.getId());
            }
        }

        @Override
        public void onError(VKError error) {
            super.onError(error);
        }
    });`
```

[Скрин дебаггера](https://habrastorage.org/files/287/35a/ba4/28735aba44164ec3b4641d30c7536cab.png)

Версия 1.6.7

Как так? :)

**Comment by alexneo2003** [comment]
у метода wall.get первый параметр owner_id
но это уже, наверное, не актуально.

кто мне подскажет как привести response полученный в результате выполнения execute запроса к .parsedModel ??

**Comment by olegsm** [comment]
Please use new SDK version 2.0
