### ISSUE TITLE
Как убрать повторные запросы на доступ к аккаунту

### ISSUE THREAD

**Issue by sportwtany** [VKCOM/vk-android-sdk#250]
Настроил авторизацию по документации. Но каждый раз при авторизации vk запрашивает разрешение на доступ к аккаунту. Как сделать так, чтобы это было однократно для одного утсройства?

**Comment by Svechnikov** [comment]
Можно использовать проверку, авторизован пользователь или нет:

```
        if (!VKSdk.isLoggedIn()) {
            VKSdk.login(this, "friends", "groups", "wall", "photos");
        }
        else {
            //user авторизован
        }
```

**Comment by sportwtany** [comment]
@Svechnikov после того как я сделаю VKSdk.logout(), isLoggedIn вернет false, и снова появится запрос разрешения на доступ

**Comment by lyamin259** [comment]
Можно сохранять token, используя SharedPreferences. Например сохраняем его в методе onStop, а в методе onCreate проверяем существует ли объект SharedPreferences, если есть то загружаем этот token, если его нету то проводим авторизацию.

**Comment by sportwtany** [comment]
@lyamin259 но при выходе (logout) мы его сотрем и история повторится, я правильно понимаю?

**Comment by lyamin259** [comment]
@sportwtany При выходе (logout), при переустановки приложения, token меняется. А если все же сохраните token в свою переменную, а потом его загрузить то он будет недействительным. Но можете попробовать.

Получить значение текущего token можно так: ` String Token = VKAccessToken.currentToken().accessToken`

Загрузить сохраненный токен из переменной можно так: `VKAccessToken.tokenFromUrlString();`

Токен меняется при каждом выходе (logout).

**Comment by dkostryukov** [comment]
@sportwtany а зачем вам не показывать запрос на разрешение доступа после logout?

**Comment by sportwtany** [comment]
@dkostryukov просьба заказчиков)

**Comment by Dreddik** [comment]
Запрос на разрешение показывается, потому что иначе iOS посчитает переключение [app] -> [vk app] -> [app] слишком быстрым, и начнёт показывать стрёмные диалоговые окна в стиле "Вы действительно хотите открыть app?"
Кроме того, пользователь понимает, что происходит.

**Comment by Dreddik** [comment]
*фигню написал, не в тот тред

**Comment by dkostryukov** [comment]
@sportwtany запрашивать должны каждый раз
