### ISSUE TITLE
Get 'key' parameter from sendRequest

### ISSUE THREAD

**Issue by afrokick** [VKCOM/vk-android-sdk#252]
Hi. Can I get a 'key' parameter? I want to send request ( https://vk.com/dev/apps.sendRequest ) and check 'key' on client side.

The documentation says that 

> строка, которая будет возвращена назад при переходе пользователя по запросу в приложение. Может использоваться для подсчета конверсии. 

but how can I get it in android/ios?

**Comment by Dreddik** [comment]
For iOS key parameter will be passed in application URL for your application like:
`vk123456://request?key=value`
For Android you will receive `key` parameter inside of extras of your launch activity intent.

**Comment by afrokick** [comment]
You should add this description to documentation, because it not transparent for developers. Thanks a lot!
