### ISSUE TITLE
invalidate token, when my game server revalidate it

### ISSUE THREAD

**Issue by zx1299** [VKCOM/vk-android-sdk#253]
I found a fatal problem when using vk sdk. 

when a user login, client will get token from sdk, then I post this token to server, my game server will use this token for authorization. But server receive token is time out from vk server. 

This problem isnot exist every time, it is sometimes. I get token is correct use your's demo call VkTestApplication.  So what is problem?

**Comment by zx1299** [comment]
@ Dreddik, can you help me?

**Comment by Dreddik** [comment]
You can't use client tokens for server authentication. 
In this case you have to implement ["Authorization Code Flow"] (https://new.vk.com/dev/auth_sites) manualy

**Comment by zx1299** [comment]
I mean that my game client app get token, then send this value to my game server. game server pass this value using vk api called [secure.checkToken]. If it is true, game server will think it is a authentication user, othersize sendback a error. The problem is that server send client's token to vk server, sometimes vk server think token is uncorrect!

**Comment by zx1299** [comment]
@Dreddik , my app isnot a webiste app, it is a mobile game. Wait for you's comment

**Comment by Dreddik** [comment]
Can you post a text of the error?

**Comment by zx1299** [comment]
yes， wait a moment. Do you think my authorization is right or not?

**Comment by Dreddik** [comment]
If you just call secure.checkToken on the server side, the authorization should be correct.

**Comment by zx1299** [comment]
ok,Thank you.  I want ask a question, how long a http call is timeout will be nice?

**Comment by zx1299** [comment]
i think it is time for close this issume. Maybe there isnot any problem, Just our server's problem.
@Dreddik  THKS!  you are a good man.
