### ISSUE TITLE
Как отобразить Api Confirm диалог из приложения?

### ISSUE THREAD

**Issue by afrokick** [VKCOM/vk-android-sdk#254]
Добрый день. По ссылке https://vk.com/dev/api_confirm сказано, что СДК само обрабатывает ситуацию, когда нужно показать диалог.

Такой вопрос. Можно ли как-то вызвать нативный клиент, чтобы он отобразил окно подтверждения действия?

Пример:

Я отсылаю приглашение другу методом apps.sendRequest через HTTP API. Мне приходит ошибка и redirect_uri. Теперь я должен показать пользователю окно браузера. Но я хочу отобразить нативный клиент с окном подтверждения.

Смотрел исходники, но не нашел чего-то подходящего типа схемы "vkontakte://validation?..."

Что можно сделать?

**Comment by Dreddik** [comment]
Зачем? Показывая webview самостоятельно, вы экономите ресурсы, и ваше приложение не будет выгружено из памяти на переключениях

**Comment by afrokick** [comment]
Потому что пользователь мог войти в прилагу используя нативное приложение, а в вебвью он не будет авторизован.

**Comment by Dreddik** [comment]
Вам придёт специальная ссылка, в которой не требуется авторизация пользователя

**Comment by afrokick** [comment]
Супер круто! Спасибо за совет. Варианта с нативной прилагой нет?

**Comment by Dreddik** [comment]
Нет

**Comment by afrokick** [comment]
Ок. Еще раз спасибо
