### ISSUE TITLE
Версия API в SDK

### ISSUE THREAD

**Issue by lyamin259** [VKCOM/vk-android-sdk#255]
Как изменить версию API в SDK для Android? Сейчас в SDK используется версия 5.21, а актуальная 5.52.

SDK выдает token для старой версии api. Работать с запросам, используя актуальную версию, например через Retrofit, становится почти невозможно.

Спасибо!

**Comment by Dreddik** [comment]
VKSdk.initialize(ctx, MY_APP_ID, "5.52");

**Comment by lyamin259** [comment]
Может быть VKSdk.customInitialize(ctx, MY_APP_ID, API); ?

Почему - то после этого появилась страница "page not found", не знаете из-за чего это может быть?

**Comment by Dreddik** [comment]
Извините, неправильно написал.
Нужно создать в ресурсах приложения строку com_vk_sdk_ApiVersion, и вписать туда версию.
page not found — на сервере сейчас что-то поломалось, чинят

**Comment by lyamin259** [comment]
@Dreddik Спасибо, сделал, но проблема почему - то осталась.

Например, отправляю запрос на получение списка диалогов, в ответ приходит следующее

{"response":[575,{"mid":123793,"date":1463476829,"out":1,"uid":12271517,"read_state":0,"title":" ... ","body":"ля ля ля"}]}

Тут есть поля mid, uid  - это вообще использовалось в версии API 4.94. Я сделал как вы сказали, добавил строку в ресурсах использовал customInitialize.

**Comment by Dreddik** [comment]
customInitialize использовать не нужно, нужно использовать обычный

**Comment by lyamin259** [comment]
@Dreddik  Да, так и сделал. 

Сделал строку: <string name="com_vk_sdk_ApiVersion">5.52</string>
Использую: VKSdk.initialize(ctx);

Но все равно ответ приходит как для старого API.
