### ISSUE TITLE
wrong logout hash

### ISSUE THREAD

**Issue by zx1299** [VKCOM/vk-android-sdk#258]
i find a little bug， when call vk api to show the vk auth webpage in weview component. 
first click logout multi times quickly, then it display a error: wrong logout hash.
I have search the core api, but i cannot find how to delete this tips.

Best regards!

**Comment by zx1299** [comment]
is it nobody can help me? ;(

**Comment by Dreddik** [comment]
Your question redirected to responsible developer

**Comment by zx1299** [comment]
what? i doesnot understand

**Comment by Dreddik** [comment]
Just wait for a while.

**Comment by zx1299** [comment]
ok, I will wait until the developer come back

**Comment by zx1299** [comment]
@Dreddik, how to get help?

**Comment by zx1299** [comment]
@Dreddik, "wrong logout hash" show in VKOpenAuthDialog.java at WebViewClient. The problem is user cannot close this window, then my game is stopped this page!!!!
Wait for you!

**Comment by Dreddik** [comment]
Please, stop flooding, we recognized issue

**Comment by Dreddik** [comment]
Must be fixed now

**Comment by zx1299** [comment]
hi, sorry for Reckless yesterday! I doesnot need reinstall sdk agin? it just modify in server.

**Comment by zx1299** [comment]
@Dreddik, I am sorry that it appear agin, if the network isnot affluent.

**Comment by Dreddik** [comment]
Check one more time, plz. Maybe now it's okay
