### ISSUE TITLE
Пост фотографий на стену юзера

### ISSUE THREAD

**Issue by MEDVEPUT** [VKCOM/vk-android-sdk#259]
Приветствую. 
Конечно понимаю, что данный вопрос достал всех, но все же
Не могу разобраться с отправлением постов на стену, в частности фотографий.
По примеру сделал отправку сообщений на стену.
А вот с отправкой фотографий не могу разобраться. Код взял из примера, но все равно не работает. По нажатию кнопки вылетает ошибка: [клик](http://i.imgur.com/k0MSfA1.png)
Для примера взял этот кусок:

```
{
					final Bitmap photo = getPhoto();
					VKRequest request1 = VKApi.uploadWallPhotoRequest(new VKUploadImage(photo, VKImageParameters.jpgImage(0.9f)), 0, TARGET_GROUP);
					VKRequest request2 = VKApi.uploadWallPhotoRequest(new VKUploadImage(photo, VKImageParameters.jpgImage(0.5f)), 0, TARGET_GROUP);
					VKRequest request3 = VKApi.uploadWallPhotoRequest(new VKUploadImage(photo, VKImageParameters.jpgImage(0.1f)), 0, TARGET_GROUP);
					VKRequest request4 = VKApi.uploadWallPhotoRequest(new VKUploadImage(photo, VKImageParameters.pngImage()), 0, TARGET_GROUP);

					VKBatchRequest batch = new VKBatchRequest(request1, request2, request3, request4);
					batch.executeWithListener(new VKBatchRequestListener() {
						@Override
						public void onComplete(VKResponse[] responses) {
							super.onComplete(responses);
							recycleBitmap(photo);
							VKAttachments attachments = new VKAttachments();
							for (VKResponse response : responses) {
								VKApiPhoto photoModel = ((VKPhotoArray) response.parsedModel).get(0);
								attachments.add(photoModel);
							}
							makePost(attachments);
						}

						@Override
						public void onError(VKError error) {
							showError(error);
						}
					});
				}
```
Ну или я чего-то не усмотрел/недокопипастил

**Comment by Dreddik** [comment]
Возможно, ваша фотка null

**Comment by MEDVEPUT** [comment]
Тогда следующий вопрос, в SDK функция открытия фотографий для выбора присутствует? По методу _getPhoto_ и  _recycleBitmap_ она есть. Но у меня по нажатию кнопки даже не открывается окно выбора

**Comment by MEDVEPUT** [comment]
Тогда следующий вопрос, в примере функция открытия фотографий для их выбора присутствует? По методу _getPhoto_ и  _recycleBitmap_ я так, что понял она есть, но у меня по нажатию кнопки даже не открывается окно выбора

**Comment by Dreddik** [comment]
Нет, там читается картинка из assets

**Comment by MEDVEPUT** [comment]
Супер! Потихоньку начинаю въезжать.
А можно же как то выводить изображения не только с Assets? Допустим, мне надо будет выбрать несколько изображений, как мне их передать Bitmap'у?
Спасибо большое

**Comment by Dreddik** [comment]
Каждое изображение у вас будет Bitmap

**Comment by MEDVEPUT** [comment]
А я могу передать BitMap'у адрес Uri?

**Comment by dkostryukov** [comment]
@MEDVEPUT вы можете по Uri загрузить bitmap и уже с ним рабоать

**Comment by MEDVEPUT** [comment]
@dkostryukov ну я сделал по другому. Я сначала загружаю в ImageView, а потом уже передаю
