### ISSUE TITLE
Поднять приложение ВКонтакте(если есть на телефлоне) на нужный профиль, передав id пользователя?

### ISSUE THREAD

**Issue by esseckers** [VKCOM/vk-android-sdk#260]
Всем привет, ребят подскажите, плиз, возможно у вас такое? Дернуть ваше приложение на страницу юзера по его Id?

Андроид, забыл уточнить)

В VKSdk не нашел такого(

Заранее спасибо)

**Comment by dkostryukov** [comment]
@esseckers можно открыть ссылку вида https://vk.com/id[id] , в данном случае покажется окно выбора, открыть в браузере или в приложении. Если дернуть ссылку вида vk://vk.com/id[id] , то откроется приложение VK, только надо помнить, что нужно проверить, установлено приложение VK на устройстве

**Comment by esseckers** [comment]
да, я уже понял)) спасибо, извините за беспокойства
