### ISSUE TITLE
VKShareDialogBuilder и VKShareDialog, при нажатие на Send - уходит в метод ошибки.

### ISSUE THREAD

**Issue by devilasd93** [VKCOM/vk-android-sdk#261]
Добрый день.
Не могу понять в чем может быть ошибка.
Постоянно выдает ошибка -101, а в тексте ошибки - null.

Вот мой код.
` new VKShareDialogBuilder()
                        .setText("I created this post with VK Android SDK\nSee additional information below\n#vksdk")
                        .setAttachmentLink("VK Android SDK information", "https://vk.com/dev/android_sdk")
                        .setShareDialogListener(new VKShareDialog.VKShareDialogListener() {
                            @Override
                            public void onVkShareComplete(int postId) {
                                Log.v("DebLogs","onVkShareComplete");
                            }

                            @Override
                            public void onVkShareCancel() {
                                Log.v("DebLogs","onVkShareCancel");
                            }

                            @Override
                            public void onVkShareError(VKError error) {
                                Log.v("DebLogs","ERROR CODE:"+error.errorCode);
                                Log.v("DebLogs","ERROR MESSAGE:"+error.errorMessage);
                            }
                        })
                        .show(activity.getSupportFragmentManager(), "VK_SHARE_DIALOG");`
              

Код тут взят из Вашего примера. Переменная activity у меня AppCompatActivity, который наследуется от FragmentActivity.

Так же пробовал перейти на старую версию SDK - 1.5 с VKShareDialog. Но та же проблема.

**Comment by dkostryukov** [comment]
@devilasd93 https://new.vk.com/dev/errors

101Неверный API ID приложения. 
Найдите приложение в списке администрируемых на странице http://vk.com/apps?act=settings и укажите в запросе верный API_ID (идентификатор приложения).

возможно, вы не правильно указали app_id в ресурсах, как описано в READ.ME
