### ISSUE TITLE
нет библиотеки VKSdkListener

### ISSUE THREAD

**Issue by SpanSpace** [VKCOM/vk-android-sdk#263]
Как ее подключать, т.к в одном из гайдов она используется, или я что то не так понял, но путь к ней такой же как и у других библиотек вк: import com.vk.sdk.VKSdkListener;

**Comment by Dreddik** [comment]
Это не библиотека, а класс в библиотеке vk-android-sdk

**Comment by SpanSpace** [comment]
да, только почему у меня нет его

**Comment by Dreddik** [comment]
Потому что он устаревший, и не используется больше.
Смотрите README, или приложение-пример

**Comment by SpanSpace** [comment]
хорошо, спасибо)
