### ISSUE TITLE
Push не приходит. 

### ISSUE THREAD

**Issue by lectricas** [VKCOM/vk-android-sdk#264]
GCM нормально настроен. 
http://apns-gcm.bryantan.info/
проверил через этот сервис. 
account.registerDevice возвращает  {"response":1}
что я делаю не так?
5490327 - id приложения.

**Comment by lectricas** [comment]
com.vk.sdk.api.VKRequest@1b7f2b2{account.registerDevice token=******* device_model=android device_id=78b97634-b42b-4e1f-bd30-70f7ff909fff settings={"msg":"on", "friend":"on", "reply":"on", "mention":"fr_of_fr"} }

**Comment by Dreddik** [comment]
Что возвращает метод `account.getPushSettings`?

**Comment by lectricas** [comment]
`{"response":{"settings":{"msg":["on"],"chat":["off"],"friend":["on"],"friend_found":["off"],"friend_accepted":["off"],"reply":["on"],"comment":["off"],"mention":["on","fr_of_fr"],"like":["off"],"repost":["off"],"wall_post":["off"],"wall_publish":["off"],"group_invite":["off"],"group_accepted":["off"],"event_soon":["off"],"tag_photo":["off"],"app_request":["off"],"sdk_open":["off"],"new_post":["off"],"snap":["off"],"birthday":["off"]},"conversations":{"count":2,"items":[{"peer_id":2000000001,"sound":1,"disabled_until":3599},{"peer_id":2000000004,"sound":1,"disabled_until":-1}]}}}`

**Comment by Dreddik** [comment]
В разделе `https://new.vk.com/apps?act=manage` для приложения, на котором тестируете, указаны корректные `Project Id` и `Simple API Key`?

**Comment by lectricas** [comment]
Там hidden символы но я дважды перекопировал.  Поменял еще settings - вернуло измененные.

**Comment by lectricas** [comment]
не бросай меня)

**Comment by lectricas** [comment]
Может все таки поможете разобраться в чем тут дело? Иначе придется каждый раз ходить на сервер и просить сообщения...

**Comment by Dreddik** [comment]
Мне нужен id пользователя, которому предназначаются пуши.

**Comment by lectricas** [comment]
допустим вот этот: https://vk.com/id273178150

**Comment by lectricas** [comment]
В общем я повторил всю цепочку - гсм работает - вк по прежнему не отправляет пуш. 
Да, вот такой вопрос - нужно авторизацию проходить через вк клиент или через браузер?
Цепочка такая - авторизируюсь через браузер пользователем https://vk.com/id273178150 - подключаю гсм через account.registerDevice и начинаю писать этому же пользователю личные сообщения.

**Comment by lectricas** [comment]
VK SDK android “sdk_fingerprint is incorrect” error
еще вот такая ошибка при попытке авторизации через приложение. 
фингерпринт беру через 
String[] fingerprints = VKUtil.getCertificateFingerprint(SocialNetworkChooseActivity.this, SocialNetworkChooseActivity.this.getPackageName());
пэкедж взял из манифеста, MainActivity беру как 

<action android:name="android.intent.action.MAIN" />
<category android:name="android.intent.category.LAUNCHER" />
и пишу только название, без пэкеджа и точек.

**Comment by Dreddik** [comment]
Попробуйте сейчас поотправлять сообщения тому пользователю, мы попробуем понять, что происходит.

По поводу отпечатка: убедитесь, что он введён без двоеточий и пробелов, что в конце нет пробелов, что у вас заведено два отпечатка для дебага и недебага.
MainActivity можно не заполнять.

**Comment by lectricas** [comment]
My bad - в VKSdk.customInitialize указан был не тот apID.
Начинаю отправлять сообщения.

**Comment by Dreddik** [comment]
Нам отбивает с ошибкой InvalidRegistration

**Comment by Dreddik** [comment]
token должен быть не access_token'ом, а токен от гугла

**Comment by lectricas** [comment]
server или client?

**Comment by Dreddik** [comment]
Видимо client, то, что получает приложение при подписке на GCM

**Comment by lectricas** [comment]
ееееееее приходит, спасибо. Почему-то решил что вы сами генерируете этот токен, раз я отдаю senderID.
