### ISSUE TITLE
When calling VKSdk.logout

### ISSUE THREAD

**Issue by xingstarx** [VKCOM/vk-android-sdk#265]
Our products use VK as a third party login method.

and I called VKSDK.login to sign in in LandingActivity .

But I don't know  when did I call VKSdk.logout?

is in product logout time? 

or for the first time or after a successful login, the server callback verification?(like below code:)

```
mSubscription = AppObservable.bindActivity(LandingActivity.this, api.loginBySocial()).subscribe(
                new Action1<User>() {
                    @Override
                    public void call(@NonNull User user) {
                        VKSdk.logout();
                        //todo start to MainActivity
                     }
                });
```

Can you help me..Thanks..

**Comment by olegsm** [comment]
Please use new SDK version 2.0
