### ISSUE TITLE
Как сделать выполнение  нескольких запросов последовательно?

### ISSUE THREAD

**Issue by zerolimitss** [VKCOM/vk-android-sdk#266]
Как сделать чтобы набор запросов выполнялись не мгновенно а последовательно и с задержкой 3 запроса в секунду?
Пробовал такую схему, в цикле создается поток, выполняется запрос(в каждом запросе меняется id) и результат помещается в коллекцию:

> 

> for (...) {
>             new Thread(new Runnable() {

>                 public void run() {

 >                     VKRequest request...

>                      request.executeWithListener(new VKRequest.VKRequestListener() {...
> }}}).start();

но почему-то выполняется (по крайней мере успешно) только 5-7 запросов остальные не знаю куда деваются и еще не редко происходят дубликаты. Что делать?

**Comment by dkostryukov** [comment]
Для этого существует VKBatchRequest, почитайте в документации https://vk.com/dev/android_sdk

**Comment by dkostryukov** [comment]
@zerolimitss Вы можете создать так:

ExecutorService executorService = Executors.newFixedThreadPool(3);

	public void main() {
		VKRequest vkRequest = new VKRequest("bla bla bla");
		VKRequestListener vkRequestListener = null; // your listener
		executorService.execute(new VKRequestSync(vkRequest, vkRequestListener));
	}

	public static class VKRequestSync implements Runnable {

		private static final long COUNTER_RESET_TIME = 1000;
		private static final long MAX_REQUESTS_PER_COUNT = 3;
		private static final AtomicInteger requestCounter = new AtomicInteger(0);
		private static volatile long counterResetTime = System.currentTimeMillis();

		public static void waitTooManyRequest() {
			// ---------- FIX WAIT 2 SEC EVERY 10 REQUEST ---------- todo
			synchronized (requestCounter) {
				if (System.currentTimeMillis() - counterResetTime > COUNTER_RESET_TIME) {
					counterResetTime = System.currentTimeMillis();
					requestCounter.set(0);
				}
				if (requestCounter.get() > MAX_REQUESTS_PER_COUNT) {
					try {
						long sleepTime = COUNTER_RESET_TIME - (System.currentTimeMillis() - counterResetTime);
						Log.e("waitTooManyRequest", "sleep:" + sleepTime);
						Thread.sleep(Math.max(0, sleepTime));
						counterResetTime = System.currentTimeMillis();
						requestCounter.set(0);
					} catch (Exception x) {
						// nothing
					}
				}
				requestCounter.incrementAndGet();
			}
		}

		final VKRequest vkRequest;
		final VKRequestListener vkRequestListener;

		public VKRequestSync(VKRequest vkRequest, VKRequestListener vkRequestListener) {
			this.vkRequest = vkRequest;
			this.vkRequestListener = vkRequestListener;
		}

		@Override
		public void run() {
			waitTooManyRequest();
			vkRequest.executeSyncWithListener(vkRequestListener);
		}
	}
