### ISSUE TITLE
VKSdk.logout does not call onVKAccessTokenChanged

### ISSUE THREAD

**Issue by Gordakan** [VKCOM/vk-android-sdk#268]
When I logout from VK, I expect to the callback method `onVKAccessTokenChanged` from [VKAccessTokenTracker](https://github.com/VKCOM/vk-android-sdk/blob/master/vksdk_library/src/main/java/com/vk/sdk/VKAccessTokenTracker.java) to be called. 
This happens with the Facebook's sdk.

I was reading VK's source code and saw on line 467 of the VKSdk (logout method): 
`VKAccessToken.replaceToken(VKUIHelper.getApplicationContext(), null);`

As the method is clearly modifying the access token, it should call the callback method as well.

--> This should happen instead. 

```
VKAccessToken old = VKAccessToken.replaceToken(VKUIHelper.getApplicationContext(), null);
        if (old != null) {
            notifyVKTokenChanged(old, null);
        }
```

This way, we could have a mean to get a callback whenever a logout happens.

**Comment by spbisya** [comment]
Аналогичная проблема, vkAccessTokenTracker не триггерится при логауте и приходится ручками запускать MainActivity

**Comment by olegsm** [comment]
Please use new SDK version 2.0
