### ISSUE TITLE
Падение логина, если на телефоне установлено приложение VK com.vkontakte.android W/vk_sdk_auth: Auth not successful [fail]

### ISSUE THREAD

**Issue by norilsk** [VKCOM/vk-android-sdk#269]
При попытке залогиниться через VKSdk.login(getActivity(), MainActivity.vkScope), если на телефоне установлено приложение Вконтакте, падает ошибка.

В логе:

com.vkontakte.android W/vk_sdk_auth: Auth not successful [fail]: https://oauth.vk.com/blank.html#error=access_denied&error_reason=sdk_error&error_description=sdk options is undefined

В методе 
public void onError(VKError error) {...}
значение errorCode = -102

**Comment by GaidaiNikita** [comment]
Такая же проблема

**Comment by norilsk** [comment]
Проблема в том, что не было настроено "Название пакета для Android" в лично кабинете VK
