### ISSUE TITLE
проблема с запуском на реальном устройстве

### ISSUE THREAD

**Issue by Scorpio93** [VKCOM/vk-android-sdk#273]
Всем привет. написал небольшую программу по выводу списка друзей, на эмуляторе все работает отлично, а вот на реальном устройстве все время при запуске тут же бросает на onError(VKError error), никаких WebView не "вылазит", простите за глупость вопроса=)

**Comment by Dreddik** [comment]
А что в ошибке-то?

**Comment by Scorpio93** [comment]
VKError(Canceled) выдает, при этом нет вставки с авторизацией, ошибка вылетает сразу же при запуске

**Comment by Scorpio93** [comment]
при удалении оф приложения Вконтакте проблема пропадает, почему так происходит?это ради безопасности сделано?как их подружить?

**Comment by StacoNiK** [comment]
В настройках приложения на сайте вконтакте все правильно указано?

**Comment by Scorpio93** [comment]
какие именно настройки вы имеете ввиду?Это на Vk Dev в настройках?

**Comment by Scorpio93** [comment]
StacoNiK, огромное тебе спасибо!!!порылся в настройках приложения и обнаружил что не в ту графу указал главную активность.Теперь каждый раз при входе запрашивает разрешения доступа, как сделать что бы оно появлялось только при первом запуске?
