### ISSUE TITLE
Возможно ли пользоваться sdk, но указывая appId уже готового iframe-приложения?

### ISSUE THREAD

**Issue by ssergo** [VKCOM/vk-android-sdk#274]
Хотелось бы пользоваться авторизацией через официальное вк и получать всех друзей, которые играют в веб-приложение. Со standalone-приложением для андроида так не получается. Может, есть какие-нибудь обходные пути?

**Comment by Dreddik** [comment]
Вы хотите добавить мобильные клиенты или у вас игра на отдельном сайте?

**Comment by ssergo** [comment]
Добавить мобильные клиенты.

**Comment by Dreddik** [comment]
Тогда обратитесь в игровую поддержку в настройках приложения ВК, вам должны включить возможность добавить ваши standalone приложения

**Comment by ssergo** [comment]
Действительно, это помогло. Спасибо большое!
