### ISSUE TITLE
Push notification timestamp

### ISSUE THREAD

**Issue by lectricas** [VKCOM/vk-android-sdk#275]
Есть ли способ его получить? Мне приходится подставлять время девайса, а потом вы тут же присылаете мне историю в которой таймстамп есть...

**Comment by lectricas** [comment]
Какая вообще схема работы с датами? на messages.send вы тоже дату не присылаете

**Comment by lectricas** [comment]
Еще когда фотку отправляю приходит:
Bundle[{msg_id=267012, uid=273178150, text=[Photo], type=msg, badge=1, _genSrv=419529, sandbox=0, collapse_key=msg}]

А как выудить ссылку на фотку то?)

**Comment by lectricas** [comment]
@Dreddik  прием)

**Comment by lectricas** [comment]
@dkostryukov  может тут подскажешь как быть то? А то я буду всю историю тянуть на каждый пуш ведь!

**Comment by dkostryukov** [comment]
@lectricas дата не приходит в пуше, ее надо получить через апи, если дата нужна для сортировки сообщений, то лучше завязываться на id сообщений. При приходе пуша с фото нужно перезапросить по id сообщение или сделать синхронизацию лонгпола

**Comment by lectricas** [comment]
вот сложно вам в пуше линк на фото прислать и таймстамп. ррррр Хотя про сортировку по id мы не подумали конечно...

**Comment by dkostryukov** [comment]
@lectricas тут проблема в том, что хочется полный текст сообщения видеть, ссылки на вложения, даты и тд, однако размер пуша не безграничен, что печально, разумеется.

**Comment by lectricas** [comment]
а давайте перепилим вк и сделаем text ограниченной длинны :D 
спасибо, теперь понятно стало, буду доделывать.
