### ISSUE TITLE
Токен не меняется

### ISSUE THREAD

**Issue by fkzwd** [VKCOM/vk-android-sdk#276]
Кароче, есть две кнопки первая - авторизация:

---

```
    button.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            loggining();
        }
    });
```

//Метод Логининг, прописан в классе MainActivity

---

```
public void loggining(){
    VKSdk.login(this,scope);
}
```

---

Вторая - выводит тоаст с текущим токеном:

---

```
    button2.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            Toast.makeText(getApplicationContext(),VKAccessToken.currentToken().accessToken,Toast.LENGTH_LONG).show();
            System.out.println("[Acces_Token] = "+VKAccessToken.currentToken().accessToken);
        }
    });
```

---

В чем проблема:
Захожу в приложуху, жму кнопку Авторизация, ввожу логин пароль, разрешаю доступ. Вывожу токен - все нормально, пробный запрос - беру статус со своей страницы (метод "status.get")
Затем, с компа меняю пароль, естественно токен стал невалидным (допустим он был 123)
Статус со страницы следовательно не берется, вылазит ошибка 5.
Затем я опять жму на кнопку Авторизация (по сути токен должен измениться)
После неё жму на кнопку2, выводится тот же самый токен(123) а не новый(к примеру 321)
Статус не берется все равно, хотя авторbpовался разрешил доступ.
Но если убить процесс приложения и запустить заново то уже все работает, и токен другой высвечивает. Как сделать так чтоб не надо было перезапускать приложение

**Comment by lives4** [comment]
@Dreddik хелп
