### ISSUE TITLE
Не могу авторизоваться с Андроида

### ISSUE THREAD

**Issue by makushatnik** [VKCOM/vk-android-sdk#277]
Не получается авторизоваться. Использую метод customInitalize, для большей уверенности, как положено, integer AppId - 5547525.
debug-сертификат - 4D573E2C4CDD16235374D1C205AF7BDD49ABB046
С веб-интерфейса я авторизовался. Тогда почему я не могу авторизоваться методом 1 - используя SDK? И еще более не понятно, почему я не могу авторизоваться методом 2 - используя WebView c тем же Url, что и на десктопе (добавил ток параметр display=wap)?
Запрос:
http://oauth.vk.com/authorize?client_id=5547525&scope=audio,offline&redirect_uri=http://oauth.vk.com/blank.html&display=wap&response_type=token

**Comment by makushatnik** [comment]
Когда пытаюсь авторизоваться с помощью 1го метода - отдельная активность на это, создал синглетон класс, наследник Application, который может getContext(). В нем в onCreate, как положено customInitialize, a его самого создаю в AuthActivity onCreate, в которой рисую форму с полями ввода - логин, пароль. Важный момент - ошибок при создании НЕТ. Значит регистрируется с моим AppId.
А вот при вызове команды login, по кнопке Войти - приходит JSON - error - client_id не верный

**Comment by makushatnik** [comment]
Отдельно скажу о том, что все плохо задокументировано!!! Для новичка, который с этим АПИ не работал, не совсем понятно, что и как надо делать.. Скажем с АПИ Телеграм было проще разобраться и быстрее сделал работающее приложение под него.

**Comment by lectricas** [comment]
авторизация нормально работает вроде. Доки на это есть тоже. Используй VKsdk.login для авторизации. У тебя тут какие-то ссылки лютые непонятные)

**Comment by makushatnik** [comment]
Бред. 1. если ссылка "лютая", наберите и посмотрите что в ВЕБ-ИНТЕРФЕЙСЕ ОНА АВТОРИЗУЕТ!!! 2. эту ссылку не я придумал. Сделали регистрацию на oauth.vk.com - так доведите ее до конца!!! Чтобы можно было авторизоваться этим способом. 3. Я же написал, что VKSdk.login не работает!!! Скрины приложил. vkmusic2 - посмотрите, мне от вас пришел токен!!! vk_invalid_client - здесь возможно зря верстал эту форму, т.к. VKSdk. При открытии vk.customInitialize, при нажатии кнопки - vk.login - результат не очень хорошо виден в верней части формы, но он есть. Вот и скажите мне, что не так?

Могу отправить 2 активности, хочу чтобы я мог авторизоваться ЛЮБЫМ способом с Андроида. Но сам смысл в авторизации через веб-интерфейс (oauth), потому что этот способ всегда дает возможность набирать вручную логин и пароль.

![vk_invalid_access2](https://cloud.githubusercontent.com/assets/16035443/16926288/b61729bc-4d30-11e6-9415-b00e63d51401.jpg)
![vkmusic2](https://cloud.githubusercontent.com/assets/16035443/16926310/c9d2c272-4d30-11e6-9acf-931e2c06dea2.jpg)
![vk_invalid_client](https://cloud.githubusercontent.com/assets/16035443/16926338/ec89c662-4d30-11e6-9726-c76cc2057134.jpg)

**Comment by dkostryukov** [comment]
Попробуйте стандартный метод авторизации, без customInitialize и проверьте, что данные приложения заполнены на сайте правильно, пакет, подпись и тд

**Comment by AlexRU18** [comment]
А что насчёт авторизации через офф. приложение? Ведь пример выдаёт совсем не то, если офф приложение установлено

**Comment by spbisya** [comment]
Мб у тебя не standalone application?

**Comment by TikhonOsipov** [comment]
Была такая же ошибка, что только не перепроверял - и com_vk_sdk_AppId, который должен называться именно так и быть integer
И отпечатки сертификатов SHA1 (без двоеточий)
И название приложения в android:name в тэге application в манифесте
Но у меня не было VkSdk.initialize(this) в методе onCreate() класса Application, а это важно

Также хорошо иметь в манифесте VkServiceActivity
<activity
                android:name="com.vk.sdk.VKServiceActivity"
                android:label="ServiceActivity"
                android:theme="@style/VK.Transparent" />

После этого всё заработало
