### ISSUE TITLE
Повторное запрашивание прав доступа

### ISSUE THREAD

**Issue by Scorpio93** [VKCOM/vk-android-sdk#278]
Знаю этот вопрос уже был но я так и не смог с ним разобраться. Как убрать повторное запрашивание данных от вк при каждом входе в приложение?

**Comment by lectricas** [comment]
можно ссылку на "этот вопрос" который уже был?

**Comment by Scorpio93** [comment]
https://github.com/VKCOM/vk-android-sdk/issues/250

**Comment by dkostryukov** [comment]
@lectricas запрашивать должны каждый раз
