### ISSUE TITLE
Не проходит вход в сеть на android 3

### ISSUE THREAD

**Issue by ivanarh** [VKCOM/vk-android-sdk#279]
После выдачи прав приложению открывается следующий экран:
![bug](https://cloud.githubusercontent.com/assets/7873281/16911176/a3119ece-4ce5-11e6-9297-acd629adf170.png)
Баг проявляется только когда установлено приложение vkontakte на устройство.
Подтверждён на android 3.2.1 и 3.0.1. Я всё понимаю, что 3 версия уже очень редкая, но раз заявлена минимальная версия 2.3, извольте пофиксить.
На остальных версиях android, включая 2.3, проблемы не выявлено.
Проявляется на последней версии sdk на текущий момент (1.6.7)

Подозреваю, что баг как таковой не в SDK, а в приложении вконтакта:

`
                if (VKUtil.isAppInstalled(ctx, VK_APP_PACKAGE_ID)
                        && VKUtil.isIntentAvailable(ctx, VK_APP_AUTH_ACTION)
                        && fingerprints.length > 0
                        && fingerprints[0].equals(VK_APP_FINGERPRINT)) {
                    if (savedInstanceState == null) {
                        intent = new Intent(VK_APP_AUTH_ACTION, null);
                        intent.setPackage(VK_APP_PACKAGE_ID);
                        intent.putExtras(bundle);
                        startActivityForResult(intent, VKServiceType.Authorization.getOuterCode());
                    }
                } else {
                    new VKOpenAuthDialog().show(this, bundle, VKServiceType.Authorization.getOuterCode(), null);
                }
`

По этому коду видно, что если клиент вконтакта установлен, открывается Activity оттуда.

**Comment by dkostryukov** [comment]
Клиент VK больше не поддерживает версию 3.0, поэтому поправить данную проблему нет возможности

**Comment by ivanarh** [comment]
Тем не менее, на клиент с android 3 успешно устанавливается клиент vk, который имеет версию 3.6 (build 348). Возможно, не самая новая версия, но vk sdk её "видит" и пытается авторизоваться через неё.
Если клиент больше не поддерживает эту версию, почему тогда её установка возможна?  Получается, пользователь должен сделать выбор: или играть в игры с авторизацией в vk, или пользоваться клиентом vk, одновременно это делать не получится.

Возможные варианты решения проблемы:
Запрет установки клиента vk на android 3. Решается средствами google play.
Модификация vk sdk, чтобы на android 3 он даже не пытался авторизоваться через приложение vk.

**Comment by olegsm** [comment]
Версия vk клиента с старой версией не доступна в google play.
