### ISSUE TITLE
VKSCOPE.OFFLINE

### ISSUE THREAD

**Issue by vladlen2010** [VKCOM/vk-android-sdk#280]
Здравствуйте, хотел бы избавиться от строчки  "Доступ в любое время" при авторизации

 ArrayList<String> scopeList = new ArrayList<>(Arrays.asList(scope));
            if (!scopeList.contains(VKScope.OFFLINE)) {
                scopeList.add(VKScope.OFFLINE);

Зачем вы добавляете его по умолчанию так и не понял, моему приложению не требуется доступ в любое время!
Прошу вырезать его из реализации по умолчанию!

**Comment by olegsm** [comment]
Please use new SDK version 2.0
