### ISSUE TITLE
не понимаю как сформировать правильно request

### ISSUE THREAD

**Issue by Scorpio93** [VKCOM/vk-android-sdk#281]
Всем привет, помогите пожалуйста с запросами, хоть ты тресни не могу понять что и куда. Пытаюсь вывести список аудио юзера, но не выходит. 
VKRequest requestMusic = VKApi.audio().get(VKParameters.from(VKApiConst.FIELDS, "title", "artist"));
пытался делать запрос так.

**Comment by Scorpio93** [comment]
https://cloud.githubusercontent.com/assets/20298182/17173502/ea70bed8-5403-11e6-9904-142f2cd67c9f.PNG
скрин одержаного

**Comment by Scorpio93** [comment]
я так понимаю что в response я должен одержать VKApiAudio, который и содержит список?помогите, хоть ткните носом где пример посмотреть можно

**Comment by Dreddik** [comment]
Я точно не помню синтаксис, должно быть примерно так
```String[] fields = ["title", "artist"];
VKApi.audio().get(VKParameters.from(VKApiConst.FIELDS, fields));
```
