### ISSUE TITLE
VKSdk.login(Context, null) стал возвращать VKError

### ISSUE THREAD

**Issue by ArtemNeFRiT** [VKCOM/vk-android-sdk#282]
Пытаюсь залогиниться в приложении с помощью следующего кода в RegOfferActivity:
`VKSdk.login(RegOfferActivity.this, null);`
Но в onActivityResult срабатывает onError...
`@Override
public void onError(VKError error) {
Log.e("mylog","error = " +error.errorReason +" " +error.errorMessage);
}`
`E/mylog: error = null null`
И при этом никаких exception.

*
`vkAccessTokenTracker.startTracking();
VKSdk.initialize(this);` 
вызываются в моем классе Application

**Comment by ArtemNeFRiT** [comment]
Исправилось после переустановки офф. приложения Vk

**Comment by olegsm** [comment]
can't reproduce
