### ISSUE TITLE
Authorization code flow

### ISSUE THREAD

**Issue by AnatoliyS** [VKCOM/vk-android-sdk#283]
Здравствуйте! Хотел бы узнать, почему в SDK нет возможности для Authorization code flow (авторизация сервера) использовать активити из приложения Вконтакте вместо WebView? Может быть есть что-то важное, что я упускаю.

Почему это нужно? Дело в том, что вводить логин и пароль от вк в чужое приложение - это очень плохой user-experience. Человек может совсем отказаться от приложения из-за того, что не доверяет ему такие данные.

Если же использовать sdk в таком виде, как есть, то выходит, что мы всю логику по работе с ВК переносим с сервера на клиент. Что, как мне кажется, архитектурно не удачное решение. Хотелось бы всю логику работы с данными иметь на сервере.

**Comment by olegsm** [comment]
Please use new SDK version 2.0
