### ISSUE TITLE
Как убедиться в подлинности пользователя?

### ISSUE THREAD

**Issue by ArtemNeFRiT** [VKCOM/vk-android-sdk#284]
В моем клиентском приложении используется следующая схема:
- Пользователь указывает email, получает письмо на почту с ссылкой, пройдя по которой попадает в таблицу подтвержденных и получает некий token, используя который, может совершать запросы, которые не сработают для обычного пользователя. 

Однако, решил подключить авторизацию при помощи VK. Возник вопрос - как можно удостовериться со стороны сервера в том, что пользователь подлинный? 
То, что у меня уже есть: app_id (статичный), secret_key (статичный), user_id (у каждого пользователя Vk свой) и access_token (динамичный), который выдается при авторизации в приложении.

Задача в том, чтобы на стороне сервера определить, что пользователь действительно существует и удостовериться в его подлинности, чтобы получить доступ до полного функционала нельзя было каким-либо обычным запросом на сервер. В документации Vk SDK нашел только это:
- Для проверки авторизации Вы можете использовать полученный параметр hash, сравнив его с md5 подписью от app_id+user_id+secret_key, например md5(194253766748fTanppCrNSeuYPbA4ENCo). 

Но где взять тогда этот самый hash на клиенте?

**Comment by AnatoliyS** [comment]
Насколько я понимаю, можно использовать для проверки метод checkToken:
https://new.vk.com/dev/secure.checkToken

То есть необходимо вначале авторизировать сервер (получить специальный токен для сервера), и затем сервер сможет проверять ваш динамичный токен, который ему передается от приложения.

**Comment by ArtemNeFRiT** [comment]
> Насколько я понимаю, можно использовать для проверки метод checkToken:
https://new.vk.com/dev/secure.checkToken

Да, поискав подобные вопросы в интернете, решил остановиться именно на таком варианте подтверждения юзеров. Спасибо!

**Comment by ArtemMikhaylov** [comment]
> Насколько я понимаю, можно использовать для проверки метод checkToken:
https://new.vk.com/dev/secure.checkToken

Меня вот смущает описание этого метода:

> Checks the user authentification in IFrame and Flash apps using the access_token parameter

Сказано об IFrame and Flash apps , но не упомянуто standalone app.  Этот метод можно применять если токен получен нативным android приложением через vk-android-sdk ?  работает?
