### ISSUE TITLE
не работают параметры запроса

### ISSUE THREAD

**Issue by Scorpio93** [VKCOM/vk-android-sdk#289]
VKApi.audio().getRecommendations(VKParameters.from(VKApiConst.COUNT, 100));
по идее должно возвращать 100 песен, но на практике возвращает каждый раз по разному. Направьте на путь истинный пожалуйста

**Comment by samarjan92** [comment]
Заметил такое же странное поведение при запросе треков пользователя, возвращает не все песни, хотя оффициальное приложение ВК получает полный список. Проверил с помощью Charles

**Comment by Scorpio93** [comment]
у меня в вк около 600 песен, видит только 440, так что соглашусь, за рекомендованное так ничего и не решил, иногда даже ничего не возвращает, такие дела((

**Comment by samarjan92** [comment]
Я думаю с проблема с рекомендоваными и с "Мои аудиозаписи" имеет схожие корни, как мне ответила поддержка ВК это связанно с требованием правообладателей, но почему бы не выдавать их тоже, но помечать как недоступные

**Comment by olegsm** [comment]
Please use new SDK version 2.0
