### ISSUE TITLE
error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light'.

### ISSUE THREAD

**Issue by gazel128** [VKCOM/vk-android-sdk#29]
styles.xml
error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light'.

**Comment by trinadhkoya** [comment]
error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light'.

**Comment by sarathkumar14** [comment]
this is the error due to r.java file can not create well
