### ISSUE TITLE
login error: invalid_client

### ISSUE THREAD

**Issue by Stepus** [VKCOM/vk-android-sdk#290]
Hello,

We have problem with vk.com login in app Kalorické tabulky (https://play.google.com/store/apps/details?id=cz.psc...)

Sometimes when user tries to login to vk.com via android application with your sdk, login dialog doesnt appear. Small black error message appears instead. It says {"error":"invalid_client","error_description":"client_id is incorrect"}.

But the application is still the same. Nor package name nor signing key changed. It occurs only at some devices. Otherwise the login works well.

Can you please tell me, where could be problem?

Thanks a lot,
Best regards,

Stepan Moravcik

stepan.moravcik@aspamobile.cz

**Comment by olegsm** [comment]
Old version doesn't support now, use 2.0.+ version.
