### ISSUE TITLE
audio.get возвращает не все аудиозаписи

### ISSUE THREAD

**Issue by nightmare00** [VKCOM/vk-android-sdk#295]
Привет. Делаю такой запрос:
`loadAudioRequest = new VKRequest("audio.get", VKParameters.from(VKApiConst.OFFSET, Integer.toString(0)));`
Получаю не все песни, которые есть у пользователя.
Пример для конкретного пользователя: https://vk.com/audios10605907
Через vk-android-sdk 'Space Oddity 1969' в выдаче не будет (самая верхняя песня в списке). 
При этом через api console и на сайте в выдаче есть все песни.
Из-за чего такое происходит?

**Comment by nukede** [comment]
Некоторые записи по просьбе правообладателей доступны только в веб-версии и официальных приложениях.

**Comment by R00We** [comment]
http://kommersant.ru/doc/3082168

**Comment by serg-z** [comment]
Могли хотя бы всё кроме ссылки на mp3 оставить.

**Comment by glebsigal** [comment]
или хотя бы ссылки на id аудиозаписей
