### ISSUE TITLE
Как запостить .gif с телефона на свою стену?

### ISSUE THREAD

**Issue by dezarion** [VKCOM/vk-android-sdk#296]
`VKApiDocs docs = new VKApiDocs();
      VKRequest uploadWallServerRequest = docs.uploadWallDocRequest(file);
      uploadWallServerRequest.executeWithListener(new VKRequestListener() {
        @Override
        public void onComplete(VKResponse response) {
          super.onComplete(response);
      });`

Использую такой код. Метод uploadWallDocRequest инкапсулирует в себе запрос за url сервера, загрузку документа и его сохранение. После его успешного выполнения я ожидаю, что документ (гифка) появится у меня на стене. Однако, документ лишь появляется у меня в списке документов. Как запостить гифку на стену сразу?

**Comment by olegsm** [comment]
Please use new SDK version 2.0
