### ISSUE TITLE
Как вернуть обложки альбомов?

### ISSUE THREAD

**Issue by mashazavolnyuk** [VKCOM/vk-android-sdk#297]
Ребята,я не понимаю,как должен выглядить запрос,чтобы возвращались обложки загружаемых альбомов? Плюс мне нужно вернуть потом по каждому альбому фотки,которые он содержит. Помогите пожалуста. С какими данными надо работать?
 VKRequest albums = new VKRequest("photos.getAlbums",
                VKParameters.from(VKApiConst.ALBUM_ID,));
в костантах я не наешла need_covers(как написано в документации)

**Comment by olegsm** [comment]
Please, use new version 2.0.+
