### ISSUE TITLE
token is incorect

### ISSUE THREAD

**Issue by rikudoxx** [VKCOM/vk-android-sdk#301]
Здравствуйте! Подключил андроид сдк как указано в инструкции, но возникает такая проблема, что когда человек запускает приложение на устройстве где есть другие приложения связанные с вк и пытается залогинится то выдает белое окно с ошибкой о некоректном токене. Как быть?

**Comment by amaksoft** [comment]
Поздно отвечаю, но надеюсь поможет тем кто еще столкнется.
Авторизация при установленном приложении ВК происходит через их activity, при отсутствии приложения - через открытие страницы авторизации на сайте в webView.
При авторизации через приложение ВК проверяется **имя пакета вашего приложения** и  **ПОЛНОЕ имя класса main activity** Вашего приложения на соотвествие с тем, которое указано Вами в разделе для разработчика.
Поверяется оно путем генерации токена на основе вышеуказанной информации, а так же ключа, которым подписано приложение и id авторизованного пользователя (если он есть) и отправке его в составе запроса. В случае если токен некорректный, Вы получаете ответ: `{"error": "invalid_token", "error_description":"token is incorrect"} `

Поэтому внимательно проверяйте:

- **fingerprint ключа**, которым подписано приложение
- **имя пакета** Вашего приложения
- **полное** имя класса Main Activity Вашего приложения

Сам разработчиком ВК или этой либы не являюсь, просто у нас в приложении такая же ошибка возникала из-за того что указали simpleName класса MainActivity вместо полного. Причем как раз только когда есть само приложения ВК и есть авторизованный пользователь. В остальных случаях все работало корректно.

**Comment by rikudoxx** [comment]
Большое вам спасибо за ответ!

18.10.2016 10:10 пользователь "Andrey Makeev" <notifications@github.com>
написал:

**Comment by rikudoxx** [comment]
Не могли бы вы уточнить полное имя класа мейн активити. Какое оно на
примере может быть? У нас в приложении есть экран заставки после чего
основное активити. Как быть в этой ситуации?

18.10.2016 12:38 пользователь "Andrey Galunec" <galunecandrey@gmail.com>
написал:

Большое вам спасибо за ответ!

18.10.2016 10:10 пользователь "Andrey Makeev" <notifications@github.com>
написал:

Поздно отвечаю, но надеюсь поможет тем кто еще столкнется.

**Comment by amaksoft** [comment]
Точно из кода библиотеки я не понял, но скорее всего что это должна быть основная активити Вашего приложения, или (возможно) та, от которой отправляем запрос на авторизацию. У меня в приложении это была одна и та же.
О существовании какой-либо другой активити внешнее приложение нормальными путями узнать не может.
