### ISSUE TITLE
 Метод VKApi.users().get() возвращает не правилный аватар

### ISSUE THREAD

**Issue by petrovichtim** [VKCOM/vk-android-sdk#302]
Добрый день.
Делаю запрос
`if (VKSdk.isLoggedIn())
            VKApi.users().get().executeWithListener(new VKRequest.VKRequestListener() {
                @Override
                public void onComplete(VKResponse response) {
                    VKApiUser user = ((VKList<VKApiUser>) response.parsedModel).get(0);
                    Glide.with(getApplicationContext())
                            .load(user.photo_200)
                            .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                            .into(userImageView);
                    userHeader.setText(user.first_name + " " + user.last_name);

```
            }
        });`
```

В поле user.photo_200 приходит ссылка http://vk.com/images/camera_b.gif
И на все остальные фотографии ссылка та же.
Прошу помочь.

**Comment by petrovichtim** [comment]
Победил вот так
`VKApi.users().get(VKParameters.from(VKApiConst.FIELDS, "photo_50, photo_100, photo_200")).executeWithListener(new VKRequest.VKRequestListener() {
                @Override
                public void onComplete(VKResponse response) {
                    VKApiUser user = ((VKList<VKApiUser>) response.parsedModel).get(0);
                    // ищем самое большое изображение
                    String photo = null;
                    if (!user.photo_200.equals("http://vk.com/images/camera_a.gif"))
                        photo = user.photo_200;
                    else if (!user.photo_100.equals("http://vk.com/images/camera_b.gif"))
                        photo = user.photo_100;
                    else
                        photo = user.photo_50;

                    Glide.with(getApplicationContext())
                            .load(photo)
                            .diskCacheStrategy(DiskCacheStrategy.SOURCE)
                            .into(userImageView);
                    userHeader.setText(user.first_name + " " + user.last_name);

                }
            });`

**Comment by olegsm** [comment]
Old version doesn't support now, use 2.0.+ version.
