### ISSUE TITLE
wall.get()

### ISSUE THREAD

**Issue by koverko-developer** [VKCOM/vk-android-sdk#303]
Здравствуйте. Делаю вот такой запрос: VKRequest request = VKApi.wall().get(VKParameters.from(VKApiConst.OWNER_ID, VKAccessToken.currentToken().userId, VKApiConst.COUNT, 15, VKApiConst.EXTENDED, 1));
        request.executeWithListener(new VKRequest.VKRequestListener() {}
Как мне правильно получить данные о постах: title, text, photo_604, imf_scr, col_likes.

**Comment by olegsm** [comment]
Please, use new version 2.0.+
