### ISSUE TITLE
Авторизация и хранение токенов

### ISSUE THREAD

**Issue by mr-cpp** [VKCOM/vk-android-sdk#306]
Уважаемые разработчики! Прошу обратить внимание на эту статью:
https://habrahabr.ru/post/313132/
Подумайте о шифровании токенов и об авторизации пользователя

**Comment by dkostryukov** [comment]
Добрый день, @mr-cpp . Подробно изучили Вашу статью и осталось непонятно две вещи.
1) Если зашифровать токен, то где хранить ключ к шифрованию этого токена. Получается, что точно так же в открытом виде? Тогда каким образом это обеспечит безопасность, злоумышленник просто найдет ключ и дешифрует токен.
2) Каким образом запрет показа WebView спасет от злоумышленников, которые могут показать фишинговую страницу или сверстать Activity, которая будет в точности повторять Activity офф приложения? Внедрение SDK подразумевает, что оно может проверить официальное приложение, которое установлено на телефоне, Вы, как разработчик стороннего приложения, можете быть уверены, что по запросу на авторизацию не откроется фишинговое приложение через используемое SDK
