### ISSUE TITLE
Unable Login user if the user has VK application (Did you even test your SDK or backend?)

### ISSUE THREAD

**Issue by vladimirarevshatyan** [VKCOM/vk-android-sdk#307]
Good day VK,i am facing really serious issue,due to which i am not able to login any user in the whole world who has your VK application installed (you HAVE to be more carefull to your SDK when you release a login API).So here is the issue.Whenever i login user,in the case if user do not have application of VK isntalled,the login goes falwlessly and perfect,but in case when a user has an application of VK isntalled onto the phone,the application throws a json error saying that the fingerprint of sdk is incorrect....I have checked 1000 times that everything is set up on my VK application developer page,and plus if it was the fingerprint error,the dialog of the login (at the point when user do not installed any VK application) the login process would not proceed,but without VK application,the login do happen,but it is throwing the above error when VK application installed,did you ven test your SDK before release?I DOUBT THAT!

**Comment by olegsm** [comment]
Old version doesn't support now, use 2.0.+ version.
