### ISSUE TITLE
Ошибка при использовании VKShareDialogBuilder 

### ISSUE THREAD

**Issue by AlimovAndrey** [VKCOM/vk-android-sdk#308]
Пытаюсь совершить пост на стену через VKShareDialogBuilder:

VKShareDialogBuilder builder = new VKShareDialogBuilder();
        builder.setText("text here");
        builder.setAttachmentImages(new VKUploadImage[]{
                new VKUploadImage(bitmap, VKImageParameters.pngImage())
        });
        builder.setAttachmentLink("title", "https://vk.com");
        builder.setShareDialogListener(new VKShareDialog.VKShareDialogListener() {
            public void onVkShareComplete(int postId) {
                Log.d(TAG, "Success");
            }

```
        public void onVkShareCancel() {
            Log.d(TAG, "Cancel");
        }

        @Override
        public void onVkShareError(VKError error) {
            Log.e(TAG, error.toString());
         }
    });
}
builder.show(getSupportFragmentManager(), "VK_SHARE_DIALOG");
```

Получаю: VKError (API errorVKError (code: 15; ; Access denied: no access to call this method))
Хотя при авторизации запрашивал : String[] scope = new String[] { VKScope.WALL, VKScope.EMAIL };

В чем может быть проблема?

**Comment by olegsm** [comment]
Old version doesn't support now, use 2.0.+ version.

**Comment by Maksim-Novikov** [comment]
Где в версии 2.0 этот диалог?
