### ISSUE TITLE
SDK shows error dialog with system description

### ISSUE THREAD

**Issue by Dimdron** [VKCOM/vk-android-sdk#311]
### SDK shows dialog with not user friendly error when user try to sign in via VK without internet connection.

Step to reproduce:
1. Take device without VK application.
2. Turn off internet connection.
3. Try to sign in with VK.

**Expected result**: SDK return error in application or something like this.
**Actual result:** SDK show dialog with "net::ERR_NAME_NOT_RESOLVED" message.

![screenshot](http://i.piccy.info/i9/acec7de8d55e5b8881a54ef82552ef43/1479376396/42818/1090608/Screenshot_2016_11_15_22_38_00.png)

**Comment by Dimdron** [comment]
#312

**Comment by olegsm** [comment]
Old version doesn't support now, use 2.0.+ version.
