### ISSUE TITLE
sdk fingerprint is incorrect

### ISSUE THREAD

**Issue by gl00k** [VKCOM/vk-android-sdk#313]
Проблема в том, что на маркете закинута бета версия на которой вылазит эта ошибка, но этот же билд, подписанный тем же ключом, но не скачанный с маркета, а закинутый на прямую в телефон - работает!? как такое возможно?) спасибо. SHA1 указан без двоеточия 
Что это может быть?) Спасибо.

**Comment by AlimovAndrey** [comment]
Ты используешь разные отпечатки сертификата для дебаг и релизной версии?
Если нет, добавь еще один в настройках приложения на странице вк приложений.

**Comment by gl00k** [comment]
В консоле указаны 2 ключа и дебаг и релиз. Дебаг билд работает, релиз билд тоже работает но только не скачанный с маркета) возможно это из-за того что прилож в маркете в бете стоит? может как то нужно регистрировать приложение которое находится в маркете?) вообщем я уже все перепробовал, еще попробую прилож перекинуть на альфа тест может все образумится)

**Comment by AlimovAndrey** [comment]
Тогда ждем официального ответа...

**Comment by gl00k** [comment]
Перенес на альфу и все заработало) странно это все как-то))

**Comment by necessitudo** [comment]
Привет! Такая же проблема! Не нашел случайно решения?

**Comment by sergey19941201** [comment]
Ну что? Есть решение? Все как у  @gl00k. Только альфу не пробовал. Будет ли работать в стабилке?

**Comment by sergey19941201** [comment]
консоль google play -> управление релизом -> подписи приложений.
Оттуда перенес все ключи в консоль ВКшника и вроде как работает.
[(https://ru.stackoverflow.com/questions/594176/ВК-api-sdk-android-sdk-fingerprint-is-incorrect)]

Еще можно попробовать получить фингерпринт прямо в запущеном приложении с помощью String[] fingerprints = VKUtil.getCertificateFingerprint(this, this.getPackageName()); и добавидь в консоль ВК
[https://github.com/VKCOM/vk-android-sdk/issues/231]

**Comment by TemMax** [comment]
@sergey19941201 в ридми есть вариант получения отпечатка через студию. Как по мне — самый удобный вариант.
