### ISSUE TITLE
Как правильно получать новые записи со стены ?

### ISSUE THREAD

**Issue by Pahanuch** [VKCOM/vk-android-sdk#314]
Добрый день. Подскажите, как правильно получать новые записи со стены пользователя. При скролинге вниз подгружаются старые записи (используем **VKApiConst.OFFSET** и **VKApiConst.COUNT**) . При PullToRefresh нужно добавлять новые записи в начало списка, если таковы имеются. Сначала думал использовать какой - то параметр **START_TIME** (Время добавления поста на стену). То есть брать последнюю дату и время добавления записи из списка и подгружать все записи, что временем младше, но для метода _wall.get_  не вижу  **START_TIME**. Спасибо!

**Comment by dkostryukov** [comment]
@Pahanuch логичнее всего было бы при pull to refresh удалять списак закэшированных постов и грузить заново с первого с последующей пагинацией. Потому что если вы будете добавлять новые записи, может возникнуть ситуация, что какой-то пост был удален, а у вас после refresh он останется.
