### ISSUE TITLE
не срабатывает likes.delete

### ISSUE THREAD

**Issue by kvk555** [VKCOM/vk-android-sdk#317]
VKRequest request = new VKRequest("likes.delete", VKParameters.from("type", "photo", "item_id", id); - не удаляет (отрабатывает без ошибок, но ничего не меняется)
VKRequest request = new VKRequest("likes.delete", VKParameters.from("type", "video", "item_id", id)); - выдает ошибку 100 (Один из необходимых параметров был не передан или неверен) 
В чем может быть причина?
Спасибо!

**Comment by dkostryukov** [comment]
@kvk555 а через сайт работает запрос с текущими параметрами? https://vk.com/dev/likes.delete возможно не указан owner_id?

**Comment by kvk555** [comment]
не работает, и запрос с типом video сразу в error 100 отправляет

**Comment by dkostryukov** [comment]
@kvk555 пришлите, пожалуйста весь фрагмент кода с id фото, лайк с которых вы удаляете и id приложения

**Comment by olegsm** [comment]
Please use new SDK 2.0 version.
