### ISSUE TITLE
Нету в VKApiConst LINK, POOL, AUDIO

### ISSUE THREAD

**Issue by sviter-pro** [VKCOM/vk-android-sdk#318]
Хочу распарсить вложения от типа данных

for (VKAttachments.VKApiAttachment attachment : p.attachments) {
    switch (attachment.getType()){
        case VKApiConst.PHOTO:

Вот PHOTO: есть в VKApiConst, а всех остальных нет, к примеру: LINK, POOL, AUDIO
как быть?

**Comment by dkostryukov** [comment]
@sviter-pro если отсутствуют какие-то константы в VKApiConst, вы можете написать из строками в switch
