### ISSUE TITLE
Запрос photos.search, присутствуют не все поля в VKResponse.parsedModel

### ISSUE THREAD

**Issue by OM-3kChcBjgFR2COfP** [VKCOM/vk-android-sdk#319]
Привет!

Код:

VKRequest request = new VKRequest("photos.search", ... );

request.executeWithListener(new VKRequest.VKRequestListener() {

            @Override
            public void onComplete(VKResponse response) {

                super.onComplete(response);
                
                VKPhotoArray list = (VKPhotoArray) response.parsedModel;

                for(VKApiPhoto photo : list){

                         в объекте photo имеются не все поля, необходимые мне, а именно lat и long, которые присутствуют в response.responseString.

                }

})

**Comment by dkostryukov** [comment]
@OM-3kChcBjgFR2COfP если существуют какие-либо поля, которые не поддержаны в VKApiPhoto, Вы можете распарсить их сами.

**Comment by OM-3kChcBjgFR2COfP** [comment]
Друзья, разработчик не хочет или не может поддерживать библиотеку.
Да, сейчас я сам парсю ответ на предмет нужных полей. Но я думаю, что раз уж подключил стороннюю библиотеку, то пусть она выполняет поставленные задачи?
