### ISSUE TITLE
window with invalid_token message while authorization when user tap "Запретить доступ к Email"

### ISSUE THREAD

**Issue by timurchan** [VKCOM/vk-android-sdk#320]
помогите пожалуйста разобраться.
1) на устройстве стоит приложение VK, при авторизации показывается окно логина из SDK
2) во время логина запрашивался доступ на email
3) если юзер нажимает Разрешить - все срабатывает отлично
4) если юзер нажимает  "Запретить доступ к Email" перед нажатием Отмена/Разрешить - еще до того, как управление вернулось в onActivityResult в мое приложение появляется окно с белым фоном и единственной надписью:
{"error":"invalid_token", "error_description":"Token is incorrect"}
я нашел похожий issue 101 - но там ответа не прозвучало.

Очень подводить при регистрации пользователей. Очень жду вашего ответа.
Заранее спасибо.
![toker_error](https://cloud.githubusercontent.com/assets/6073330/21361235/3486496c-c6f4-11e6-99a2-bc7f27fd67c1.jpg)

**Comment by timurchan** [comment]
проявлялось у разных аккаунтов - на разных девайсах
особое непонимание вызывает то, что окно показывается до того, как управление вернулось в мою программу

**Comment by dkostryukov** [comment]
@timurchan проблему поправили
