### ISSUE TITLE
возможно ли скачивать изображения через эту библиотеку?

### ISSUE THREAD

**Issue by aleks4560** [VKCOM/vk-android-sdk#321]
В документации описаны примеры загрузки файлов на сервер. Есть ли какие-нибудь методы для их скачивания (в частности изображений, чтобы их можно было отобразить в ImageView) в вашей библиотеке для аndroid? Или придется пользоваться дополнительной библиотекой для работы с интернетом?

**Comment by dkostryukov** [comment]
@aleks4560 надо пользоваться дополнительными инструментами, получив url картинки из sdk

**Comment by aleks4560** [comment]
Код, после выполнения запроса через executeWithListener, выполняется не дожидаясь получения результата запроса. Во всех примерах вывод результата на экран приложения производится вызовом методов класса, из которого был вызван executeWithListener, в переопределении методов VKRequest.VKRequestListener. Вообще говоря, это не очень удобно... При использовании того же Retrofit'а код может выполняться в пределах одного метода без вызова дополнительных.
Короче говоря, есть ли способ после вызова executeWithListener обработать результат в том методе, из которого executeWithListener был вызван?
