### ISSUE TITLE
не приходять push-уведомления Android/Firebase

### ISSUE THREAD

**Issue by vitoksmile** [VKCOM/vk-android-sdk#323]
VKSdk.customInitialize(context, appId, "5.60");

JSONObject settings = new JSONObject();
settings.put("msg", "on");

VKRequest vkRequest = new VKRequest("account.registerDevice", VKParameters.from(
                VKApiConst.ACCESS_TOKEN, VKAccessToken.currentToken().accessToken,
                "token", FirebaseInstanceId.getInstance().getToken(),
                "device_model", Build.MODEL,
                "system_version", Build.VERSION.SDK_INT,
                "device_id", Settings.Secure.getString(context.getContentResolver(), Settings.Secure.ANDROID_ID),
                "settings", settings
        ));
        vkRequest.executeWithListener(new VKRequest.VKRequestListener() {
            @Override
            public void onComplete(VKResponse response) {
                      // и ответ {"response":1}
            }
        });

Но уведомления не приходят

**Comment by vitoksmile** [comment]
уже все приходит, проблема у настройках приложения

**Comment by Le0Michine** [comment]
@vitoksmile а что именно было не так? Тоже ничего не приходит, хотя настройки вроде верные

**Comment by vitoksmile** [comment]
ключ от firebase в приложение неверно задал

**Comment by Le0Michine** [comment]
@vitoksmile simple API key?
А брал его в итоге со страницы настроек проекта в firebase?

Project Id оттуда же?

**Comment by vitoksmile** [comment]
да, но сначала не работало и потом вдруг начало

**Comment by Le0Michine** [comment]
@vitoksmile а в самом firebase как то можно увидеть что работает? 

Project Id на странице проекта один, там же написано, что он в URL есть, но в урле другой, у тебя  так же?

**Comment by vitoksmile** [comment]
я уже не работаю с проектом, не могу сказать

**Comment by Le0Michine** [comment]
@vitoksmile спасибо!
