### ISSUE TITLE
Batch request

### ISSUE THREAD

**Issue by orcchg** [VKCOM/vk-android-sdk#324]
Dear developers:

I'm examining the source code of VKBatchRequest.java [https://github.com/VKCOM/vk-android-sdk/blob/25a694ede91a2bed675a28671fe3d61b2bd6d430/vksdk_library/src/main/java/com/vk/sdk/api/VKBatchRequest.java](url)

Don't you think this implementation is quite strange, do you?
Each time an error occurs during execution of single VKRequest, VKBatchRequest#provideError() internal method is called, and there onError() callbacks are called for each VKRequest in a loop, even for those request, which have not performed by the moment. So, we just fire onError() for all requests whether it has just occurred on a single request. How could we distinguish succeeded and failed requests?

Same strange implementation regards to VKBatchRequest#provideResponse() internal method as well. Here we just ignore to fire onComplete() callback when a single request finishes, because there is no all responses collected:

`for (VKResponse resp : mResponses) {
            if (resp == null) return;
        }`

But when all responses are collected, we just fire onComplete() callback for each requests in a loop, all at once, simultaneously. Despite each request could finish at different points of time. This is not convenient behaviour.

**Comment by orcchg** [comment]
По-русски:

В коде VKBatchRequest странная реализация:

В случае ошибки на любом VKRequest срабатывает метод VKBatchRequest#provideError(), в котором происходит цикл ПО ВСЕМ имеющимся VKRequest, независимо от того, какие из них вообще успели выполниться, какие завершились успехом или ошибкой. В этом цикле вызывается onError(). Понять, на каком запросе возникла ошибка - невозможно. И почему вообще ошибка на одном влечет вызов коллбека onError() на всех?

В случае успеха реализация такая же: при успехе на любом из VKRequest срабатывает метод VKBatchRequest#provideResponse(), в котором сначала ничего не делается, покуда все запросы не завершатся успехов, о чем намекает цикл:

`for (VKResponse resp : mResponses) {
            if (resp == null) return;
        }`

Зато потом, когда ВСЕ запросы отработают с успехом (и НИ ОДИН не завершится ошибкой) - вот тогда в цикле сработает коллбек onComplete() сразу на каждом отдельном запросе. Понять, что какой-то запрос завершился успехом или ошибкой, ОТДЕЛЬНО от остальных, никак не возможно.

**Comment by olegsm** [comment]
Please use new SDK version 2.0
