### ISSUE TITLE
Требует maven_push.gradle при установке vksdk_library

### ISSUE THREAD

**Issue by CoolMind** [VKCOM/vk-android-sdk#325]
Здравствуйте!
Версия библиотеки 1.6.7 или 1.6.8.
Пытаюсь установить vksdk_library. Скачал из репозитория проект, дальше в настройках проекта Android Studio (Project structure, New module) добавляю его (указываю путь к папке). Начинаются традиционные импорт, синхронизация Gradle. Выдаёт ошибку, что не найден файл `maven_push.gradle`. Копирую его из библиотеки в корень проекта. Дальше выдаёт другую ошибку:
`Error:Could not find method isReleaseBuild() for arguments [] on project ':vksdk_library' of type org.gradle.api.Project.`.
Решается нахождением build.gradle модуля vksdk_library и комментированием последней строки:
//apply from: '../maven_push.gradle'
А зачем вы всё так усложнили? Ведь во многих проектах обычно достаточно было бы сделать что-то типа:
compile 'com.vk:androidsdk:1.6.8'.

**Comment by dkostryukov** [comment]
@CoolMind а так не работает у вас compile 'com.vk:androidsdk:1.6.8' ?

**Comment by CoolMind** [comment]
@dkostryukov, решил сначала сделать по инструкции, но попробую и ваш вариант.
