### ISSUE TITLE
VKSdk.initialize(Context) must be call from Application#onCreate()

### ISSUE THREAD

**Issue by CoolMind** [VKCOM/vk-android-sdk#326]
Делаю инициализацию VK SDK в стартовой активности. Читаю в https://vk.com/dev/android_sdk?f=3.1.%2B%D0%98%D0%BD%D0%B8%D1%86%D0%B8%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F%2BSDK:

> Необходимо инициализировать SDK при запуске приложения следующим методом, лучше всего это делать в методе onCreate Вашего Application

Пишу:
`VKSdk.initialize(getApplicationContext());`

Всё бы ничего, но выдаёт ошибку:

> java.lang.RuntimeException: VKSdk.initialize(Context) must be call from Application#onCreate()

Чем плоха стартовая активность?

**Comment by vitoksmile** [comment]
необхідно створити клас MyApplication extended android.app.Application і у методі onCreate виконати VKSdk.initialize(this). Також у маніфесті треба прописати MyApplication

**Comment by CoolMind** [comment]
Да, я понимаю, так и сделал, но это первый случай, когда именно требуют всё делать в MyApplication (это при том, что в документации не обязывают). Т.е. это, видимо, баг.

**Comment by iamtodor** [comment]
@CoolMind @vitoksmile как workaround я могу предложить сделать свой форк сдк и удалить проверку: 
```java
 if (!(ctx instanceof Application)) {
            if (ctx == null) {
                throw new NullPointerException("Application context cannot be null");
            } else {
                throw new RuntimeException("VKSdk.initialize(Context) must be call from Application#onCreate()");
            }
}
```
Я изменения поведения не увидел. Все работало так же.
Вы выполняете все действия на свой страх и риск :)

**Comment by dkostryukov** [comment]
@CoolMind @iamtodor @vitoksmile Вызов VKSdk.initialize(this) в Application#onCreate не баг, а необходимость, так как, учитывая сложные жизненные циклы приложений, использующих sdk, могут возникнуть ситуации, когда sdk не проинициализирован. Для удобства и безопасности работы было введено это ограничение. Если подход с Application категорически вам не подходит, есть метод VKSdk.customInitialize(this) , его вы можете использовать на свой страх и риск без дополнительных форков

**Comment by iamtodor** [comment]
@dkostryukov не буду спорить касательно сложности-легкости жизненного цикла, но метод `VKSdk.customInitialize(this)` не описан вообще ничего. Я о нем ничего не смог нагуглить, хотя в репе все таки поиском нашел.

**Comment by CoolMind** [comment]
@dkostryukov, хорошо, тогда следует исправить документацию.
Видимо, в жизненном цикле действительно есть какой-то баг. Может быть, при уничтожении главной активности? Потому как недавно обнаружил, что у Facebook такого ограничения нет, но есть упоминание в одной из аналогичных http://stackoverflow.com/questions/29305232/facebook-sdk-4-for-android-how-to-log-out-programmatically статей о том, что перед любым вызовом API следует выполнять FacebookSdk.sdkInitialize(getApplicationContext());

**Comment by CoolMind** [comment]
Действительно, в Android есть ситуация, когда текущая активность может после простоя в фоне разрушиться. При этом если инициализация singleton'ов выполнялась в другой активности, то заново она проходить не будет. В этом случае всё приложение упадёт.
