### ISSUE TITLE
Получение push-up уведомлений через FCM.

### ISSUE THREAD

**Issue by ghost** [VKCOM/vk-android-sdk#329]
Всем доброго времени суток. Заступорился с уведомлениями на андроид. Т.к. в инэте вся документация под GCM, в кабинете для разработчиков от вк абсолютно нет никакой документации, а GCM плавно поменяли на FCM, то никак не могу разобраться, как же получать сообщения. Все настроил правильно. Отправляю все необходимые параметры с последней версией апи, settings и т.д., возвращается "успех", но вот по документации Firebase ничего не приходит кроме уведомлений самого Firebase'а. Help!

**Comment by Le0Michine** [comment]
@sx95 проблема решена?

**Comment by sx95** [comment]
@Le0Michine решена, я просто забил на ВК Api. Если хотите написать что-то объемное и полезное - у Вас не получится, потому что ВК ограничивает доступ к полному функционалу, а толку от импотента - я хз. Но если у Вас есть какая-то лазейка в руководстве ВК, тогда есть шанс на получение доступа.
