### ISSUE TITLE
Отсутствует поле в VK SDK

### ISSUE THREAD

**Issue by CssHammer** [VKCOM/vk-android-sdk#331]
При вызове метода messages.getDialogs приходит ответ с объектами message. Если у меня в диалогах есть беседа, то объект message содержит в себе поле chat_id и прочие данные о беседе. В классе VkApiMessage и других в SDK мне не удалось обнаружить соответствующего поля, следовательно значение chat_id из ответа не парситься и теряется. Из-за этого не возможно идентифицировать беседа ли это. Как с этим справляться? Парсить JSON вручную? 

![](https://pp.vk.me/c637620/v637620284/2aa61/6BZZhUsev_Y.jpg)
![](https://pp.vk.me/c637620/v637620284/2aa68/ygzH7U7rs_8.jpg)

**Comment by Le0Michine** [comment]
@CssHammer вариант 1 -- дописать недостающие модели
вариант 2 -- у беседы значение поля title не пустое и не равно " ... "

**Comment by CssHammer** [comment]
@Le0Michine Мне кажется или это должны делать разработчики SDK?

**Comment by Le0Michine** [comment]
@CssHammer естественно :)
но с учетом даты последнего коммита не уверен это произойдет в ближайшем будущем, да и в целом в этом sdk из полезного только авторизация разве что, чтобы что-то нормально сделать надо переписать половину sdk и дописать еще своего, многие методы просто не реализованы

**Comment by dkostryukov** [comment]
@CssHammer , если каких-то полей не хватает, Вы можете попарсить json сами
