### ISSUE TITLE
Upload video to storage

### ISSUE THREAD

**Issue by dpproduction** [VKCOM/vk-android-sdk#332]
Hi guys! 
So I need post video to my wall. In this SDK, I found only _uploadWallPhotoRequest(...)_. 
Can anybody tell me, how to upload video file to vk storage and then post it to my wall?

**Comment by gabberrr** [comment]
I did it.
1. We need get upload url 
       _vkParameters.put("name", "sdk test");
       vkParameters.put("wallpost", "1");
       VKRequest req = VKApi.video().save(vkParameters);_

2. Upload our file to this url 
 _String url = response.json.getJSONObject("response").getString("upload_url");
  int ownerId = response.json.getJSONObject("response").getInt("owner_id");
 MultipartBody.Part video = prepareFilePart("video_file", pathToFile);
Response<JsonObject> uploadResp = mApiInterface.postVideoToVk(url, video).execute();_

3. Post to wall
  _VKParameters parameters = new VKParameters();
   parameters.put(VKApiConst.OWNER_ID, ownerId);
   parameters.put(VKApiConst.ATTACHMENTS, "video_"+ownerId+"_"+uploadResp.body().get("video_id").getAsInt());
  VKRequest req =  VKApi.wall().post(parameters);_

**Comment by olegsm** [comment]
Please, use new version 2.0.+
