### ISSUE TITLE
В VKSdk.onActivityResult() периодически VKAccessToken == null при первом запуске

### ISSUE THREAD

**Issue by arso8** [VKCOM/vk-android-sdk#334]
Добрый день.

Проблема в том, что при первом запуске приложения на момент вызова `VKSdk.onActivityResult()`, `VKAccessToken.currentToken() == null`.

Происходит это из-за вызова `trackVisitor(null)`, если `oldToken == null` (VKSdk.java:315). 
В trackVisitor происходит ошибка (VKError (code: 5; ; User authorization failed: invalid session.)) и токен обнуляется в `onAccessTokenIsInvalid()`.

Null приходит не всегда, но достаточно часто.

_sdk ver 1.6.8
api ver 5.21 (на 5.62 тоже воспроизводится)_

**Comment by arso8** [comment]
Есть, конечно, workaround, но не советую =)
![1](https://cloud.githubusercontent.com/assets/1999809/23215773/97626da6-f924-11e6-9def-54eac4eb22c7.jpg)

**Comment by olegsm** [comment]
use new 2.0.2 version.
