### ISSUE TITLE
[SCOPE] NPE at hasScope check

### ISSUE THREAD

**Issue by alexeypodolian** [VKCOM/vk-android-sdk#335]
I have some crashes at production build with the following stack trace: 
`Fatal Exception: java.lang.NullPointerException at com.vk.sdk.VKAccessToken.hasScope(VKAccessToken.java:313)`

313 line at VKAccessToken class: `if (this.scope.get(scopeStr) == null)`

It's look like at some point `this.scope` is null at VKAccessToken object.

I'm doing something wrong, or it's an issue at SDK? 
Can you help, please?

**Comment by karpoff** [comment]
I see the same issue in my prod application but I can't reproduce it and check why does it happen
I believe there should be some exception handling in public boolean hasScope (VKAccessToken.java:313) for fixing that

**Comment by Zachary625** [comment]
Same issue here~

**Comment by Zachary625** [comment]
Same issue here.

**Comment by abzal86** [comment]
Also having this issue. Any workarounds?
![image](https://user-images.githubusercontent.com/6681239/39166254-4e527cdc-47bb-11e8-9a38-9778099d045c.png)

**Comment by olegsm** [comment]
use new 2.0.2 version.
