### ISSUE TITLE
 Нет возможности восстановить VKShareDialogListener после переворота экрана.

### ISSUE THREAD

**Issue by shushper** [VKCOM/vk-android-sdk#336]
Строим диалог при помощи VKShareDialogBuilder() и задаем ему VKShareDialogListener. После переворота экрана, диалог восстанавливается и показывается на экране, но листенера у него уже нет. И даже если мы через tag найдем этот фрагмент, нет возможности задать ему новый листенер.

Если после переворота экрана нажать send и sharing пройдет успешно, то можно и не заметить что нужен листенер. Но если пришла какая-то ошибка, ее уже негде обрабатывать. Например, можно выключить интернет, показать VkShareDialog, перевернуть экран и нажать send. Произойдет ошибка, но ее негде отловить, да к тому же диалог останется на экране. 

Как вариант у VkShareDialogNative можно сделать публичный метод  setListener.

**Comment by olegsm** [comment]
Old version doesn't support now, use 2.0.+ version.
