### ISSUE TITLE
Official vk application

### ISSUE THREAD

**Issue by polyak01** [VKCOM/vk-android-sdk#338]
Добрый день, мы используем веб приложение, как на фронте(android), так и на серверной части, все работает отлично через sdk view. Но если стоит официальное приложение вк - при попытке авторизироваться происходит ошибка, что sdk не установлено. Как-нибуть можно обойти этот момент и использовать только sdk view даже если есть официальное приложение? Если нет, то какой другой пусть существует?
[screen](https://github.com/polyak01/data/blob/master/Screenshot_2017-02-07-13-45-40.png)

**Comment by dkostryukov** [comment]
@polyak01 по ссылке 404
