### ISSUE TITLE
Не работает onProgress()

### ISSUE THREAD

**Issue by shagspb** [VKCOM/vk-android-sdk#344]
Ребята, привет. При аплоаде картинки почему-то не работает onProgress(). 

Код:

 VKRequest request = VKApi.uploadWallPhotoRequest
                (new VKUploadImage(bm, VKImageParameters.pngImage()), 0, 0);
        request.executeWithListener(new VKRequest.VKRequestListener() {

            @Override
            public void onProgress(VKRequest.VKProgressType progressType, long bytesLoaded, long bytesTotal) {
                // вот тут проблема. Не вызывается во время загрузки. Ни разу.
               Log.d("progress", "progressType");
                progress.progress(bytesLoaded / bytesTotal);
                super.onProgress(progressType, bytesLoaded, bytesTotal);
            }

            @Override
            public void onComplete(VKResponse response) {
                progress.onComplete(response);
                super.onComplete(response);
            }

});

**Comment by olegsm** [comment]
Старая версия  SDK не поддерживается больше.
