### ISSUE TITLE
При использовании функции VKSdk.wakeUpSession всегда приходит LoggedOut или Pending

### ISSUE THREAD

**Issue by InokumaT** [VKCOM/vk-android-sdk#348]
При старте приложения мы хотим восстановить accessToken с прошлой сессии. выглядит это так 
             

VKSdk.customInitialize(ApplicationContext,AppID,"");
             VKSdk.wakeUpSession(LoaderAPI.getActivity().getApplicationContext(), new VKCallback<VKSdk.LoginState>() {
            @Override
            public void onResult(VKSdk.LoginState res) {  				  
                    switch (res) {                        
                        case LoggedIn:							
                            // говорим, что уже залогинены
                            break; 
			case LoggedOut: 
                        case Pending:                           
                        case Unknown:
				//не залогинены
                            break;							
                    }   				   
            }
            @Override
            public void onError(VKError error) {
					//произошла ошибка
            }
});

после этого мы всегда переходим в состояние 	//не залогинены, с чем это может быть связано?

**Comment by olegsm** [comment]
Please use new SDK 2.0 version.
