### ISSUE TITLE
Отлавливание сообщения

### ISSUE THREAD

**Issue by Newmcpe** [VKCOM/vk-android-sdk#353]
Как можно отлавливать сообщение,сразу,как он прийдет?

**Comment by vitos18** [comment]
http://ukrainie.sexy/gladki/115158-khlopec-c-liy-t...
http://ukrainie.sexy/gladki/115230-tovsta-dama-z-d...
http://ukrainie.sexy/gladki/115247-cholov-k-dovba-...
подписывайся на нашу группу


>Понедельник, 28 августа 2017, 13:28 +03:00 от Newmcpe <notifications@github.com>:
>
>Как можно отлавливать сообщение,сразу,как он прийдет?
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Виталий Рочняк
vitaliy.rochnyak@mail.ru

**Comment by vitos18** [comment]
http://ukrainie.sexy/gladki/115247-cholov-k-dovba-dvokh-tovstikh-kokhanok-na-shirokomu-l-zhku.html  


>Понедельник, 28 августа 2017, 13:28 +03:00 от Newmcpe <notifications@github.com>:
>
>Как можно отлавливать сообщение,сразу,как он прийдет?
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Виталий Рочняк
vitaliy.rochnyak@mail.ru
