### ISSUE TITLE
fingerprint of sdk is incorrect through app login

### ISSUE THREAD

**Issue by alexnik0888** [VKCOM/vk-android-sdk#354]
I have "fingerprint of sdk is incorrect" error when I login through VK app. Via web form all is ok. 
All data in vk settings is right. I see you have many issues like this. How to fix it?

**Comment by Yazon2006** [comment]
@alexnik0888 
Short answer: to set proper fingerprint in VK console.
Details: Your app should be signed with key (https://developer.android.com/studio/publish/app-signing.html). By default it is signed with some randomly generated during Android Studio installation debug key. Each key has its SHA-1 fingerprint and you can retrieve it (https://developers.google.com/android/guides/client-auth). So generally solution steps are easy:
1) Sign apk with key.
2) Get SHA-1 fingerprint and set it in VK dev console.
3) Make sure that fingerprint in VK console and fingerprint of key that was used for application the same.
This procedure absolutely the same as in Firebase console or Google Cloud Messaging console (deprecated now). Nothing new. Nothing unexpected.

**Comment by olegsm** [comment]
Please, follow to new version.
