### ISSUE TITLE
sdk_package is incorrect after changing package name

### ISSUE THREAD

**Issue by 4eRTuk** [VKCOM/vk-android-sdk#355]
1. на устройстве есть приложение ВК
2. в вебе задаем package name и MainActivity
3. логинимся через ВК в своём приложении на андроиде
4. изменяем package name (может и MainActivity тоже влияет) на другой
5. последующие входы в своё приложение выдают "sdk_package is incorrect"

**Comment by NirvanaRSX** [comment]
Проблема была, как-то решена? 

Аналогичная проблема: package name поменяли и отвалилась регистрация в приложении через вк и гугл
