### ISSUE TITLE
Поддержка прокси

### ISSUE THREAD

**Issue by bartwell** [VKCOM/vk-android-sdk#356]
Возможно ли выполнять запросы к API с помощью Android SDK через прокси? Если да, то с помощью каких методов можно указать параметры прокси?
В документации ничего не удается найти по этому поводу.

**Comment by itslonua** [comment]
Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(PROXY_HOST, PROXY_PORT));
HttpTransport httpTransport = new NetHttpTransport.Builder().setProxy(proxy).build();
VkApiClient vk = new VkApiClient(httpTransport );

**Comment by bartwell** [comment]
Похоже, что класс VkApiClient отсутствует в Android SDK, кажется, он есть только в Java SDK.

**Comment by olegsm** [comment]
Используете версию 2.0+, переопределяйте на свой OkHttpClient.
