### ISSUE TITLE
Поменялся пользователь на мобильном официальном клиенте

### ISSUE THREAD

**Issue by rBadamshin** [VKCOM/vk-android-sdk#357]
После того, как мы залогились с помощью `VKSdk.login(getActivity(), VKScope.WALL);` мы можем бессрочно постить записи из стороннего приложения себе на страницу, например. Соответственно не хочется перед каждой попыткой запостить что-то вконтакт просить разрешение у пользователя, но по требованиям нужно знать - не перелогинились ли на официальном клиенте, чтобы в этом случае мы постили на стену уже другого пользователя. Скажите пожалуйста какие варианты есть?

**Comment by olegsm** [comment]
Please use new SDK version 2.0
