### ISSUE TITLE
Vk SDk, getNearby, geolocation

### ISSUE THREAD

**Issue by Nay1man** [VKCOM/vk-android-sdk#358]
Hello, I newbie in android development. How use users.getNearby? How android 
automatically receives geolocation in parameters "latitude" and "longitude". Please write code exempale.
Site of Vk SDK: https://vk.com/dev/users.getNearby

**Comment by olegsm** [comment]
You can use base example from new SDK (https://github.com/VKCOM/vk-android-sdk/blob/master/samples/app/src/main/java/com/vk/sdk/sample/requests/VKUsersRequest.kt)

Use android.location.Location and com.google.android.gms.location.LocationRequest classes.
