### ISSUE TITLE
Application@OnCreate Unity bridge

### ISSUE THREAD

**Issue by slavaobninsk** [VKCOM/vk-android-sdk#359]
Здравствуйте раньше при написания плагина для Unity (формат .jar), VKSdk.initialize можно было вызывать из класса extends Activity, после обновления SDK android, выдается ошибка, что VKSdk.initialize необходимо вызывать из Application@OnCreate. Можно ли как то избежать этого при использование типа билда на стороне Unity -Internal build system ?

**Comment by olegsm** [comment]
use new 2.0.2 version.
