### ISSUE TITLE
Manifest merger failed : Attribute activity#com.vk.sdk.VKServiceActivity@splitName

### ISSUE THREAD

**Issue by holoduke** [VKCOM/vk-android-sdk#361]
Whenever i try to add this library in 2 modules used in the same app. i get a error

Execution failed for task ':base:processDebugFeatureManifest'.
> Manifest merger failed : Attribute activity#com.vk.sdk.VKServiceActivity@splitName value=(feature_match) from [:feature_match] AndroidManifest.xml:71:13-46
        is also present at [:feature_topvoters] AndroidManifest.xml:74:13-50 value=(feature_topvoters).
        Suggestion: add 'tools:replace="android:splitName"' to <activity> element at AndroidManifest.xml:68:9-72:53 to override.

Anyone know how to solve this situation?
My app is a multi module app. Not in every module the dependency of vkontakte is needed, so i import it in 2 modules where i need it. 
The manifest merging phase goes wrong here. 
There is no manifest file where i have defined com.vk.sdk.VKServiceActivity. That is part of the library itself.

**Comment by olegsm** [comment]
Old version doesn't support now, use 2.0.+ version.
