### ISSUE TITLE
Использование публичных методов

### ISSUE THREAD

**Issue by shamil10031** [VKCOM/vk-android-sdk#363]
Здравствуйте! Пишу приложение с использованием вк авторизации. Ради интереса решил просто тестировать разное и вот что обнаружил (Безусловно сделал все, что нужно : standalone приложени, отпечаток-ключ андроид-приложения и тд):
Публичные запросы обрабатываются без всякой авторизации и токенов (то есть просто пишу что то типа users.get() и другие разные публичные методы);
Добавил авторизацию, и при подтверждении авторизации начали работать методы, требующие токен юзера; Но вот , что непонятно:
- Когда вызываю метод VKSdk.login() (то есть когда добавляю авторизацию), то при отмене авторизации (то есть когда выходит окошко со входом, а я нажимю отменить) публичные методы перестают работать , выходит ошибка Acces denied. Но, безусловно, при подтверждении авторизации работают и публичные методы и те, которые работают с токеном юзера.
- А когда не вызываю метод login , то все методы публичные работают корректно;
Поэтому и проблема: хочется добавить авторизацию пользователя, но при этом , если пользователь вдруг откажется авторизовываться, то у него будут грузиться хотя бы публичные методы.

Читал, что публичные методы работают как минимум с сервисным токеном (то есть нужен токен standalone приложения), но, как я писал выше, публичные методы (когда не добавлял авторизацию VKSdk.login()) работали и без него. А при отмене авторизации токен стандалон приложения не помогал. Помогите, может я чего то не понимаю?

**Comment by olegsm** [comment]
Please use new SDK version 2.0
