### ISSUE TITLE
На эмуляторе не появляется окно запроса доступа к аккаунту

### ISSUE THREAD

**Issue by stoplus** [VKCOM/vk-android-sdk#365]
На эмуляторах  не появляется окно запроса доступа к аккаунту и подтверждения. Просто темнеет экран, немного поработал прогресбар и всё.
![fgfg](https://user-images.githubusercontent.com/29597046/35856132-1827948c-0b46-11e8-89e0-8fd777756df1.png)
На реальном телефоне всё работает хорошо.  Но при нажатии на "Скрыть уведомление", вылетает ошибка 403.
![screenshot_2018-02-06 -14-05-28](https://user-images.githubusercontent.com/29597046/35856651-b9d8022a-0b47-11e8-8fd7-a0b1e6a830e5.png)
Помогите разобраться пожалуйста, что не так

**Comment by olegsm** [comment]
Old version doesn't support now, use 2.0.+ version. Reopen issue instead of.
