### ISSUE TITLE
как передать параметры в метод likes.delete?

### ISSUE THREAD

**Issue by anjilite7** [VKCOM/vk-android-sdk#369]
получаю owner_id и item_id из метода fave.getPhotos и передаю их в likes.delete

`VKRequest vkRequest = new VKRequest("likes.delete", VKParameters.from(VKApiConst.FIELDS, "photo",owner_id,item_id));`

Получаю следующую ошибку:

VKError (API errorVKError (code: 100; ; One of the parameters specified was missing or invalid: type is undefined))

**Comment by plaxin** [comment]
owner_id + "_" + item_id
