### ISSUE TITLE
Не вызывается onActivityResult, если установлен ВК клиент

### ISSUE THREAD

**Issue by kafffka** [VKCOM/vk-android-sdk#370]
На vk.com у приложения установлены все настройки.

В манифесте 
```
<activity android:name="com.vk.sdk.VKServiceActivity"
                android:label="ServiceActivity"
                android:theme="@style/VK.Transparent" />
```

В strings.xml
`<integer name="com_vk_sdk_AppId">APP_ID</integer>`

Gradle: 
`implementation 'com.vk:androidsdk:1.6.9'`

App
```
private var vkAccessTokenTracker: VKAccessTokenTracker = object : VKAccessTokenTracker() {
        override fun onVKAccessTokenChanged(oldToken: VKAccessToken?, newToken: VKAccessToken?) {
            Log.wtf("LogTest", "vkAccessTokenTracker ${oldToken?.userId} ${newToken?.userId}")
            if (newToken == null) {

                Log.wtf("LogTest", "token null")
            }
        }
    }

...

vkAccessTokenTracker.startTracking();
VKSdk.initialize(App.instance)
```

Activity
`VKSdk.login(activity, "friends")`

Если у пользователя не установлен клиент, то всё в порядке. Если установлен клиент, то onActivityResult не вызывается. Единственное, что смог сделать при наличии клиента, это при повторном запросе отлавливать у vkAccessTokenTracker токен пользователя.

**Comment by arturkarapetyanKlassroom** [comment]
То же самое у меня, onActivityResult не вызывается

**Comment by olegsm** [comment]
Please use new SDK version 2.0
