### ISSUE TITLE
the share dialog lacks callback

### ISSUE THREAD

**Issue by bigmouseyan** [VKCOM/vk-android-sdk#372]
In onCreateDialog of VKShareDialogDelegate,
--------------
mInternalView.findViewById(R.id.close_btn).setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View v) {
				dialogFragmentI.dismissAllowingStateLoss();
			}
});
--------------
This section of the code can colse the share dialog, but it does not call the VKShareDialogListener。Thus, my activity can not receive the callback. So, I hope VK team can repair this issue. Thank you!

**Comment by mrdazhuk** [comment]
I've faced with the same problem. @bigmouseyan  How did you solve it?

**Comment by bigmouseyan** [comment]
you can create a new package named "com.vk.sdk.dialogs" in your own project
then inherit DialogFragment

codes like this:
`package com.vk.sdk.dialogs;

import android.annotation.SuppressLint;
import android.app.Dialog;
import android.app.DialogFragment;
import android.content.DialogInterface;
import android.os.Bundle;
import android.support.annotation.NonNull;

/**
 * Created by junhuiyan on 2018/4/25.
 */

public class IMSDKShareDialogNative  extends DialogFragment implements VKShareDialogDelegate.DialogFragmentI{
    private VKShareDialogDelegate mDelegate = new VKShareDialogDelegate(this);
    private VKShareDialogBuilder.VKShareDialogListener listener;
    public IMSDKShareDialogNative() {
    }

    @SuppressLint("ValidFragment")
    IMSDKShareDialogNative(VKShareDialogBuilder builder) {
        mDelegate.setAttachmentImages(builder.attachmentImages);
        mDelegate.setText(builder.attachmentText);
        if (builder.linkTitle != null && builder.linkUrl != null) {
            mDelegate.setAttachmentLink(builder.linkTitle, builder.linkUrl);
        }
        mDelegate.setUploadedPhotos(builder.existingPhotos);
        mDelegate.setShareDialogListener(builder.listener);
        listener = builder.listener;
    }

    @NonNull
    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        return mDelegate.onCreateDialog(savedInstanceState);
    }

    //取消分类的onSaveInstanceState，避免图片保存到bundle的Bug
    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
//        mDelegate.onSaveInstanceState(outState);
    }

    @Override
    public void onCancel(DialogInterface dialog) {
        super.onCancel(dialog);
        mDelegate.onCancel(dialog);
    }

    @Override
    public void dismissAllowingStateLoss() {
        super.dismissAllowingStateLoss();
        if(listener != null){
            listener.onVkShareCancel();
        }
    }
}`

**Comment by olegsm** [comment]
Please follow new version.
