### ISSUE TITLE
Clipping the VK activity view on Android 8.0 / 8.1

### ISSUE THREAD

**Issue by grey-panther** [VKCOM/vk-android-sdk#376]
Hi! I have a problem with the SDK on devices with Android 8.0 and 8.1.
Steps:
1) Uninstall VK-app if it's installed on the device;
2) Build VKTestApplication and install it on the device;
3) Go to the landscape orientation;
4) Tap the button "SIGN IN WITH VK";
5) Tap an input form (login or password) to call a soft keyboard;
6) Close the soft keyboard making a click on system button "Back".

The result is a clipped view where is unable to click buttons "Login" and "Cancel".
![screenshot_20180615-182632](https://user-images.githubusercontent.com/18363546/41476858-6426185a-70cb-11e8-95b8-9dd760892a41.jpg)

On previous Android API versions the view is resized when a soft keyboard is hidding.

**Comment by darkstarx** [comment]
Yes, we have the same problem in our product.
Fix this issue please!

P.S. We use gradle integration, so a new version needed in the repository.

**Comment by olegsm** [comment]
Please use new SDK version 2.0
