### ISSUE TITLE
Пропадает форма авторизации при нажатии на "Скрыть уведомление"

### ISSUE THREAD

**Issue by MikeOsipov** [VKCOM/vk-android-sdk#378]
При авторизации без установленного VK клиента, если появляется уведомление (в данном случае про привязку номера), после нажатия на "Скрыть уведомление" форма пропадает и остается затемненный прозрачный фон. По нажатию на бэк возвращаемся на первоначальный экран. 

![vk_auth_issue_1](https://user-images.githubusercontent.com/7148918/42259928-a882caa0-7f8c-11e8-98a4-33dc5ff056fc.png)
![vk_auth_issue_2](https://user-images.githubusercontent.com/7148918/42259929-a8a8304c-7f8c-11e8-8449-a59473e5ade5.png)
![vk_auth_issue_3](https://user-images.githubusercontent.com/7148918/42259930-a8d613a4-7f8c-11e8-80e8-c06a19cc4d65.png)

**Comment by olegsm** [comment]
Old version doesn't support now, use 2.0.+ version. If issue can be reproduced, just reopen.
