### ISSUE TITLE
Ошибка при авторизации

### ISSUE THREAD

**Issue by QeGle** [VKCOM/vk-android-sdk#385]
Возникает при нажатии "Отмена" на вебвью. 
com.vk:androidsdk:2.0.0

<img width="566" alt="2019-02-01 19 25 33" src="https://user-images.githubusercontent.com/12546542/52128627-44cff380-2657-11e9-9c26-f5712769aa5f.png">

**Comment by smileman** [comment]
Такая же ошибка возникает. Хотелось бы фикса =)

**Comment by e-rikov** [comment]
У меня такая же проблема

**Comment by olegsm** [comment]
fixed in 2.02
