### ISSUE TITLE
Нет класса VKUsers 

### ISSUE THREAD

**Issue by kon3gor** [VKCOM/vk-android-sdk#386]
Пытаюсь выполнить запрос к апи, но у меня нет класса VKUser. У меня вообще нет vk.sdk. Есть только vk.api.sdk. Что с этим делать ?

**Comment by olegsm** [comment]
Можно глянуть класс из примера (https://github.com/VKCOM/vk-android-sdk/blob/master/samples/app/src/main/java/com/vk/sdk/sample/models/VKUser.kt)
