### ISSUE TITLE
Как загрузить фото?

### ISSUE THREAD

**Issue by panovvitalik** [VKCOM/vk-android-sdk#387]
Вроде как по поиску должен быть метод VKApi.uploadWallPhotoRequest 
В версии 2.0.0 VKApi не нашел.
И в исходниках uploadWallPhotoRequest нет

Как загрузить фото? Хотя-бы просто в ВК - и получить в ответе ссылочку на jpg. 

p.s.
Пока даунгрейднулся до 1.6.9. Там методы все эти есть.

**Comment by acyuta** [comment]
Нужно создать самому обработчик отнаследовавшись от дженерика VKRequest<>.
Удобно, что можно самому маппить ответы и не хранить токен.

**Comment by panovvitalik** [comment]
я почему-то так сразу и подумал, что "нужно создать, заженерить, замапить" и т.п... 
Поэтому лучше пока поживем с 1.6.9. одна строчка кода для загрузки картинки меня вполне устраивает.
Спасибо
