### ISSUE TITLE
Access denied: no access to call this method | by [photos.getWallUploadServer]

### ISSUE THREAD

**Issue by solareye** [VKCOM/vk-android-sdk#392]
Невозможно сделать share на стену с прикреплённой фотографией без установленного приложения, то есть через VK SDK webView.

Покапавшись обнаружил в VKWebViewAuthActivity метод
`private fun loadUrl() {
try {
            val urlToLoad = if (needValidationResult()) intent.getStringExtra(VK_EXTRA_VALIDATION_URL)
                    else "https://oauth.vk.com/authorize?client_id=${params.appId}" +
                    "&scope=$params.getScopeString()" +
                    "&redirect_uri=$REDIRECT_URL" +
                    "&display=mobile" +
                    "&v=${VK.getApiVersion()}" +
                    "&response_type=token&revoke=1"
            webView.loadUrl(urlToLoad)
        } catch (e: Exception) {
            setResult(Activity.RESULT_CANCELED)
            finish()
        }
    }`

где пропустили фигурные скобки в `"&scope=$params.getScopeString()" +`

Должно быть `"&scope=${params.getScopeString()}" +`

**Comment by olegsm** [comment]
fixed in 2.0.2
