### ISSUE TITLE
где найти java версию

### ISSUE THREAD

**Issue by sashastg** [VKCOM/vk-android-sdk#398]
Добрый день
вижу что все ваши примеры / сдк  написаны на Kotlin.
мой android проект написан на Java.
как я могу работать с vk sdk ?

**Comment by TemMax** [comment]
Здравствуйте!
Koltin полностью совместим с Java.
Работать можете так же, как и обычно — сильных отличий нет.

**Comment by sashastg** [comment]
пробовали несколько разных специалистов, не получилось пройти дпльше
аутинтификации.
в частности сделать публикацию на стену.


вт, 2 апр. 2019 г., 17:28 Artem Komar <notifications@github.com>:

**Comment by olegsm** [comment]
Можно работать с старой версией СДК, но ее поддержка остановлена
https://github.com/VKCOM/vk-android-sdk/tree/version1.6.9
