### ISSUE TITLE
Как получить email пользователя при авторизации в версии SDK 2.0.0

### ISSUE THREAD

**Issue by giperwlad** [VKCOM/vk-android-sdk#399]
В предыдущих версиях SDK (до 2.0)  email можно было достать из объекта VKAccessToken, сразу в callback авторизации. Но сейчас этого поля нет.

**Comment by giperwlad** [comment]
Есть способ. Брать вручную из intent.extras при получении activityResult. Какой смысл было убирать email из VKAccessToken. Если и был, то нужно возвращать в VKAuthCallback полный ответ вместе с email, ибо api возвращает его. Иначе складывается ощущение что во 2.0.0 версии просто косякнули и случайно потеряли email.

**Comment by kkaun** [comment]
В точности такое же ощущение при взгляде на рефакторнутый `VKAccessToken` :)

**Comment by ruha9005** [comment]
Сделал PR
https://github.com/VKCOM/vk-android-sdk/pull/401

**Comment by whalemare** [comment]
Аналогично потерялась аватарка пользователя в account.getProfileInfo :\

**Comment by Strikelon** [comment]
Выше написали: "Брать вручную из intent.extras при получении activityResult"
Можете написать подробнее как именно?
```
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        val callback = object: VKAuthCallback {
            override fun onLogin(token: VKAccessToken) {
// Получать из data? Если через data?.getStringExtra(Что писать здесь в качестве параметра?)
                SecondActivity.startFrom(this@MainActivity)
                finish()
            }

            override fun onLoginFailed(errorCode: Int) {
            }
        }
        if (!VK.onActivityResult(requestCode, resultCode, data!!, callback)) {
            super.onActivityResult(requestCode, resultCode, data)
        }
    }
```

**Comment by ruha9005** [comment]
@Strikelon это был workaround (дублирующий уже существующий на тот момент функционал из библиотеки), необходимые изменения уже есть в последней версии

**Comment by olegsm** [comment]
fixed
