### ISSUE TITLE
Установка кастомного конфига

### ISSUE THREAD

**Issue by bartwell** [VKCOM/vk-android-sdk#400]
Пытаюсь установить кастомный конфиг используя VK SDK 2.0.2. Использую следующий код:

        VKApiConfig.Builder vkApiConfig = new VKApiConfig.Builder();
        vkApiConfig.context(this);
        vkApiConfig.logger(new DefaultApiLogger(Logger.LogLevel.VERBOSE, "myTag"));
        vkApiConfig.getOkHttpProvider().updateClient(builder -> {
            return new OkHttpClient.Builder()
                    .someMethod1()
                    .someMethod2()
        });
        VK.setConfig(vkApiConfig.build());

Но в логах записи с "myTag" не появляются и настройки HttpClient-а не изменяются судя по всему. Вероятно, конфиг не обновляется. Как это делать правильно?

**Comment by arsich** [comment]
Никаких не приходит или приходят с "VKSdkApi"?
