### ISSUE TITLE
Android SDK Login:  cannot be automatically authorized

### ISSUE THREAD

**Issue by linvd** [VKCOM/vk-android-sdk#403]
We meet such an issue, is there anyone can help? It will be appreciated!! Many thanks!!

Android SDK Client Auto Authorization Login Problem:
After VK Android client first authorized login, the next login can not be automatically authorized. Each time the authorization have to be called. The code in the VK document and the actual code are different. How can we achieve the automatic authorization after first time? And is there anyone can help provide example code?
Thank you!
---------------------------------------
После первого авторизованного входа в Android VK клиента, следующий вход не может быть авторизован автоматически, повторно нужно авторизовывать каждый раз. Код из файла отличается от действительного кода. Пожалуйста, предоставьте действительный код, чтобы можно было осуществить автоматическую авторизацию.

**Comment by arsich** [comment]
https://vk.com/editapp?act=create вы можете создать приложение здесь и получить appId. Если речь не про это, уточните пожалуйста, какой код имеется ввиду
