### ISSUE TITLE
Не вызывается VKAuthCallback#onLoginFailed 

### ISSUE THREAD

**Issue by docentTSR** [VKCOM/vk-android-sdk#405]
sdk ver: 2.1.0

Если словить ошибку **"sdk package is incorrerct"** и уйти с этого экрана, то не вызывается **VKAuthCallback#onLoginFailed**.

В сдк отрабатывает условие
fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?, callback: VKAuthCallback, context: Context): Boolean {
        if (requestCode != VK_APP_AUTH_CODE || **data == null**) {
            return false
        }
        // some code
        return true
}

Можно смотреть на result, что он false, но тогда придется писать в двух местах логику по обработке ошибки. Почему не использовать onLoginFailed(VKAuthCallback.UNKNOWN_ERROR) если **data == null** ?

Странно одновременно иметь result и callback.

**Comment by olegsm** [comment]
fixed
