### ISSUE TITLE
Смена параметра lang в VKRequest

### ISSUE THREAD

**Issue by lantseves** [VKCOM/vk-android-sdk#406]
В документации написано, что параметр lang общий для всех объектов
При попытке заполнить параметр значением "ru" в своем потомке VKRequest<List<VKUser>>
я все равно получал имена пользователей на английском

`

    public class VKFriendsGet extends VKRequest<List<VKUser>> {
    final String TAG_LOG = "TAG_LOG" ;
    public VKFriendsGet() {
        super("friends.get");
        this.addParam("fields" , "photo_200") ;
        this.addParam("lang" , "ru") ; // здесь я пытался заполнить параметр
    }

    @Override
    public List<VKUser> parse(@NotNull JSONObject r) throws Exception {
        List<VKUser> result = new ArrayList<>() ;
        JSONObject response = r.getJSONObject("response") ;
        JSONArray users = response.getJSONArray("items") ;
        for (int i = 0 ; i < users.length() ; i++) {
            result.add(VKUser.CREATOR.parse(users.getJSONObject(i))) ;
        }
        super.parse(r) ;
        return result ;
     }
    }

`

Я посмотрел исходный код класса VKRequest и увидел, что мой параметр затирается при выполнение метода onExecute

`

       @Throws(InterruptedException::class, IOException::class, VKApiException::class)
        override fun onExecute(manager: VKApiManager): T {
        val config = manager.config

        /*Добавьте тут условие, что заполнять параметр из VKApiConfig только если параметра 
        не задали при обращение 
        в своем проекте я унаследовал ваш класс и переопределил этот метод внес одну 
        строку на java вместо строки ниже
        if (!params.containsKey("lang")) params.put("lang" , config.getLang()) ;
        */
        
        params["lang"] = config.lang //Тут заменяется мой параметр на lang из ApiConfig
        params["device_id"] = config.deviceId
        params["v"] = config.version

        return manager.execute(VKMethodCall.Builder()
                .args(params)
                .method(method)
                .version(config.version)
                .build(), this)
    }
`

Добавьте такую проверку в ваш sdk

**Comment by olegsm** [comment]
1) val config = VKApiConfig.
2) config.lang = "ru"
2) VK.setConfig(config)

**Comment by Veilvi** [comment]
Возник тот же вопрос, но 
val config = VKApiConfig.
config.lang = "ru"
VK.setConfig(config)
не работает, вопрос в том, почему VK.setConfig(config) говорит, что найден VKApiConfig.Companion. Параметра config.lang также нет
