### ISSUE TITLE
Куда исчез ShareDialog? Постинг на стену

### ISSUE THREAD

**Issue by Lucasito** [VKCOM/vk-android-sdk#407]
В версии SDK на Kotlin не вижу ShareDialog. От него совсем отказались? Если делаю пост на стену с картинкой, как в примере, у меня почему-то ничего не происходит, ни ошибок, ничего. Без картинки постинг работает.

**Comment by Lucasito** [comment]
Так как выводить на данный момент ShareDialog?

**Comment by arsich** [comment]
https://github.com/VKCOM/vk-android-sdk/blob/master/samples/app/src/main/java/com/vk/sdk/sample/requests/VKWallPostCommand.kt
Попробуйте сделать как здесь.
Убедитесь, что при авторизации указали разрешение не только на VKScope.WALL, но и VKScope.PHOTOS
От ShareDialog отказались.
