### ISSUE TITLE
Где проводится отслеживание и ревалидация токена?

### ISSUE THREAD

**Issue by erlnby** [VKCOM/vk-android-sdk#408]
Почитал сурсы и не совсем понял, где производится обновление токена после конца времени его действия

**Comment by TemMax** [comment]
Автоматически токен не обновляется. Вы должны сами его обновить.

**Comment by arsich** [comment]
Воспользуйтесь VKTokenExpiredHandler
Пример: https://github.com/VKCOM/vk-android-sdk/blob/master/samples/app/src/main/java/com/vk/sdk/sample/SampleApplication.kt
