### ISSUE TITLE
Отсутствие удобного доступа к userId.

### ISSUE THREAD

**Issue by Anzohan** [VKCOM/vk-android-sdk#419]
Господа разработчики-олимпиадники! Добавьте пожалуйста статик метод VK.getUserId(), который будет возвращать Id залогиненного пользователя. Ибо сейчас эту информацию приходится хранить с помощью "костылей".

И раз уж вы решили хранить TokenExpiredHandler-ы в ArrayList а не в HashSet, то добавьте пожалуйста метод проверки, есть ли указанный хэндлер в списке, или нет.

**Comment by Sidebail** [comment]
+1, потратили уйму времени чтобы получить имя и фамилию после аутентификации. Решили откатиться до 1.6.7, на который ориентирована документация на https://vk.com/dev/android_sdk

Расширить документацию тут в README на английском было бы удобно

**Comment by alexxpert** [comment]
Видимо это не стали реализовывать, потому что получить объект текущего пользователя можно вызвав API метод `users.get` с пустым параметром `user_ids`

**Comment by arsich** [comment]
Добрый день! user_id можно получить через VK.getCurrentToken()?.userId
Имя-фамилию можно получить через users.get, пример запроса https://github.com/VKCOM/vk-android-sdk/blob/master/samples/app/src/main/java/com/vk/sdk/sample/requests/VKUsersRequest.kt
