### ISSUE TITLE
Upgrade to 2.1.1, login failed

### ISSUE THREAD

**Issue by heiyuye** [VKCOM/vk-android-sdk#428]
Upgrade to 2.1.1,
After the AccessToken is successfully obtained, the AccessToken is submitted to the server for login. The AccessToken invalid exception occurs and the login cannot be performed.

Version 1.6.9 does not have this issue.

Is this what is the reason

**Comment by arsich** [comment]
Check scopes and this example https://github.com/VKCOM/vk-android-sdk/blob/master/samples/app/src/main/java/com/vk/sdk/sample/WelcomeActivity.kt

**Comment by heiyuye** [comment]
Old version login will add VKScope.OFFLINE by default.Version 2.0.0 will not be added by default.

**Comment by maximgavrilov** [comment]
В текущей версии (начиная с 3.3.0) снова добавляется и на веб-авторизации вываливается в invalid scope:

https://github.com/VKCOM/vk-android-sdk/blob/e5ef9f63070c038c9cfbb8667ed463cadabf9ad7/core/src/main/java/com/vk/api/sdk/auth/VKAuthManager.kt#L136
