### ISSUE TITLE
Не видит VkServiseActivity

### ISSUE THREAD

**Issue by invweb** [VKCOM/vk-android-sdk#431]
https://sun9-52.userapi.com/c855336/v855336041/16a845/RSqwq2fp-3Q.jpg
Почему так?

**Comment by arsich** [comment]
Версия 2.0 без обратной совместимости. Либо оставаться на 1.6.9, либо поддержать новое апи по документации

**Comment by MobileSolutionsRu** [comment]
Я следовал вашим инструкциям и получил этот баг, что за ерунда? Команда что, не обновляет гайды что ли?
