### ISSUE TITLE
Как получить authorization_code через нативное приложение VK?

### ISSUE THREAD

**Issue by art2limit** [VKCOM/vk-android-sdk#432]
Сценарий простой, есть установленное приложение VK на телефоне, есть другое приложение которое запрашивает данные через OAUTH (Войти через ВКонтакте). Если следовать документации, то почта сразу придет в onActivityResult, но это не нужно, потому что почту должен забрать бекенд. Чтобы получить почту через бекенд, нужен authorization_code которого нет в приложении.

Вопрос, как его достать? Бекенд использует запрос https://oauth.vk.com/access_token

**Comment by arsich** [comment]
С бэкенда email получить нельзя. Пользователь должен напрямую на клиенте указать, что он разрешает доступ к своей почте

**Comment by art2limit** [comment]
это не связано с вопросом, с бекенда получить почту можно, если код авторизации будет
