### ISSUE TITLE
КАК получить профиль пользователя

### ISSUE THREAD

**Issue by MobileSolutionsRu** [VKCOM/vk-android-sdk#433]
Не могу найти самую банальную информацию: как получить профиль пользователя. В гайдах не найти, там какая - то ерунда про "список пользователей", нужно : получить имя пользователя (да ребят, до апи фейсбука вам расти и расти, приходится вас спрашивать о такой банальной информации)

**Comment by MobileSolutionsRu** [comment]
супер, я смотрю команда ВК не утруждается отвечать пользователям SDK на GitHub, по всей видимости SDK и его описание идеальны и это мы тут идиоты

**Comment by olegsm** [comment]
@MobileSolutionsRu вы можете реализовать метод с помощью SDK.  Реализуйте мтод по документации из https://vk.com/dev. Пример реализации можно найти в sample.

**Comment by invweb** [comment]
Где же найти эти самые samples, с ходу - не видно

**Comment by invweb** [comment]
А, ну вы закрыли тикет, видимо моя проблема решена (на самом деле это не так) спрашивается, почему?

**Comment by invweb** [comment]
Сильно в этом плане отстаёте от fb, у них всё очевидно ((
