### ISSUE TITLE
VkApi, не понимаю что импортировать

### ISSUE THREAD

**Issue by invweb** [VKCOM/vk-android-sdk#434]
Не находит VkApi, не находит что импортировать, не находит именно VkApi, остальное работает нормально. Какую зависимость надо добавить в градл, чтобы система увидела VkApi?

**Comment by SuleymanovTat** [comment]
какая у тебя версии библиотеки подключена?

**Comment by invweb** [comment]
implementation 'com.vk:androidsdk:2.1.1' 

Версия 2.1.1, не понятно почему в доках указан класс которого нигде нет

**Comment by invweb** [comment]
<img width="715" alt="Screenshot 2020-01-21 at 18 50 08" src="https://user-images.githubusercontent.com/2270351/72819784-ea241300-3c7e-11ea-99f4-e216835414c5.png">

**Comment by SuleymanovTat** [comment]
твой код будет работать в версии compile 'com.vk:androidsdk:1.6.5',
новой версии класс библиотеки класс называется VKUtils
вот так попробуй VKUtils.getCertificateFingerprint(this, this.getPackageName());  должно работать

**Comment by djdance** [comment]
VKUtils!
Почему об этом нет в доках? годы идут, а приходится все так же шариться по багрепортам

**Comment by invweb** [comment]
@djdance "плюсую"

**Comment by djdance** [comment]
справедливости ради, я неправ. В доках появилось. В глубине пункта _1.1 Отпечаток сертификата_

**Comment by invweb** [comment]
если появилось - отлично
