### ISSUE TITLE
wall.post друзьям? Реально?

### ISSUE THREAD

**Issue by glebPrischepa** [VKCOM/vk-android-sdk#44]
Доброго времени суток!
Подскажите, можно ли выполнять wall.post друзьям на их стены зная их id?

Выполняется следующий код.

```
final VKRequest post = VKApi.wall().post(
            VKParameters.from(VKApiConst.OWNER_ID, id, VKApiConst.ATTACHMENTS, attachments, VKApiConst.MESSAGE,
                    message, VKApiConst.PHOTO,link));
    post.setModelClass(VKWallPostResult.class);
```

post.executeWithListener(new VKRequestListener() {
            @Override
            public void onComplete(final VKResponse response) {  
                // Success
            }

```
        @Override
        public void onError(final VKError error) {
        // Error
        }
    });
```

id - соответственно id аккаунта.

В данном случае, если id != id авторизованного пользователя
приходит ошибка в onError
но error.errorMessage, error.errorReason  вообще null'ы.
Однако error.errorCode = -101.

Пробовал играться с VKApiConst.OWNER_ID и VKApiConst.USER_ID т.е. в OWNER_ID передавать id авторизованного пользователя (т.е. от кого), а в   USER_ID передавать id (кому). Но без результатно.

Подскажите, в чём проблема.
Спасибо

**Comment by vellbell14** [comment]
Подскажите, как открыть стену с помощью api
