### ISSUE TITLE
Получение токена в виде строки

### ISSUE THREAD

**Issue by BrightOS** [VKCOM/vk-android-sdk#443]
Какими методами можно достать токен при входе в приложение? К примеру, в результате успешной авторизации мы получаем VKAccessToken res. Так вот, как можно вытащить какой-либо токен пользователя из него в виде строки? Пишу на Java. Вопрос, вероятно, весьма тупой, ибо я в этом деле ещё совершенно не разбираюсь, но всё же

**Comment by BrightOS** [comment]
Короче говоря, всё, что надо сделать - перехватить токен после его получения в классе VKAccessToken в методе tokemFromParametrs сразу после строки с parametrs.get(ACCESS_TOKEN)

**Comment by putyavka** [comment]
Вызов VK.onActivityResult поддерживает передачу колбэков. В onLogin приходит VKAccessToken с исчерпывающим набором данных.

`VK.onActivityResult(requestCode, resultCode, data, vkAuthCallback)`

```
val vkAuthCallback = object: VKAuthCallback {
        override fun onLogin(token: VKAccessToken) {
            Log.i(TAG, "onLogin userId=${token.userId} accessToken=${token.accessToken}")
        }

        override fun onLoginFailed(errorCode: Int) {
            Log.i(TAG, "onLoginFailed errorCode=$errorCode")
        }
    }
```

Если надо получить токен, когда пользователь уже залогинен, то можно (хотя это хак) использовать внутреннее хранилище. Почему эти данные недоступны публично мне неясно

```
if (VK.isLoggedIn()) {
  val token = VKAccessToken.restore(
                activity.getSharedPreferences(
                    "com.vkontakte.android_pref_name",
                    Context.MODE_PRIVATE))
            Log.i(TAG, "token=$token")
        }
```
