### ISSUE TITLE
Ошибка при запуске sdk_fingerprint is incorrect

### ISSUE THREAD

**Issue by leks2** [VKCOM/vk-android-sdk#445]
Создал программу в Android Studio, использовал VK api. Вроде бы, авторизация должна работать. Я скомпилировал apk и установил на телефон, но при запуске пишет следующие(пишет в activity авторизации): {"error":"invalid_request","error_description":"sdk_fingerprint is incorrect"} . Что это значит? Я в настройках своего приложения VK прописал, как положено: Main Activity для Android, Название пакета для Android и отпечаток сертификата и все это происходит, если установлено официальное приложение VK с play market, если удалить приложение VK , то авторизация работает и в приложение заходит.

**Comment by atom1cx** [comment]
> Создал программу в Android Studio, использовал VK api. Вроде бы, авторизация должна работать. Я скомпилировал apk и установил на телефон, но при запуске пишет следующие(пишет в activity авторизации): {"error":"invalid_request","error_description":"sdk_fingerprint is incorrect"} . Что это значит? Я в настройках своего приложения VK прописал, как положено: Main Activity для Android, Название пакета для Android и отпечаток сертификата и все это происходит, если установлено официальное приложение VK с play market, если удалить приложение VK , то авторизация работает и в приложение заходит.

Столкнулись с похожей проблемой. Помогло указать ключ SHA256, не смотря на то, что в инструкции указан SHA1

**Comment by shushper** [comment]
А я не обратил внимание на эту строчку 

> By deleting all the colons you'll get your key's fingerprint.

После этого взял SHA1, удалил все двоеточия, вставил одной строкой и заработало.

**Comment by fortrannew** [comment]
Удивительно, но к 2024 году так и не исправили! То же самое пишет: sdk_fingerprint is incorrect, если установлено официальное приложение VK. Стоит удалить - и авторизация через VK работает. Использую flutter. Плагин flutter_login_vk: ^2.2.2+1
