### ISSUE TITLE
secure.checkToken проверка email

### ISSUE THREAD

**Issue by degtyaryov** [VKCOM/vk-android-sdk#448]
Добрый день.

Android приложение запрашивает email и потом передаёт его на сервер.

На сервере могу проверить достоверность всей информации переданной от клиента кроме email.

Как на сервере проверить что email не был модифицирован?

**Comment by gerra** [comment]
Привет!

email можно получить только при непосредственно авторизации

**Comment by degtyaryov** [comment]
> Привет!
> 
> email можно получить только при непосредственно авторизации
Добрый день.

Мне кажется что Вы мой вопрос не поняли.

Информацию от vk получает клиент и передаёт её на сервер.
secure.checkToken даёт возможность проверить эту информацию. Клиент может модифицировать эту информацию каким-то образом, например вирус или через какой-нибудь дебаггер.

Мне нужно знать действительно это тот email который передал vk клиенту.

Почему я не могу это сделать?

**Comment by gerra** [comment]
Такой возможности не прудсматривает апи ВКонтакте.

secure.checkToken проверяет на валидность выданный клиенту токен и не более. Казалось бы, этого должно хватать.

Секьюрность передачи выданного email-а от вашего клиента вашему бэкенду должна обеспечиться вами.
