### ISSUE TITLE
User authorization failed: access_token was given to another ip address.

### ISSUE THREAD

**Issue by bitvale** [VKCOM/vk-android-sdk#449]
Имеется приложение (мобильное (андроид) + серверная часть). Возможно ли получать данные пользователя на серверной части приложения с помощью access_token, полученного в мобильном приложении. 

В настоящий момент приходит ошибка: User authorization failed: access_token was given to another ip address.

Ведь по сути это одно приложение и пользователь разрешил ему использовать свои данные.

**Comment by libalex** [comment]
Токен привязывается к тому IP-адресу, с которого он был получен и официального способа обойти это ограничение вроде бы нет.
Есть инфа от коллег, что на "вечный" токен (scope `offline`) это ограничение не распространяется.

**Comment by bitvale** [comment]
Ясно, спасибо!
