### ISSUE TITLE
where is VKShareDialogBuilder ?

### ISSUE THREAD

**Issue by Zeus64** [VKCOM/vk-android-sdk#453]
Hello, When I read the doc located in https://vk.com/dev/android_sdk they use `VKShareDialogBuilder builder = new VKShareDialogBuilder(); ` but I can't find any implementation of `VKShareDialogBuilder` in the master. where is `VKShareDialogBuilder ` or what to use instead ?

**Comment by olegsm** [comment]
Hello! its documentation about old version SDK. https://github.com/VKCOM/vk-android-sdk/tree/version1.6.9
New 2.0+ version does not exist it.
