### ISSUE TITLE
Получить записи со стены

### ISSUE THREAD

**Issue by UrbanSide** [VKCOM/vk-android-sdk#468]
Всем доброго времени суток,подскажите нубу,как я могу получить записи со стены своей группы?
На старом SDK получалось,на этом не могу понять,все поменялось...

**Comment by Artemych** [comment]
Через метод api
https://vk.com/dev/wall.get
 любым из удобных способов которые описаны в redme на главное старнице

**Comment by UrbanSide** [comment]
> Через метод api
> https://vk.com/dev/wall.get
> любым из удобных способов которые описаны в readme на главное старнице

В Readme я вижу только **VKUsersRequest** пример.И не шибко понимаю как его можно переделать.

**Comment by Artemych** [comment]
`        
VK.execute(WallGet(ownerId = -1234567, offset = 0, count = 100), object : VKApiCallback<WallGetResponseDto> {
            override fun success(result: WallGetResponseDto) {
                
            }

            override fun fail(error: Exception) {
                
            }
 })
`



`        
Single.fromCallable {
            VK.executeSync(WallGet(ownerId = -1234567, offset = 0, count = 100))
}.subscribe {

 }`


`        VK.execute(WallGetCommand(ownerId = -1234567, offset = 0, count = 100), object: VKApiCallback<List<WallWallpostFull>> {
            override fun success(result: List<WallWallpostFull>) {
                TODO("Not yet implemented")
            }

            override fun fail(error: Exception) {
                TODO("Not yet implemented")
            }

        })

class WallGetCommand(
        private val ownerId: Int,
        private val offset: Int,
        private val count: Int
    ) : ApiCommand<List<WallWallpostFull>>() {
        override fun onExecute(manager: VKApiManager): List<WallWallpostFull> {
            val call = VKMethodCall.Builder()
                    .method("wall.get")
                    .args("owner_id", ownerId)
                    .args("offset", offset)
                    .args("count", count)
                    .version(manager.config.version)
                    .build()
            return manager.execute(call, ResponseApiParser())
        }


        class ResponseApiParser : VKApiResponseParser<List<WallWallpostFull>> {
            override fun parse(response: String?): List<WallWallpostFull> {
                TODO("Not yet implemented")
            }
        }

    }

`

**Comment by Artemych** [comment]
```kotlin
VK.execute(WallGet(ownerId = -1234567, offset = 0, count = 100), object : VKApiCallback<WallGetResponseDto> {
    override fun success(result: WallGetResponseDto) {
    
    }

    override fun fail(error: Exception) {
        
    }
 })

   
Single.fromCallable {
    VK.executeSync(WallGet(ownerId = -1234567, offset = 0, count = 100))
}.subscribe {

}


VK.execute(WallGetCommand(ownerId = -1234567, offset = 0, count = 100), object: VKApiCallback<List<WallWallpostFull>> {
    override fun success(result: List<WallWallpostFull>) {
        TODO("Not yet implemented")
    }

    override fun fail(error: Exception) {
        TODO("Not yet implemented")
    }

})

class WallGetCommand(
        private val ownerId: Int,
        private val offset: Int,
        private val count: Int
) : ApiCommand<List<WallWallpostFull>>() {
    override fun onExecute(manager: VKApiManager): List<WallWallpostFull> {
        val call = VKMethodCall.Builder()
                .method("wall.get")
                .args("owner_id", ownerId)
                .args("offset", offset)
                .args("count", count)
                .version(manager.config.version)
                .build()
        return manager.execute(call, ResponseApiParser())
    }


    class ResponseApiParser : VKApiResponseParser<List<WallWallpostFull>> {
        override fun parse(response: String?): List<WallWallpostFull> {
            TODO("Not yet implemented")
        }
    }
}
```

**Comment by UrbanSide** [comment]
**WallGetResponseDto** это как я понимаю типо модель должна быть?Которую нужно создать и заполнить как в получении пользователя?

**Comment by Artemych** [comment]
https://github.com/VKCOM/vk-android-sdk/blob/master/vk-sdk-api/src/main/java/com/vk/sdk/api/wall/dto/WallGetResponseDto.kt

**Comment by Artemych** [comment]
ну или если что-то не нравится то да руками написать свою с преферансом и куртизанками
