### ISSUE TITLE
Импортирование sdk в Android Studio

### ISSUE THREAD

**Issue by Lilostich** [VKCOM/vk-android-sdk#469]
Итак, я в своем приложении подключил android sdk vk добавлением строки implementation ... В built/gradle в итоге в моем проекте код с авторизацией проходит нормально, а при попытке выполнить строчки кода, которые приведены в качестве примера выполнения запроса на гите(vk.execute для получения списка друзей) не предлагает импортировать класс результата, как это решить? Пока большая проблема вызвать любой запрос

добавил строку в dependencies и сейчас она выглядит так :
dependencies {
    implementation 'com.vk:androidsdk:2.6.0'
...
}
в main activity пытаюсь написать import com.vk.sdk...
но после com.vk. предлагает только api, sdk там нет, не знаю как это исправить, помогите

**Comment by JaneySprings** [comment]
Там проект состоит из двух модулей, один с SDK, а другой с классами ответа (API). При такой зависимости в dependencies, Gradle импортирует только модуль SDK, это видно в его кешах (в .jar файле версии 2.6.0 только sdk модуль). Возможно он добавляется какой-то отдельной зависимостью (com.vk:androidapi:2.6.0 или т.п, но в readme составлен на версию 2.4). У меня в репозитории (Cappuccino-core) есть пара моделей и запросов, которые были еще для старых версий sdk, если очень хочется, можно пока пользоваться ими, а не новой сериализацией данных. 
P.S. У моего приложения на SDK 2.6.0 не работает вход. VK.Login вместо открытия офф. ВК вылетает приложение с логом "AppId is empty!", хотя app_id указан в ресурсах и называется также, как и в примерах.

**Comment by fakheet** [comment]
@JaneySprings на 2.4.0 тоже ничего не импортируется, откуда брать классы для запросов по документации не понятно

**Comment by UBaHbI4** [comment]
Вообще не понятно. Кроме VK.login ничего не получается сделать. Подробной информации 0.

**Comment by SergJ4** [comment]
Вот тут выложили модуль недавно с модельками. https://mvnrepository.com/artifact/com.vk/androidsdkapi

**Comment by Artemych** [comment]
```
dependencies {
    implementation 'com.vk:android-sdk-core:3.x.x
    implementation 'com.vk:android-sdk-api:3.x.x // generated models and api methods
}
```
