### ISSUE TITLE
Начиная с версии 2.6.0 дублируются запросы на сервер

### ISSUE THREAD

**Issue by Litesav-L** [VKCOM/vk-android-sdk#471]
Проблема заключается в дублировании запросов на сервер при фактическом выполнении кода 1 раз в Android SDK(Kotlin). Это происходит вне зависимости от заданного интервала между запросами и результатов предыдущих запросов. В версии 1.6.9 таких проблем нет, в 2.6.0 появилась

**Comment by olegsm** [comment]
Добрый день, попробуйте версию 3.0.0
