### ISSUE TITLE
Логин не проходит в 3.2.2

### ISSUE THREAD

**Issue by 3DanD** [VKCOM/vk-android-sdk#487]
Обновили игру на версию 3.2.2. Игроки стали часто жаловаться на ошибки логина.
Кто-то жмёт кнопку "разрешить" в окне запроса разрешения доступа к игре, и вместо успешного логина снова попадает в то же самое окно разрешения.
Кто-то при этом ловит ошибку net::ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY (см. https://github.com/VKCOM/vk-android-sdk/issues/486).
Кто-то net::ERR_FAILED.
Не знаю, связаны ли между собой эти ошибки. На наших устройствах не воспроизводится, судим по скринам в техподдержку.

**Comment by libalex** [comment]
Недавно тоже столкнулся с `net::ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY` при авторизации на устройстве без установленного приложения VK, т.е. когда форма авторизация должна открыться в WebView. В причинах до конца не разобрался.

**Comment by Artemych** [comment]
А какая версия chrome и webview стоит на устройстве?

**Comment by 3DanD** [comment]
Игрок прислал [видео проблемы](https://cloud.mail.ru/stock/71atZdmcmLvgpcpRyZJHoYmE).

Собираем с игроков данные о версиях приложения ВК и Google Chrome.
Пока версии прислал только один человек. VK 6.51, Chrome 92.0.4515.159. На моём телефоне эти же версии. Всё, что мне удалось добиться:
1. запускаю игру с 4g соединением, логинюсь в вк.
2. выгружаю игру.
3. Выключаю 4g.
4. Включаю Wi-Fi
5. Запускаю игру
6. После первого нажатия "разрешить" в окне запроса от вк тут же вылезает второе окно. После второго нажатия "разрешить" логин проходит нормально.

Предположу, что проблемы игроков могут быть связаны с нестабильным соединением или прокси сервером, то есть меняющимся IP адресом.

**Comment by 3DanD** [comment]
Также некоторые игроки жалуются на невозможность отправки подарков - вылезают ошибки. Один прислал скрин, там ошибка `net::ERR_CONNECTION_REFUSED`.

У большинства на скринах сеть мобильная.

Есть что-нибудь по ошибке с логином? Проблема массовая, её бы решить поскорее.

**Comment by 3DanD** [comment]
Мы запрашиваем переавторизацию, когда просрочен токен. Видимо, проблема в нём. В версии sdk 1.6, которой мы пользовались ранее, токен не становился невалидным при смене сети/айпишника
```
        VKTokenExpiredHandler vkAccessTokenTracker = new VKTokenExpiredHandler() {
            @Override
            public void onTokenExpired() {
                m_Token = null;
                VK.login(getActivity(), m_Scope);
            }
        };
```

**Comment by Artemych** [comment]
А можно вас попросить показать пример вызова VK.login(activity, scopes). Интересуют 2 момента: 
- скопы с которыми вы идете на логин
- версия апи которую вы используете для работы с api
- так же нет ли переопределений версии api или каких-либо других изменений в конфиге по умолчанию сетевого клиента задается через VK.setConfig

**Comment by 3DanD** [comment]
- Скопы: VKScope.FRIENDS, VKScope.WALL, VKScope.GROUPS
- com.vk:android-sdk-api:3.2.2
- setConfig не используем

**Comment by neikist** [comment]
Из сегодняшнего отзыва пользователя, как понимаю приложение не установлено и открывается веб вью
`Не смог зайти через ВК. Ошибка постоянно: net::ERR_NAME_NOT_RESOLVED.`

**Comment by Klug76** [comment]
It might be better to to use Custom Tabs instead of WebView. See https://developer.chrome.com/docs/android/custom-tabs/, and facebook sdk for examples.

**Comment by libalex** [comment]
Actually Custom Tabs recommended to use instead WebView also by security reasons.

**Comment by Artemych** [comment]
> * Скопы: VKScope.FRIENDS, VKScope.WALL, VKScope.GROUPS
> * com.vk:android-sdk-api:3.2.2
> * setConfig не используем

Проблема с разлогином при смене ip должна быть решена в 3.3.0. Попробуйте, пожалуйста, новую версию.

**Comment by Artemych** [comment]
> Эта проблема воспроизводится и на Google Play эмуляторах с установленным приложением VK:
> 
> ```
> VK.initialize(application)
> VK.login(activity, setOf(VKScope.EMAIL, VKScope.FRIENDS, VKScope.OFFLINE))
> ```
> 
> В `VKAuthCallback` после `onActivityResult` вызывается метод `onLoginFailed` с ошибкой:
> 
> ```
> com.vk.api.sdk.exceptions.VKAuthException: Auth canceled
> at com.vk.api.sdk.auth.VKAuthManager.onActivityResult(VKAuthManager.kt:86)
> at com.vk.api.sdk.VK.onActivityResult(VK.kt:164)
> at com.vk.api.sdk.VK.onActivityResult$default(VK.kt:157)
> ```
> 
> При этом пользователь авторизован в VK на этом же эмуляторе, что совпадает с репортами наших пользователей.

Можно попросить пошарить точную конфигурацию эмулятора, пожалуйста? И так же версии webview и chrome

**Comment by dkostyrev** [comment]
Конфигурация эмулятора (Nexus 5 API 28 Google Play):


```
AvdId=Nexus_5_API_28
PlayStore.enabled=true
abi.type=x86
avd.ini.displayname=Nexus 5 API 28
avd.ini.encoding=UTF-8
disk.dataPartition.size=10G
fastboot.chosenSnapshotFile=
fastboot.forceChosenSnapshotBoot=no
fastboot.forceColdBoot=no
fastboot.forceFastBoot=yes
hw.accelerometer=yes
hw.arc=false
hw.audioInput=no
hw.audioOutput=no
hw.battery=yes
hw.camera.back=virtualscene
hw.camera.front=emulated
hw.cpu.arch=x86
hw.cpu.ncore=4
hw.dPad=no
hw.device.hash2=MD5:041eb4f348dec9fd18091e32004fae73
hw.device.manufacturer=Google
hw.device.name=Nexus 5
hw.gps=yes
hw.gpu.enabled=yes
hw.gpu.mode=auto
hw.initialOrientation=Portrait
hw.keyboard=yes
hw.lcd.density=480
hw.lcd.height=1920
hw.lcd.width=1080
hw.mainKeys=no
hw.ramSize=1536
hw.sdCard=yes
hw.sensors.orientation=yes
hw.sensors.proximity=yes
hw.trackBall=no
image.sysdir.1=system-images/android-28/google_apis_playstore/x86/
runtime.network.latency=none
runtime.network.speed=full
sdcard.size=4G
showDeviceFrame=no
skin.dynamic=yes
skin.name=1080x1920
skin.path=_no_skin
skin.path.backup=/Users/dkostyrev/Library/Android/sdk/skins/nexus_5
tag.display=Google Play
tag.id=google_apis_playstore
vm.heapSize=128
```

Версия `com.android.chrome` 
```
versionCode=349710017 minSdk=24 targetSdk=28
versionName=69.0.3497.100
```

Версия `com.google.android.webview`
```
versionCode=349710065 minSdk=24 targetSdk=28
versionName=69.0.3497.100
```

Приложение `com.google.android.webview` из Google Play Store установить на этот эмулятор невозможно.

**Comment by Artemych** [comment]
к слову говоря версия chrome довольно старая. текущая мажорная 94

**Comment by dkostyrev** [comment]
Обновление chrome действительно решает проблему, спасибо!

**Comment by Artemych** [comment]
Стоит попросить пользователей обновить chrome на актуальную версию тк это именно ошибка webview(chrome) соотвественно.
