### ISSUE TITLE
authorization I do not use VK.login

### ISSUE THREAD

**Issue by ragnaros12** [VKCOM/vk-android-sdk#488]
is it possible to authorize a user without this method. Or can you change the design of the account access window, and the authorization window itself?

**Comment by libalex** [comment]
> is it possible to authorize a user without this method.
AFAIK, it isn't possible.
> Or can you change the design of the account access window, and the authorization window itself?
Why?

**Comment by ragnaros12** [comment]
@libalex, Sorry, I was wondering if I can write a custom login layout design?
