### ISSUE TITLE
Сборка падает после обновления на версию 3.2

### ISSUE THREAD

**Issue by neikist** [VKCOM/vk-android-sdk#489]
После обновления сборка начала падать с ошибкой
`More than one file was found with OS independent path 'META-INF/core_release.kotlin_module'.`
С чем конфликтует - выяснить не смог, в ветке в которую подтянул обновление слишком много доработок за 3 месяца.

**Comment by Artemych** [comment]
Проверьте пожалуйста версию 3.3.0

**Comment by neikist** [comment]
Да, спасибо, с этой версией проблем со сборкой нет.
