### ISSUE TITLE
sdk_fingerprint is incorrect

### ISSUE THREAD

**Issue by 0XRAgit** [VKCOM/vk-android-sdk#490]
Ошибка:
{"error":invalid_request", "error_description":"sdk_fingerprint is incorrect"}

Интегрировал OAuth vk с помощью com.vk:androidsdk:2.2.0 в приложение для аутинфикации. При аутинфикации с устройства без установленного приложения Vk - всё работает корректно, а при установленном - вылетает ошибка, указанная выше. Отпечаток сертификата - корректен, проверялся не раз.

Используемые технологии/устройства:
com.vk:androidsdk:2.2.0
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 34
Redmi Note 7
Android 10 QKQ1
MIUI Gobal 12.5.1

**Comment by 0XRAgit** [comment]
sha вводил и с двоеточием, и без.
проверил лишних пробелов не стоит

**Comment by olegsm** [comment]
Один или два у вас сертификата? необходимо проверить, что используется нужный.
На всякий случай рекомендую использовать последнюю версию  3.2.2

**Comment by 0XRAgit** [comment]
При попытке подключить версию 3.2.2:
Could not find com.vk:androidsdk:3.2.2.
Required by:
    project :app
Указано один sha, но 2 раза. Один с двоеточиями, второй без, какой оставить?

**Comment by libalex** [comment]
SHA-1 отпечаток сертификата нужно указывать [без двоеточий](https://vk.com/dev/android_sdk).
Обратите внимание на имя пакета и главной Activity - может там опечатка?

**Comment by 0XRAgit** [comment]
Удалю с двоеточиями.
Перепроверил несколько раз.
Main activity для Android - MainActivity
Название пакета для Android - ru.ecoline.app

**Comment by Artemych** [comment]
При попытке подключить версию 3.2.2:
Could not find com.vk:androidsdk:3.2.2.

dependencies {
    implementation 'com.vk:android-sdk-core:3.x.x
    implementation 'com.vk:android-sdk-api:3.x.x // generated models and api methods
}

**Comment by Artemych** [comment]
Проверьте пожалуйста, совпадает ли сертификат, которым подписывается приложение и тот от которого берется fingerprint?

**Comment by 0XRAgit** [comment]
Имплементировал эти либы:
dependencies {
    implementation 'com.vk:android-sdk-core:3.x.x
    implementation 'com.vk:android-sdk-api:3.x.x // generated models and api methods
}

**Comment by 0XRAgit** [comment]
Совпадают сертификаты

**Comment by djdance** [comment]
оффтоп:

а какой командой смотреть в консоли SHA? раньше была вот такая функция, а теперь?

`VKUtil.getCertificateFingerprint(this,this.getPackageName())`
