### ISSUE TITLE
Вопрос - можно ли понизить android::minSdkVersion

### ISSUE THREAD

**Issue by Klug76** [VKCOM/vk-android-sdk#494]
Вопрос - можно ли понизить android::minSdkVersion c ``minSdk: 21,`` до 17 или даже 15? Понимаю что поддержка legacy устройств не в приоритете но все же..

**Comment by olegsm** [comment]
Добрый день! к сожалению это не возможно уже в рамках официального SDK, но всегда можно взять API секцию https://github.com/VKCOM/vk-android-sdk/tree/master/api/src/main/java/com/vk/sdk/api и адаптировать под свои нужды.
