### ISSUE TITLE
Auth webview not displayed on a real device

### ISSUE THREAD

**Issue by rocklass** [VKCOM/vk-android-sdk#514]
Hello there 👋 
I try to login with `ActivityResultLauncher` method by calling `com.vk.api.sdk.VK#login(androidx.activity.ComponentActivity, androidx.activity.result.ActivityResultCallback<com.vk.api.sdk.auth.VKAuthenticationResult>)`.
When doing so, the authentication webview is not displayed on a real device while it works on an emulator.
When VK app is installed on the phone, I can login without any issue.
Version: 3.5.2

https://user-images.githubusercontent.com/7993662/190680108-61ea8490-e64d-4ecd-b5fa-519731077da6.mp4

**Comment by iliailemkov** [comment]
Hello, @rocklass! 
Could you give a little bit more information: device vendor, firmware, webview version etc? 
Maybe have you configured proxy in network?

**Comment by rocklass** [comment]
Hi @iliailemkov 
I reproduce the issue on several devices:
- OnePlus BE2029 - Android 11 - Android System Webview version 108.0.5359.79
- Google Pixel 6 - Android 13 - Android System Webview version 107.0.5304.141

**Comment by rocklass** [comment]
The root cause was that I still have the legacy dependency (version 1.6.9).
Removing the legacy dependency fix the issue.
