### ISSUE TITLE
invalid token

### ISSUE THREAD

**Issue by zhiqiangluo** [VKCOM/vk-android-sdk#515]
{“error”：“invalid-token”. "errror_description":"token is incrorrect"} 
this issue occurs when I use vk_android_sdk 3.5.2，The problem has not been fixed

**Comment by maximgavrilov** [comment]
Скорее-всего причина связана с тем, что форсится добавление Scope.OFFLINE, а он не поддерживается уже больше двух лет.

https://github.com/VKCOM/vk-android-sdk/blob/e5ef9f63070c038c9cfbb8667ed463cadabf9ad7/core/src/main/java/com/vk/api/sdk/auth/VKAuthManager.kt#L137

**Comment by iliailemkov** [comment]
@zhiqiangluo could you give more info?

**Comment by olegsm** [comment]
Can't reproduce without info.
Reopen this issue if it appears again.
