### ISSUE TITLE
VK.login через фрагменты

### ISSUE THREAD

**Issue by VixonneN** [VKCOM/vk-android-sdk#516]
Как сделать авторизацию через фрагменты? Когда я вызываю во фрагменте registerForActivityResult(...) мне не приходит никакой ответ в VkAuthenticationResult, но при этом регистрация проходит

**Comment by VixonneN** [comment]
Разобрался, не надо было дополнительно вызывать VK.login()

**Comment by petersamokhin** [comment]
@VixonneN 😉 https://vksdk.github.io/vk-sdk-android/auth/
