### ISSUE TITLE
Не работает вход через Web View

### ISSUE THREAD

**Issue by polkanovns** [VKCOM/vk-android-sdk#518]
В версии 3.5.2 не работает вход через вэб вью, причем вход через приложение VK работает корректно.
Отображается ошибка
```
{"error":"invalid_request","error_description":"invalid scope"}
```

SDK генерирует для вэб вью следующую ссылку (подставьте свой client_id для проверки): https://oauth.vk.com/authorize?client_id=client_id&scope=OFFLINE%2CWALL%2CPHOTOS%2CFRIENDS%2CGROUPS&redirect_uri=https%3A%2F%2Foauth.vk.com%2Fblank.html&response_type=token&display=mobile&v=5.131&revoke=1
вход вызывается следующим образом:
```
VK.login(activity, listOf(VKScope.FRIENDS, VKScope.WALL, VKScope.PHOTOS, VKScope.GROUPS))
```

Версия SDK 3.2.2 генерирует рабочую ссылку https://oauth.vk.com/authorize?client_id=client_id&scope=FRIENDS%2CWALL%2CPHOTOS%2CGROUPS&redirect_uri=https%3A%2F%2Foauth.vk.com%2Fblank.html&response_type=token&display=mobile&v=5.131&revoke=1

Проблема в том, что в последних версиях SDK добавляет OFFLINE scope, который все ломает.
```
    private fun prepareScopes(scopes: Collection<VKScope>): Collection<VKScope> {
        if (!scopes.contains(VKScope.OFFLINE)) {
            return scopes + VKScope.OFFLINE
        }
        return scopes
    }
```
Если поиграться со ссылками, то видно, что начиная с версии API 5.105 OFFLINE scope перестал поддерживаться.

**Comment by iliailemkov** [comment]
@polkanovns, привет! Да все верно с 5.105 нельзя использовать notify и offline скоупы для встраиваемых приложений. 
Метод помечен как устаревший, можно попробовать через `ActivityResultLauncher`.

**Comment by polkanovns** [comment]
@iliailemkov 
вижу, что список скопов модифицируется только для устаревшего метода login(), так может убрать неверную логику или вообще удалить этот метод, если он в работает некорректно?

**Comment by olegsm** [comment]
SDK обновлено до 4.0.0 версии, устаревшие методы удалены.

**Comment by petersamokhin** [comment]
@polkanovns @iliailemkov 😉 https://vksdk.github.io/vk-sdk-android/auth/
