### ISSUE TITLE
net::ERR_FAILED или net::ERR_ADDRESS_UNREACHABLE

### ISSUE THREAD

**Issue by ilyamuromets** [VKCOM/vk-android-sdk#519]
Вижу, что многие сталкиваются с аналогичной проблемой причём даже на самой последней версии. Но опишу свой кейс.
Я использую старую библиотеку - com.vk:androidsdk:2.2.3
Пытаюсь авторизоваться через браузер (нет установленного приложения) и вместо формы получаю AlertDialog с текстом из заголовка (1-ый случается только при чистой установке приложения далее всегда случается 2-ой) - срабатывает WebViewClient.onReceivedError() с этими ошибками.
Я попытался отпроксировать запросы (mitmproxy) и при подключенной проксе всё запустилось, никаких ошибок и веб-форма загружается.

Как побороть?

**Comment by olegsm** [comment]
Лучше проверить на последней версии  SDK - 4.0.0
