### ISSUE TITLE
Как использовать библиотеку из проекта на java

### ISSUE THREAD

**Issue by panovvitalik** [VKCOM/vk-android-sdk#525]
Как обычно при попытке перехода к более новой версии: 4.0.1 (с 3.2.2) все сломалось. 
Проект на java. 
Есть возможность как-то использовать данную библиотеку из проекта на java?

Например, как для начала теперь делать логин?

Раньше была одна строчка кода: 
`VK.login(activity, ListUtils.createObjectList(VKScope.PHOTOS, VKScope.OFFLINE))`

Теперь предлагается написать что-то типа: 
`ActivityResultLauncher launcher = VK.login(activity, new ActivityResultCallback<VKAuthenticationResult>() {`
`                    @Override`
`                    public void onActivityResult(VKAuthenticationResult result) {`
`                        // Что здесь нужно добавить, чтобы обработать success резалт???`
`                    }`
`                });`
`        launcher.launch(ListUtils.createObjectList(VKScope.PHOTOS, VKScope.OFFLINE));`

Но как дописать этот кусок кода?

p.s.
И пожалуйста вопрос конкретный! - указан в теме поэтому не нужно предлагать: 
- "все переходят на котлин", 
- "перепешите проект на котлин", 
- "перепешите классы работы с вк библиотекой на котлин" 
и т.п......

**Comment by libalex** [comment]
Ну вот на Kotlin пример выглядит так:

```kotlin
val authLauncher = VK.login(activity) { result : VKAuthenticationResult ->
    when (result) {
        is VKAuthenticationResult.Success -> {
            // User passed authorization
        }
        is VKAuthenticationResult.Failed -> {
            // User didn't pass authorization
        }
    }
}
```

На Java можно написать примерно так:

```java
ActivityResultLauncher authLauncher = VK.login(activity, new ActivityResultCallback<VKAuthenticationResult>() {
    @Override
    public void onActivityResult(VKAuthenticationResult result) {
        if (result instanceof VKAuthenticationResult.Success) {
            // User passed authorization
        }
        if (result instanceof VKAuthenticationResult.Failed) {
            // User didn't pass authorization
        }
    }
});
```

Ну и дальше можно обрабатывать результат авторизации.

**Comment by panovvitalik** [comment]
@libalex 
"instanceof" - действительно, - два разных класса теперь сделали. Спасибо! 
Попробую дальше тогда....
