### ISSUE TITLE
NullPointerException when using ActivityResultLauncher 

### ISSUE THREAD

**Issue by rocklass** [VKCOM/vk-android-sdk#526]
Hello there 👋 
Some of our users encountered a crash when login with VK.
The root cause is a `NullPointerException` when using the `ActivityResultLauncher<Collection<VKScope>>` provided by `VK.login(activity)`.

Here is the stacktrace:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.activity.result.ActivityResultLauncher.b(java.lang.Object)' on a null object reference
       at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
       at ******.launch(***.kt:54)
```

SDK version: 4.0.1
Android minSdkVersion 23
Android targetSdkVersion 31
Android compileSdkVersion 32

**Comment by trepolon** [comment]
You found a solution?

**Comment by trepolon** [comment]
I have authorization performed without problems, but a NullPointerException occurs after calling a SDK API method. I downgraded to 3.5.2 and the problem is gone.
