### ISSUE TITLE
Требуется помощь с FCM

### ISSUE THREAD

**Issue by rr8733380** [VKCOM/vk-android-sdk#530]
Добрый день. Подскажите пожалуйста как настроить Push-уведомления - FCM (уведомления для Android), не GCM. На сайте нет документации по этом поводу. В интернете тоже нет никакой информации. Помогите пожалуйста.

**Comment by ivanmalikov394** [comment]
> Добрый день. Подскажите пожалуйста как настроить Push-уведомления - FCM (уведомления для Android), не GCM. На сайте нет документации по этом поводу. В интернете тоже нет никакой информации. Помогите пожалуйста.
