### ISSUE TITLE
sdk options is undefined

### ISSUE THREAD

**Issue by deadfan** [VKCOM/vk-android-sdk#547]
If the app is not installed on the mobile phone, the webpage login is normal, if the vk app is installed, an error is reported in the picture

{“error”：“invalid_request","error_description":"sdk options is undefined"}

**Comment by LordOfTheApples123** [comment]
I was struggling on the same problem, so here's what i found. This sdk is not compatible with mobile apps, it only works with web. Try using VK ID. https://id.vk.com/about/business/go/docs/ru/vkid/latest/vk-id/intro/start-page. Doc is in russian, but it's the most relevant. 
BUT!!! you will need to create new app in https://id.vk.com/about/business/go. Using the same app id on old sdk leads to errors when using new VK ID sdk.

**Comment by deadfan** [comment]
Thank you for the tip. Спасибо большое
