### ISSUE TITLE
VKRequest.executeWithListener не вызывает listener при вызове не из главного потока

### ISSUE THREAD

**Issue by int02h** [VKCOM/vk-android-sdk#66]
Раньше можно было вызвать следующий код

``` java
request.executeWithListener(listener);
```

как в главном потоке, так и в фоновом. После обновления SDK до версии 1.3.2 у меня стали падать тесты, который вызывали этот код в фоновом потоке. Причем сам запрос обрабатывается корректно, но вот методы listener'а не вызываются. Например, если делать пост в фоновом потоке при помощи следующего кода

``` java
final VKRequest request = VKApi.wall().post(params);
request.executeWithListener(listener);
```

то пост фактически появится на стене, но обратного вызова никакого не будет.

В документации нигде не сказано про главный поток.

**Comment by fedotxxl** [comment]
Столкнулся с аналогичной проблемой.
Как подождать результат при вызове `executeWithListener`? Я был абсолютно уверен, что listener вызывается в другом потоке, поэтому ждал результат при помощи `CountDownLatch` -> deadlock

**Comment by dkostryukov** [comment]
@fedotxxl в новой версии появился метод executeSyncWithListener

**Comment by sjkrypa** [comment]
Всем привет. Столкнулся с похожей проблемой, только в Xamarin. Использую метод ExecuteSyncWithListener. Решение так и не было найдено?
