### ISSUE TITLE
Toast with "Be sure to call this using startActivityForResult()"

### ISSUE THREAD

**Issue by kirussell** [VKCOM/vk-android-sdk#73]
Hello, I suppose toast's show() method is called in VK application itself http://joxi.ru/J142VIwyTJC-AsS0yig
We've found it with "Don't keep activities" option turned on and installed VK application.
Steps from our testing team:
1. Check "Don't keep activities" options is turned on in Developers menu
2. Check if Vk application is installed
3. Start YourApp authorize with VK SDK
4. After authorization completed sucessfully Toast with "Be sure to call this using startActivityForResult()" appeared

Hope it will be hepfull.

**Comment by SuleymanovTat** [comment]
We've found this problem on VK application site. I notify you about result 
решили проблему?

**Comment by akulyakhtin** [comment]
Facing the same "Be sure to call this using startActivityForResult()"  toast here, too. Is there any workaround?

**Comment by ArtiX-GP** [comment]
I tried to log in through the application VK, but saw a toast "Be sure to call this using startActivityForResult()". How to solve this problem?

**Comment by ArtiX-GP** [comment]
I found a solution to the problem!
Однако мне лень дальше писать на английском.
Я просто убрал в манифесте строки:
android:configChanges="keyboardHidden|orientation|screenSize"
android:launch mode="singleInstance"
И все заработало.

**Comment by akulyakhtin** [comment]
У меня таких строк нет и тост есть.

**Comment by ArtiX-GP** [comment]
Хмм.. Ты пришли код своей activity, сравним его с моим, потому что у меня таких проблем нет

**Comment by NAO3133** [comment]
Тоже поднимается такой тост в версии 1.6.1

**Comment by AlexeyMeshkov** [comment]
И в 1.6.3 тоже.

**Comment by olegsm** [comment]
Please, follow new SDK 2.0
