### ISSUE TITLE
Получение комментов с именем и аватаром отправителя

### ISSUE THREAD

**Issue by nullproduction** [VKCOM/vk-android-sdk#78]
Столкнулся с проблемой, в объекте класса VKApiComment не реализован доступ к имени отправителя и аватару.

При запросе комментов делаю патарметр "extended", true.
В json появляются поля profiles и groups.
Но проблема в том что в методе parse класса VKApiComment я получаю JSONObject с самим комментарием и не имею доступа к profiles и groups.

В каком направлении копать или как реализовать это дургим способом?

**Comment by PaulProject** [comment]
А можно более подробно написать, что получилось в итоге?
