### ISSUE TITLE
Авторизация на android в приложении на cordova

### ISSUE THREAD

**Issue by DrMoriarty** [VKCOM/vk-android-sdk#80]
Добрый день. 
Я пишу приложение на apache cordova и для этого приложения делаю ряд плагинов для социального шаринга. Само приложение VK настроено, логин и шаринг через iOS работают нормально.
На андроид в момент авторизации, когда появляется окно о предоставлении доступа приложению к аккаунту, в лог попадает такая ошибка:

```
11-10 16:39:25.647: E/Web Console(29873): Uncaught ReferenceError: onBodyResize is not defined at https://oauth.vk.com/authorize?revoke=1&response_type=token&scope=wall%2Coffline&redirect_uri=https%3A%2F%2Foauth.vk.com%2Fblank.html&sdk_package=ru.trilan.ironworld&display=android&client_id=4622186&sdk_fingerprint=145687CF4A8F1A34CEB1A3171267DF3E2DF09304&lang=ru&access_token=e9d4c11cff45bd72083ac1ff21df014166795a7bb9c87ca6404241be0844bbdc444202fbf4bf75c68e2ac&sig=3442b7933817bc81ea063b558e1fa652:23
```

После нажатия любой кнопки (отмена или разрешить) окно логина закрывается, но приложение не получает ни токена, ни сигнала об ошибке.

Исходный код  плагина тут: https://github.com/DrMoriarty/cordova-social-vk/blob/master/src/android/SocialVk.java

Вероятно проблема возникла из-за каких то моих неправильных действий. Буду рад, если вы подскажете мне пути решения.
Сам андроид версии: 4.2.2

**Comment by victoriaSh** [comment]
@DrMoriarty, как вам удалось сделать standalone авторизацию для cordova приложения?
установить и попробовать ваш модуль не получается, выходит ошибка. 
попыталась сделать сама что-то подобное, не могу связать java-код с javascript

**Comment by DrMoriarty** [comment]
@victoriaSh об ошибке сделайте тикет в  https://github.com/DrMoriarty/cordova-social-vk
я посмотрю, что такое
