### ISSUE TITLE
How to open VK app using a contact ID ? 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [VKCOM/vk-android-sdk#84]
For Facebook I can use this:
    final Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(String.format("fb://profile/%s", friendId)));

For LinkedIn I can use this:
    final Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(String.format("linkedin://profile/%s",  friendId)));

What can I do in order to open VK app for the page of the chosen VK-user ?

**Comment by jespertheend** [comment]
Is there any way to open the app with a share intent similar to https://vk.com/share.php?
