### ISSUE TITLE
Выполнение метода Execute

### ISSUE THREAD

**Issue by MaksimVinokurov** [VKCOM/vk-android-sdk#87]
Добрый вечер. У меня возникла задача в приложении: мне необходимо получить список последних сообщений для некоторых пользователей. Данную задачу я смог решить с помощью цикла в котором выполнял запрос метода messages.getDialogs и передавал параметром id пользователя.

Но это выполняется слишком долго и я решил объединить все в один метод execute. Я написал для него следующий код:

var ids = ["abc"];
var r = [];
while(ids.length > 0) 
{
r.push(API.messages.getDialogs({\"user_id\":ids.pop()}));
}
return r;

где abc - список id пользователей разделенный запятыми.

Затем этот код я пытаюсь выполнить при помощи Android VKSDK, но к сожалению получаю ошибку. Вот код которым я пытаюсь сделать запрос (codeText - содержит строку с кодом запроса):

VKRequest request = new VKRequest("execute", VKParameters.from("code", codeText, HttpMethod.GET);
VKJsonOperation oper = (VKJsonOperation)request.getOperation();
oper.start();
JSONObject obj = oper.getResponseJson();

Подскажите как можно выполнить данный запрос синхронно.

**Comment by MaksimVinokurov** [comment]
Роман, так реально решить проблему?


30 декабря 2014 г., 11:24 пользователь Макс Максов <
rdtwindowsphone@gmail.com> написал:

**Comment by Dreddik** [comment]
Так если вы научились обычные методы дёргать синхронно, в чём проблема с execute? Это такой же метод

**Comment by MaksimVinokurov** [comment]
Роман, я понял что немного неверно начал диалог. Вот код того как я делаю
запросы обычно:

@Override
public ArrayList<IUserProfile> search(String text, Long count, Long offset,
Integer cityId, Integer countryCode, Integer status,
Integer ageFrom, Integer ageTo) {
VKParameters params = VKParameters.from(VKApiConst.Q, text,
   VKApiConst.COUNT, count,
   VKApiConst.OFFSET, offset,
   VKApiConst.HAS_PHOTO, 1,
   VKApiConst.SEX, 1,
   VKApiConst.ONLINE, 1,
   VKApiConst.FIELDS, "photo_50,can_write_private_message");
if (cityId != null)
params.put(VKApiConst.CITY, cityId);
if (countryCode != null)
params.put(VKApiConst.COUNTRY, countryCode);
if (status != null)
params.put(VKApiConst.STATUS, status);
if (ageFrom != null)
params.put(VKApiConst.AGE_FROM, ageFrom);
if (ageTo != null)
params.put(VKApiConst.AGE_TO, ageTo);
 VKRequest request = VKApi.users().search(params);
VKJsonOperation oper = (VKJsonOperation)request.getOperation();
oper.start();
JSONObject obj =  oper.getResponseJson();
VKUsersArray userArray = new VKUsersArray();
try {
userArray.parse(obj);
} catch (JSONException e) {
e.printStackTrace();
}
ArrayList<IUserProfile> iuserArray = new ArrayList<IUserProfile>();
for (VKApiUserFull user:userArray)
iuserArray.add(new UserProfileImpl(user));
return iuserArray;
}

Как видите выполнение синхронно возможно, теперь у меня встала задача
выполнить метод execute точно таким же способом:
вот код для формирования метода:


StringBuilder sb = new StringBuilder();
sb.append("var ids = [");
for (int i = 0; i< ids.size(); i++) {
sb.append(String.valueOf(ids.get(i)));
if (i != ids.size() - 1)
sb.append(",");
else
sb.append("];");
}
sb.append("var r = []; while(ids.length > 0)
{r.push(API.messages.getDialogs({\"user_id\":ids.pop()}));}return r;");

После того как код метода сформирован, я выполняю сам запрос. Можете ли Вы
мне просто написать код синхронного запроса который будет работать. Заранее
спасибо. Я думаю такое объяснение гораздо понятнее.


8 января 2015 г., 21:33 пользователь Roman Truba <notifications@github.com>
написал:

**Comment by Dreddik** [comment]
Я вам лично ничего написать не могу.
Делайте по аналогии, если у вас так работает

**Comment by MaksimVinokurov** [comment]
Да вот в том то вся и проблема, что не работает!


10 января 2015 г., 20:37 пользователь Roman Truba <notifications@github.com>
написал:
