### ISSUE TITLE
Vkontakte login inside fragment

### ISSUE THREAD

**Issue by dhrumit123** [VKCOM/vk-android-sdk#90]
vkontakte login inside fragment is not working. Please help on this asap.

**Comment by Dreddik** [comment]
Try this asap
https://github.com/VKCOM/vk-android-sdk/issues/23#issuecomment-37731270

**Comment by dhrumit123** [comment]
Cant i write all the things including VKUIHelper inside fragment?

**Comment by Dreddik** [comment]
Did you try the example? What problem exactly do you have?
