### ISSUE TITLE
Странный баг с первым запросом

### ISSUE THREAD

**Issue by nullproduction** [VKCOM/vk-android-sdk#91]
Заметил странный баг, при открытии приложения делаю  VKRequest c методом "wall.get". И почему-то первый запрос занимает в среднем 2-3 секунды. Все последующии запросы работают быстро.
Ситуация наблюдается на genymotion android 2.3 и 4.4.
В чем может быть проблема?

**Comment by Dreddik** [comment]
Не представляю. Есть какие-нибудь варианты?

**Comment by nullproduction** [comment]
Можно закрывать. Баг скорее всего был связан с parse.com sdk. После его выпиливания, проблема пропала. Как именно он нарушал работу не могу сказать так как он предоставляется только в виде jar без исходного кода
