### ISSUE TITLE
Преобразование JSONObject в VKApiPost

### ISSUE THREAD

**Issue by lutean** [VKCOM/vk-android-sdk#92]
Подскажите, как можно преобразовать JSONObject в VKApiPost?

1. Выполняю VKApi.wall().get
2.Дальше так JSONObject result = (JSONObject)response.json.getJSONObject("response");
posts = result1.getJSONArray("items");
JSONObject post = posts.getJSONObject(1);

**Comment by Dreddik** [comment]
Посмотрите в #96
