### ISSUE TITLE
Maven package - javadoc/sources

### ISSUE THREAD

**Issue by ckesc** [VKCOM/vk-android-sdk#93]
Если подтягиваешь библиотеку как maven-зависимость с помощью gradle, то не подтягиваются исходники/javadoc несмотря на правильно настроенный `build.gradle`:
```gradle
idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
```
### Костыльное решение
Нашёл как можно это сделать костылём: в файле `.idea\libraries\androidsdk_1_3_6.xml`
Меняем
```xml
    <JAVADOC/>
```
на
```xml
    <JAVADOC>
      <root url="http://vkcom.github.io/vk-android-sdk/" />
    </JAVADOC>
```
(очевидно имя файла зависит от текущей версии)

**Comment by Dreddik** [comment]
Здравствуйте, извините, что так долго не отвечал.
На самом деле, я не знаю почему так происходит.
Можете дать чуть больше информации? Как именно подключается в gradle? Репозиторий настроен на maven central?

**Comment by ckesc** [comment]
Да. Беру всё с maven central. Подключаю как обычно 
```gradle
dependencies { 
    compile 'com.vk:androidsdk:+' 
} 
```

**Comment by Dreddik** [comment]
А плагин пробовали?
https://github.com/xujiaao/AARLinkSources

**Comment by ckesc** [comment]
Плагин не пробовал. Спасибо, попробую =)
