### ISSUE TITLE
Проблема показа ShareDialog под unity

### ISSUE THREAD

**Issue by dilshod** [VKCOM/vk-android-sdk#94]
Как мне показать ShareDialog если у меня основной активити не наследует от android.support.v4.app.Activity?
Метод ShareDialog.show требует тип android.support.v4.app.FragmentManager, а getFragmentManager() возвращает тип android.app.FragmentManager.

**Comment by Dreddik** [comment]
А как подключаете библиотеку?

**Comment by dilshod** [comment]
Создал android библиотеку в intellij idea положил ее в папку Plugins/Android, бросил все исходники туда, и собрал jar файл через ant. Все работает, только не получается показать ShareDialog.
Еще добавил свой activity:
```
public class VKActivity extends UnityPlayerActivity {
    @Override
    protected void onCreate(Bundle var1) {
        super.onCreate(var1);
        VKUIHelper.onCreate(this);
    }

    @Override
    public void onResume() {
        super.onResume();
        VKUIHelper.onResume(this);
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        VKUIHelper.onDestroy(this);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        VKUIHelper.onActivityResult(this, requestCode, resultCode, data);
    }
}
```

**Comment by Dreddik** [comment]
Тогда можно просто из исходников удалить 
``` import android.support.v4.app.DialogFragment; ```
Вместо него импортировать
``` import android.app.DialogFragment; ```

Просто в таком случае, у вас отвалится поддержка Android < 11

**Comment by dilshod** [comment]
Попробую, спасибо.
Еще вопрос, есть возможность обойтись без написания своего активити которая наследует от UnityPlayerActivity?
onCreate, onResume, onDestroy я могу вставить в нужные места, а вот с onActivityResult сложней.

**Comment by Dreddik** [comment]
Я думаю, что не получится, потому что SDK запускает Activity приложения ВК и ждёт от него результат

**Comment by dilshod** [comment]
Спасибо

**Comment by dilshod** [comment]
Еще пришлось закомментировать следующее в VKShareDialog.java:
```
        /*result.setOnCancelListener(new DialogInterface.OnCancelListener() {
            @Override
            public void onCancel(DialogInterface dialogInterface) {
                if (mListener != null) {
                    mListener.onVkShareCancel();
                }
                VKShareDialog.this.dismiss();
            }
        });*/
```
Из за нее вылетает.

И кстати я сделал чтобы он работал без своего activity. onactгivityresult используется только в VKOpenAuthActivity. Добавил в нее методы:
```

    /*
     * My custom hack for unity
     */
    protected void setActivityResult(int resultCode) {
        //setResult(resultCode);
        VKUIHelper.onActivityResult(this, VKSdk.VK_SDK_REQUEST_CODE, resultCode, null);
    }

    protected void setActivityResult(int resultCode, Intent data) {
        //setResult(resultCode, data);
        VKUIHelper.onActivityResult(this, VKSdk.VK_SDK_REQUEST_CODE, resultCode, data);
    }
```
И вызываю их вместо setResult.
