### ISSUE TITLE
Как сделать извлечение VKRequest в BroadcastReceiver?

### ISSUE THREAD

**Issue by nullproduction** [VKCOM/vk-android-sdk#95]
У меня есть BroadcastReceiver который запускается при старте приложения и при старте системы и повторяется каждые 15 минут. В нем делаю загрузку новых постов и получаю креш после запуска системы:

Caused by: java.lang.NullPointerException
 at com.vk.sdk.VKSdk.getAccessToken(VKSdk.java:344)

Крэш из-за того что VKSdk не была инициализированна. метод VKSdk.initialize я вызываю в методе onCreate моего главного контроллера, при запуске ресивера он не вызывается.

Как правильно инициализировать библиотеку в таком случае, без activity?

**Comment by nullproduction** [comment]
Сделал временное решение проблемы:

Перед запросом проверяю

if (VKSdk.instance() == null) {
        VKSdk.initialize(new LoginActivity().sdkListener, Config.get().vkAppId);
}

и устаавливаю язык по умолчанию, иначе приложение будет будеать из-за NullPointerException в методе getLang()

```
 VKRequest request = new VKRequest(
            "wall.get",
            params,
            VKRequest.HttpMethod.GET,
            PostsArray.class
        );
        request.setPreferredLang("ru");
```

**Comment by Dreddik** [comment]
В принципе, можно ининциализировать SDK два раза без проблем.
Однако, с контекстом действительно есть проблема.

**Comment by Dreddik** [comment]
Попробуйте устанавливать контекст этой функцией перед вызовом из сервиса

**Comment by nullproduction** [comment]
спасибо, так лучше. подскажите как обновить sdk если подключение через grable? 

     compile 'com.vk:androidsdk:+'

**Comment by Dreddik** [comment]
Надо будет подождать, пока обновится главный репозиторий

**Comment by CheslavT** [comment]
![default](https://cloud.githubusercontent.com/assets/10923242/6106820/a515d1d8-b06d-11e4-9e97-85cc570bec0f.png)
Где в классе VKUIHalper метод static public void setApplicationContext(Context appContext) {} ???

**Comment by Dreddik** [comment]
Пока что нет в документации, позже добавлю

**Comment by CheslavT** [comment]
А давно он появился? В моей версии SDK его нет. А как если что обновить SDK? Вы вверху отвечали уже на этот вопрос но я не понял, можно подробнее.

**Comment by Dreddik** [comment]
Добавлен на прошлой неделе
