### ISSUE TITLE
wall.get and parsedModel

### ISSUE THREAD

**Issue by misikch** [VKCOM/vk-android-sdk#96]
Как парсить стену в список постов? 
Запрос:
`VKRequest request2 = VKApi.wall().get(VKParameters.from(VKApiConst.OWNER_ID));`

В ответ приходит первая запись со стены, но парсинг в posts не идет:
`//VKApi mPost = ((VKList<VKApiPost>) responses[1].parsedModel).get(0);`

Много информации по тому как получить userInfo, постить информацию на стену, но как забрать правильно со стены реализация только на php

**Comment by nullproduction** [comment]
ну вы же берете нулевой элемент массива. уберите get(0) и будем вам список со всеми постами

**Comment by misikch** [comment]
Так я и первый элемент не получаю. Хотя в logcat я вижу json request и там первый пост со стены присутствует.

**Comment by misikch** [comment]
И ещё вопрос как написать `request`, чтобы получить 5 записей со стены

**Comment by misikch** [comment]
Точнее как написать параметры чтобы получить записи с `n` по `n+m`

**Comment by nullproduction** [comment]
Почитайте документация по sdk и документация по api в целом.
  Вот запрос 5 записей со стены: 
    ```
      VKParameters params = VKParameters.from(
            "owner_id", "1",
            "count", 5,
        );

        VKRequest request = new VKRequest(
            "wall.get",
            params,
            VKRequest.HttpMethod.GET,
            VKPostArray
        );
     ```

**Comment by Dreddik** [comment]
Это может показаться немного странным, но чтобы получить объекты постов, нужно передать параметр extended.
Ваш запрос будет выглядеть так
```
VKRequest request2 = VKApi.wall().get(VKParameters.from(VKApiConst.OWNER_ID, VKSdk.getAccessToken().userId, VKApiConst.EXTENDED, 1));

request2.executeWithListener(new VKRequestListener() {
    @Override
    public void onError(VKError error) {

    }

    @Override
    public void onComplete(VKResponse response) {
        VKList<VKApiPost> posts = (VKList<VKApiPost>) response.parsedModel;
        VKApiPost post = posts.get(0);
        Log.d("Post:", post.toString());
    }
});
```
