### ISSUE TITLE
Video direct or external links are empty on wall post

### ISSUE THREAD

**Issue by airstep** [VKCOM/vk-android-sdk#97]
Невозможно получить прямую либо внешнюю ссылку на видео с поста стены
VKApiPost -> VKAttachments -> if (attach instanceof VKApiVideo) (direct or external link issue)

**Comment by Dreddik** [comment]
Для получения прямых ссылок ваше приложение должно иметь доступ к прямой авторизации https://vk.com/dev/auth_direct
Это нужно обосновывать через службу поддержки.

**Comment by airstep** [comment]
Спасибо за быстрый ответ!

**Comment by airstep** [comment]
Разобрался, кому интересно: используем дополнительный запрос при помощи video.get (с установленным owner_id, а также videos = owner_id + "_" + video_id

**Comment by Dreddik** [comment]
А, так вы про это :)
В video.get можно передать extended, будут и обычные ссылки

**Comment by airstep** [comment]
Да - но это дополнительный запрос. Было бы хорошо если бы записи со стены уже имели extended ссылки.
