### ISSUE TITLE
Get albums

### ISSUE THREAD

**Issue by yarolegovich** [VKCOM/vk-android-sdk#98]
Здравствуйте, не нашел еще способа связаться, пишу тут.
В документации описывается photos.getAlbums метод, но в андроид-сдк на данный момент, как я понял, его нет?
Может есть аналоги?

**Comment by Dreddik** [comment]
Вы можете написать собственную реализацию, например
```
VKRequest albums = new VKRequest("photos.getAlbums",
        VKParameters.from(VKApiConst.PHOTO_SIZES, 1),
        VKRequest.HttpMethod.GET);
albums.setResponseParser(new VKParser() {
    @Override
    public Object createModel(JSONObject object) {
        return new VKList<>(object, VKApiPhotoAlbum.class);
    }
});
albums.executeWithListener(new VKRequest.VKRequestListener() {
    @Override
    public void onComplete(VKResponse response) {
        Log.d("Albums: ", response.parsedModel.toString());
    }
});
```

**Comment by IlyaPavlovskii** [comment]
При написании собственной реализации столкнулся с проблеммой - VKError errorCode: 15, Access denied. 
При чем другие методы, на базе VKRequest работают.

**Comment by IlyaPavlovskii** [comment]
Прошу прощения, решил проблему через ишью [44](https://github.com/VKCOM/vk-android-sdk/issues/44). Не передавал нужные scopes при логине.
